# ════════════════════════════════════════════════════════════════════════════
#              DATA TABLE GENERATOR — wares.xml → data/*.py
# ════════════════════════════════════════════════════════════════════════════
#
# Regenerates the ware-derived lookup tables in data/ straight from the game's
# own files, read out of the .cat/.dat archives (no extraction needed):
#
#   data/wares.py            WARE_NAMES, WARE_VOLUME, WARE_TRANSPORT,
#                            WARE_GROUPS (+ WARE_GROUP_PRIORITY, editorial)
#   data/ware_prices.py      WARE_PRICES
#   data/production_stats.py PRODUCTION_STATS
#
# Run it after a game update or DLC install:
#
#   python gamefiles/generate_data.py
#
# then review `git diff data/` — the diff IS the change report: every value
# the patch touched shows up as a changed line. Nothing else in the codebase
# needs to change; the generated files keep the exact same dict names and
# shapes the scanner already imports.
#
# DESIGN: generate-and-commit, not read-at-runtime. The data files stay
# importable without a game install (UI-only use, CI, other machines), and
# value changes arrive as reviewable diffs instead of silent runtime drift.
#
# WHAT COUNTS AS "EDITORIAL": WARE_GROUP_PRIORITY encodes our chosen station
# auto-naming order — it does not exist in the game files (waregroups.xml has
# a `tier` attribute but it orders tech progression, not naming priority), so
# it is emitted verbatim from the template below. Edit it HERE, not in the
# generated file.
# ════════════════════════════════════════════════════════════════════════════

import pathlib
import re
import sys

# Allow running as a script from anywhere: put the repo root on sys.path.
REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from lxml import etree as ET

from gamefiles.catalog import CatalogIndex, find_x4_install
from gamefiles.xmlpatch import apply_diff

DATA_DIR = REPO / "data"

# Wares the scanner needs that are NOT tagged "economy" in wares.xml:
# rawscrap/nividiumgems show up in station cargo (scrap processing, gem
# manufacture) so the volume/transport tables must cover them.
EXTRA_WARE_IDS = {"rawscrap", "nividiumgems"}

# Header prepended to every generated file. The per-file blocks below add
# their own table-specific documentation under it.
GENERATED_BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "#  AUTO-GENERATED by gamefiles/generate_data.py — DO NOT EDIT BY HAND.\n"
    "#  Source: libraries/wares.xml (+ DLC diffs) read directly from the X4\n"
    "#  install's .cat archives. Re-run after a game update or DLC install:\n"
    "#      python gamefiles/generate_data.py\n"
    "#  then review the git diff for what the patch changed.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)


# ──────────────────────────────────────────────────────────────────────────
#  Language-file text handling
# ──────────────────────────────────────────────────────────────────────────

# X4 t-file format:
#   - "{page,id}" references are the actual display text, composed at runtime.
#   - Leading "(...)" blocks are translator comments — always BEFORE the refs.
#     Strip them first so ref resolution sees only the content.
#   - "\(" and "\)" are escaped literal parentheses in the resolved text.
#
# The comment regex uses `(?:[^()\\]|\\.)*` so that escaped parens like \(Gas\)
# inside a comment (e.g. "(Magnetar \(Gas\) Vanguard)") are treated as
# non-delimiter characters and the whole comment matches cleanly.
_COMMENT_RE = re.compile(r'(?<!\\)\((?:[^()\\]|\\.)*\)')
_REF_RE = re.compile(r'\{\s*(\d+)\s*,\s*(\d+)\s*\}')


def clean_text(raw: str, texts: dict) -> str:
    """Strips translator comments, resolves {page,id} refs, unescapes parentheses.

    X4 t-file entries often look like:
        (Behemoth Vanguard){20101,11001} {20111,1101}
    The leading (...) is a translator comment; the refs ARE the actual text.
    The comment appears in the RESOLVED value (not the initial ref), so we must
    strip comments after each resolution pass, not just once up front.
    """
    for _ in range(4):  # 4 passes: enough for one level of ref nesting
        raw = _COMMENT_RE.sub("", raw).strip()   # strip comments from current value
        new = _REF_RE.sub(lambda m: texts.get(f"{m.group(1)}:{m.group(2)}", ""),
                          raw)
        if new == raw:
            break
        raw = new
    return raw.replace(r"\(", "(").replace(r"\)", ")").strip()


def load_texts(idx: CatalogIndex, page_ids: set[str]) -> dict:
    """{"page:id": raw text} for the requested pages of t/0001-l044.xml."""
    root = ET.fromstring(idx.read("t/0001-l044.xml"))
    texts = {}
    for page in root.findall("page"):
        if page.get("id") in page_ids:
            for t in page.findall("t"):
                texts[f"{page.get('id')}:{t.get('id')}"] = t.text or ""
    return texts


# ──────────────────────────────────────────────────────────────────────────
#  Game-data assembly
# ──────────────────────────────────────────────────────────────────────────

def load_merged_wares(idx: CatalogIndex):
    """Base wares.xml with every DLC's diff applied, in catalog order."""
    root = ET.fromstring(idx.read("libraries/wares.xml"))
    for vp in idx.find("extensions/*/libraries/wares.xml"):
        apply_diff(root, ET.fromstring(idx.read(vp)), source=vp)
    return root


def load_group_textids(idx: CatalogIndex) -> dict[str, int]:
    """
    waregroups.xml: group id → page 20215 base textId.
    e.g. "hightech" → 501; the factory display name sits at textId+3.
    """
    root = ET.fromstring(idx.read("libraries/waregroups.xml"))
    ids = {}
    for grp in root.findall("group"):
        m = _REF_RE.match(grp.get("name", ""))
        if m and m.group(1) == "20215":
            ids[grp.get("id")] = int(m.group(2))
    return ids


def select_wares(root) -> list:
    """
    The wares our tables cover: everything tagged "economy" (tradeable goods,
    including mineables and DLC wares) plus the explicit extras. Equipment,
    software, inventory items etc. are excluded — the scanner never sees them
    as cargo or production output.
    """
    out = []
    for w in root.findall("ware"):
        tags = (w.get("tags") or "").split()
        if "economy" in tags or w.get("id") in EXTRA_WARE_IDS:
            out.append(w)
    # Sorted by id so regeneration is deterministic → clean git diffs.
    out.sort(key=lambda w: w.get("id"))
    return out


# ──────────────────────────────────────────────────────────────────────────
#  File emitters
# ──────────────────────────────────────────────────────────────────────────

# WARE_GROUP_PRIORITY is editorial (see header) — emitted verbatim.
PRIORITY_BLOCK = '''
# ─────────────────────────────────────────────────────────────────────────────
#  WARE GROUP PRIORITY  (page 20215 base textId → priority rank)
#  EDITORIAL — maintained in gamefiles/generate_data.py, not derived from game
#  files. When a station produces wares from multiple groups, the group with
#  the lowest priority number wins and names the station, mirroring X4's own
#  auto-naming (hullparts + energycells → "High Tech Factory").
#  Groups absent from this dict rank last (language.py falls back to 999).
# ─────────────────────────────────────────────────────────────────────────────

WARE_GROUP_PRIORITY: dict[int, int] = {
    501:  1,   # High Tech Goods      → "High Tech Factory"
    1001: 2,   # Ship Technology      → "Ship Technology Factory"
    901:  3,   # Refined Goods        → "Refined Goods Complex"
    701:  4,   # Minerals             → "Mineral Refinery"
    401:  5,   # Gases                → "Gas Refinery"
    801:  6,   # Pharmaceutical Goods → "Pharmaceutical Goods Factory"
    101:  7,   # Agricultural Goods   → "Agricultural Goods Factory"
    301:  8,   # Food                 → "Farm"
    601:  9,   # Ice                  → "Ice Refinery"
    201: 10,   # Energy               → "Energy Complex"
    1201: 11,  # Water                → "Water Refinery"
}
'''


def _fmt_dict(name: str, type_hint: str, items: list[tuple[str, str]],
              comment: str = "") -> str:
    """Renders a dict literal with aligned values, one entry per line."""
    width = max((len(k) for k, _ in items), default=0) + 2  # +2 for quotes
    lines = [f"{name}: {type_hint} = {{"]
    for key, value in items:
        lines.append(f"    {('\"' + key + '\":').ljust(width + 1)} {value},")
    lines.append("}")
    return (comment + "\n" if comment else "") + "\n".join(lines) + "\n"


def gen_wares_py(wares, group_textids, texts) -> str:
    names, volumes, transports, groups = [], [], [], []
    for w in wares:
        wid = w.get("id")
        display = clean_text(w.get("name", ""), texts)
        names.append((wid, repr(display)))
        volumes.append((wid, f'{float(w.get("volume", "1")):.1f}'))
        transports.append((wid, repr(w.get("transport", "container"))))
        # WARE_GROUPS only covers wares buildable in a player station —
        # signalled in wares.xml by the presence of a factoryname reference.
        gid = group_textids.get(w.get("group", ""))
        if gid is not None and w.get("factoryname"):
            groups.append((wid, str(gid)))

    parts = [
        GENERATED_BANNER,
        _fmt_dict(
            "WARE_NAMES", "dict[str, str]", names,
            "\n# Ware id → display name (wares.xml name ref resolved via "
            "t/0001-l044.xml page 20201).\n"
            "# Used to label production modules and cargo; unknown ids fall "
            "back to title-case."),
        _fmt_dict(
            "WARE_VOLUME", "dict[str, float]", volumes,
            "\n# Ware id → volume in m³ per unit (wares.xml volume attribute)."
            "\n# Converts cargo amounts into m³ for storage fill percentages."),
        _fmt_dict(
            "WARE_TRANSPORT", "dict[str, str]", transports,
            "\n# Ware id → storage class: container / solid / liquid "
            "(wares.xml transport\n# attribute). Attributes trade "
            "reservations to the right storage type."),
        _fmt_dict(
            "WARE_GROUPS", "dict[str, int]", groups,
            "\n# Ware id → page 20215 base textId of its ware group "
            "(waregroups.xml).\n# Only wares with a factoryname in wares.xml "
            "(player-buildable) are listed.\n# The group factory display name "
            "lives at textId+3 — e.g. hightech 501 →\n# 504 \"High Tech "
            "Factory\" — the +3 offset X4 uses on this page."),
        PRIORITY_BLOCK,
    ]
    return "\n".join(parts)


def gen_ware_prices_py(wares) -> str:
    items = []
    for w in wares:
        p = w.find("price")
        if p is None:
            continue
        items.append((w.get("id"),
                      f'{{"min": {int(p.get("min", 0))}, '
                      f'"average": {int(p.get("average", 0))}, '
                      f'"max": {int(p.get("max", 0))}}}'))
    return GENERATED_BANNER + _fmt_dict(
        "WARE_PRICES", "dict[str, dict]", items,
        "\n# Ware id → market price band in credits (wares.xml <price>).\n"
        "# The station budget calculation values trade wares at the MAX "
        "price.")


def gen_production_stats_py(wares) -> str:
    blocks = []
    for w in wares:
        prods = w.findall("production")
        if not prods:
            continue  # mineables and pure trade goods have no recipe
        methods = []
        for prod in prods:
            inputs = {i.get("ware"): int(i.get("amount", 0))
                      for i in prod.findall("primary/ware")}
            input_str = ", ".join(f"'{k}': {v}" for k, v in sorted(inputs.items()))
            methods.append(f"            '{prod.get('method', 'default')}': "
                           f"{{{input_str}}},")
        # time/amount come from the FIRST (default) production entry; faction
        # methods only differ in inputs, which is all the methods dict holds.
        first = prods[0]
        blocks.append(
            f"    '{w.get('id')}': {{\n"
            f"        \"group\":   '{w.get('group', '')}',\n"
            f"        \"time\":    {int(float(first.get('time', 0)))},\n"
            f"        \"amount\":  {int(first.get('amount', 0))},\n"
            f"        \"methods\": {{\n" + "\n".join(methods) + "\n"
            f"        }},\n"
            f"    }},")
    return (GENERATED_BANNER +
            "\n# Ware id → production recipe (wares.xml <production> nodes)."
            "\n#   group   — ware category (wares.xml group attribute)"
            "\n#   time    — production cycle duration in seconds"
            "\n#   amount  — units produced per cycle"
            "\n#   methods — method id → {input ware: amount per cycle}."
            "\n#             'default' is the standard recipe; faction methods"
            "\n#             (teladi, split, ...) appear where inputs differ."
            "\n#             Empty dict = no inputs needed (energy cells).\n"
            "PRODUCTION_STATS: dict[str, dict] = {\n"
            + "\n".join(blocks) + "\n}\n")


# ──────────────────────────────────────────────────────────────────────────
#  station_names.py — WARE_FACTORY_NAMES
# ──────────────────────────────────────────────────────────────────────────

def gen_station_names_py(wares, texts) -> str:
    """
    Builds WARE_FACTORY_NAMES: ware_id → FactoryEntry(name, text_id).

    factoryname="{20201,N}" on each <ware> gives us the text_id (N). The
    factory display name sits at text_id itself on page 20201 (e.g. id 1204
    → "Hull Part Factory"). The ware display name sits at text_id-3 (1201 →
    "Hull Parts") — emitted as a comment so the file is self-documenting.
    Only wares with a factoryname reference are player-buildable and listed.
    """
    entries = []
    REF = re.compile(r'^\{(\d+),(\d+)\}$')
    for w in wares:
        fn = w.get("factoryname", "")
        m = REF.match(fn)
        if not m:
            continue
        text_id = int(m.group(2))
        factory_name = clean_text(texts.get(f"20201:{text_id}", ""), texts)
        ware_name    = clean_text(texts.get(f"20201:{text_id - 3}", ""), texts)
        if not factory_name:
            continue
        entries.append((w.get("id"), text_id, factory_name, ware_name,
                        w.get("group", "")))

    lines = [
        GENERATED_BANNER,
        "# Ware id → FactoryEntry(name, text_id) for player-buildable stations.",
        "# name     — factory display name from page 20201 of the language file",
        "# text_id  — page 20201 id; callers that need the ware display name",
        "#            find it at text_id-3 on the same page.",
        "#",
        "# Used by resolve_station_type() in scanner/language.py:",
        "#   • 1 unique ware produced → WARE_FACTORY_NAMES[ware_id].name",
        "#   • 2+ unique wares        → group factory name (data/wares.py WARE_GROUPS)",
        "",
        "from typing import NamedTuple",
        "",
        "",
        "class FactoryEntry(NamedTuple):",
        '    """Factory name and its page 20201 text ID from the X4 language file."""',
        "    name:    str  # display string, e.g. \"Hull Part Factory\"",
        "    text_id: int  # page 20201 id — ware display name is at text_id-3",
        "",
        "",
        "WARE_FACTORY_NAMES: dict[str, FactoryEntry] = {",
    ]
    # Group entries by ware group for readability, same as the hand-written file.
    from collections import defaultdict
    by_group = defaultdict(list)
    for eid, text_id, fname, wname, group in entries:
        by_group[group].append((eid, text_id, fname, wname))
    for group in sorted(by_group):
        lines.append(f"    # {group}")
        for eid, text_id, fname, wname in sorted(by_group[group]):
            lines.append(f'    "{eid}": FactoryEntry({repr(fname)}, {text_id}),'
                         f'  # display: {repr(wname)} (id {text_id - 3})')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────
#  ships.py + ship_stats.py
# ──────────────────────────────────────────────────────────────────────────

def load_ship_data(idx: CatalogIndex, texts: dict) -> list[tuple]:
    """
    Reads every ship_*.xml macro from the catalogs (base + DLC) and returns
    a list of (macro_id, display_name, ship_class, max_hull) tuples.

    DLC ship macros are full documents (not diffs), so they're simply parsed
    alongside the base-game ones — no patch application needed.
    """
    ships = []
    # Base game and DLC paths share the same inner structure; collect all at once.
    all_paths = (idx.find("assets/units/*/macros/ship_*.xml") +
                 idx.find("extensions/*/assets/units/*/macros/ship_*.xml"))

    for vp in all_paths:
        root = ET.fromstring(idx.read(vp))
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue

        macro_id   = macro_el.get("name", "")
        ship_class = macro_el.get("class", "")
        ident      = root.find(".//identification")
        hull_el    = root.find(".//hull")

        name_ref = ident.get("name", "") if ident is not None else ""
        display  = clean_text(name_ref, texts) if name_ref else macro_id

        max_hull = int(hull_el.get("max", 0)) if hull_el is not None else 0

        if macro_id:
            ships.append((macro_id, display, ship_class, max_hull))

    ships.sort(key=lambda s: s[0])
    return ships


def gen_ships_py(ships) -> str:
    items = [(macro_id, repr(display))
             for macro_id, display, _, _ in ships]
    return (GENERATED_BANNER +
            "\n# Ship macro id → display name (ship macro XML identification/@name\n"
            "# resolved via page 20101 of the language file).\n"
            "# Used by the ship scanner to label ships; unknown macros fall back\n"
            "# to hull origin + role derived from the macro name itself.\n" +
            _fmt_dict("SHIP_NAMES", "dict[str, str]", items))


def gen_ship_stats_py(ships) -> str:
    blocks = []
    for macro_id, _, ship_class, max_hull in ships:
        blocks.append(f"    '{macro_id}': {{\n"
                      f"        'class':    '{ship_class}',\n"
                      f"        'max_hull': {max_hull},\n"
                      f"    }},")
    return (GENERATED_BANNER +
            "\n# Ship macro id → static game stats (ship macro XML).\n"
            "#   class    — ship size class (ship_s, ship_m, ship_l, ship_xl, ship_xs)\n"
            "#   max_hull — base maximum hull HP before mods\n"
            "SHIP_STATS: dict[str, dict] = {\n" +
            "\n".join(blocks) + "\n}\n")


# ──────────────────────────────────────────────────────────────────────────

def main() -> int:
    game_dir = find_x4_install()
    if game_dir is None:
        print("FAIL: no X4 installation found — nothing generated.")
        return 1
    print(f"Reading game files from: {game_dir}")

    idx = CatalogIndex.from_game_dir(game_dir)

    # ── Wares (wares.xml + DLC diffs + waregroups.xml + t-file page 20201) ──
    wares_root = load_merged_wares(idx)
    wares = select_wares(wares_root)
    group_textids = load_group_textids(idx)
    # Page 20201 serves both the wares tables and station_names.
    texts_20201 = load_texts(idx, {"20201"})
    print(f"Selected {len(wares)} wares "
          f"({len(EXTRA_WARE_IDS)} via explicit extras list)")

    # ── Ships (ship macro XMLs + t-file pages 20101 + 20111) ────────────
    # 20101 — ship base names and full variant entries (refs to 20111)
    # 20111 — variant suffixes ("Vanguard", "Sentinel") and type qualifiers
    #         ("\(Gas\)", "\(Mineral\)") referenced inside the 20101 entries
    texts_ships = load_texts(idx, {"20101", "20111"})
    ships = load_ship_data(idx, texts_ships)
    print(f"Found {len(ships)} ship macros")

    outputs = {
        "wares.py":            gen_wares_py(wares, group_textids, texts_20201),
        "ware_prices.py":      gen_ware_prices_py(wares),
        "production_stats.py": gen_production_stats_py(wares),
        "station_names.py":    gen_station_names_py(wares, texts_20201),
        "ships.py":            gen_ships_py(ships),
        "ship_stats.py":       gen_ship_stats_py(ships),
    }
    for fname, content in outputs.items():
        path = DATA_DIR / fname
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"Wrote {path.relative_to(REPO)}")

    print("\nDone — review with: git diff data/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
