# Core role: Generates equipment catalog (weapons, turrets, shields, engines, thrusters) with calculated stats by parsing equipment macros from .cat/.dat archives.
#
# Output: data/equipment_stats.py with EQUIPMENT_STATS (macro → stats) and EQUIPMENT_ALIASES (aliases → canonical)
# Run after game update or DLC install: python gamefiles/generate_equipment.py
#
# DESIGN: generate-and-commit for reviewable diffs on game patches.
#
# Weapon damage is one hop away: weapon/turret/launcher macros reference bullet/missile macros which hold the damage values.
# Mines and spacesuit bomb launcher are excluded (not ship-hardpoint equipment).

import pathlib
import re
import sys

# Allow running as a script from anywhere: put the repo root on sys.path.
REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from lxml import etree as ET

from gamefiles.catalog import CatalogIndex, find_x4_install
from gamefiles.langtext import _REF_RE, clean_text, load_texts
from gamefiles.generate_data import load_macro_price_ranges
from gamefiles.xmlpatch import apply_diff

DATA_DIR = REPO / "data"

# Ship size classes as they appear as a token in a macro name
# (weapon_arg_m_ion_01_mk1_macro → "m"). Ordered longest-first so "xl"/"xs"
# are tested before the single-letter sizes when scanning tokens.
_SIZES = ("xs", "xl", "s", "m", "l")

GENERATED_BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "#  AUTO-GENERATED by gamefiles/generate_equipment.py — DO NOT EDIT BY HAND.\n"
    "#  Source: assets/props/{weaponsystems,surfaceelements,engines} + weaponfx\n"
    "#  bullet macros, read directly from the X4 install's .cat archives.\n"
    "#  Re-run after a game update or DLC install:\n"
    "#      python gamefiles/generate_equipment.py\n"
    "#  then review the git diff for what the patch changed.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)

# Field order for the emitted per-entry dicts: identity first, then the
# slot-specific stats. Absent fields are simply skipped. (heat_per_shot,
# heat_initial and is_beam are intermediate values used while computing the
# fields below and are deliberately NOT listed here, so they never reach the
# generated file.)
_FIELD_ORDER = [
    "slot", "class", "name", "mk", "size", "race", "group",
    "price", "price_min", "price_max",
    # weapon / turret
    "damage_hull", "damage_shield", "damage_hull_while_shielded",
    "reload_rate", "range_m", "projectile_speed_m_s",
    "ammo_clip", "ammo_clip_reload_s",
    "rotation_speed", "rotation_accel", "hull_max", "storage_capacity",
    "damage_rate_burst", "damage_rate_sustained",
    "time_to_overheat", "cooldown_duration",
    # shield
    "capacity", "recharge_rate", "recharge_delay", "disruption_stability",
    # engine
    "thrust_forward", "thrust_reverse",
    "travel_thrust", "travel_charge",
    "boost_thrust", "boost_duration", "boost_recharge",
    # thruster
    "strafe", "pitch", "yaw", "roll",
]


# ──────────────────────────────────────────────────────────────────────────
#  Small parse helpers
# ──────────────────────────────────────────────────────────────────────────

def _size_from_macro(macro: str) -> str | None:
    """The size token in a macro name, or None (e.g. lasertowers have none)."""
    toks = macro.split("_")
    for s in _SIZES:
        if s in toks:
            return s
    return None


def _group_from_path(vpath: str) -> str | None:
    """The weaponsystems category folder, e.g. .../weaponsystems/energy/... → 'energy'."""
    parts = vpath.split("/")
    try:
        return parts[parts.index("weaponsystems") + 1]
    except (ValueError, IndexError):
        return None


def _int(el, attr: str):
    """Attribute as int, or None if missing/blank/non-numeric."""
    if el is None:
        return None
    v = el.get(attr)
    try:
        return int(float(v)) if v not in (None, "") else None
    except (ValueError, TypeError):
        return None


def _round(el, attr: str, ndigits: int = 1):
    """Attribute as rounded float, or None if missing."""
    if el is None:
        return None
    v = el.get(attr)
    try:
        return round(float(v), ndigits) if v not in (None, "") else None
    except (ValueError, TypeError):
        return None


def _float(el, attr: str):
    """Attribute as unrounded float, or None if missing/blank/non-numeric."""
    if el is None:
        return None
    v = el.get(attr)
    try:
        return float(v) if v not in (None, "") else None
    except (ValueError, TypeError):
        return None


def _num(v):
    """Round to 3dp, then collapse to a plain int when that's exact (X4 damage/
    capacity values are almost always whole numbers; keeps the generated file's
    existing int-heavy style instead of sprouting '.0' on every multiplied value).
    3dp (not 1dp) so the UI has enough precision to truncate down to the in-game
    tooltip's displayed value instead of rounding to it -- the game truncates
    these derived stats, it doesn't round, so pre-rounding away the sub-tenth
    digits here would make that truncation impossible downstream."""
    if v is None:
        return None
    r = round(v, 3)
    return int(r) if r == int(r) else r


def _glob(idx: CatalogIndex, *patterns: str) -> list[str]:
    """Union of catalog matches for multiple wildcards."""
    seen: set[str] = set()
    for p in patterns:
        seen.update(idx.find(p))
    return sorted(seen)


_EXT_PREFIX_RE = re.compile(r'^extensions/[^/]+/')


def _load_merged_roots(idx: CatalogIndex, paths: list[str]) -> list[tuple[str, ET._Element]]:
    """Parses each catalog path, merging DLC files into their base-game
    counterpart at the same relative path before the caller ever sees them.

    Unlike wares.xml (one big file generate_data.py's load_merged_wares()
    diffs as a whole), equipment is one macro per file -- but a DLC can still
    ship a <diff> patching an existing base macro at the identical relative
    path (e.g. extensions/<dlc>/assets/.../weapon_x_macro.xml patching
    assets/.../weapon_x_macro.xml). Without this merge, that diff file was
    being parsed as its own standalone document and produced a second, sparse
    record for the same macro id -- the duplicate-equipment-entries bug.

    Returns (relative_path, merged_root) pairs, one per logical macro: base
    + merged diffs where a base file exists, or the DLC's own document where
    a DLC introduces a brand new macro (no base file to diff against).
    """
    by_relpath: dict[str, list[str]] = {}
    for vp in paths:
        rel = _EXT_PREFIX_RE.sub("", vp)
        by_relpath.setdefault(rel, []).append(vp)

    out: list[tuple[str, ET._Element]] = []
    for rel, group in by_relpath.items():
        # Base-game path (no extensions/ prefix) sorts first when present;
        # DLC diffs then apply on top of it in (deterministic) sorted order.
        group.sort(key=lambda vp: vp.startswith("extensions/"))
        root = ET.fromstring(idx.read(group[0]))
        for vp in group[1:]:
            patch_root = ET.fromstring(idx.read(vp))
            if patch_root.tag == "diff":
                apply_diff(root, patch_root, source=vp)
            else:
                # A second DLC shipping a full (non-diff) macro at the same
                # path is unexpected, but if it happens the later one wins --
                # same "later catalog overrides" rule the .cat index uses.
                root = patch_root
        out.append((rel, root))
    return out


# ──────────────────────────────────────────────────────────────────────────
#  Pass 1 — bullets (the weapon/turret damage table)
# ──────────────────────────────────────────────────────────────────────────

def load_bullets(idx: CatalogIndex) -> dict[str, dict]:
    """macro id → per-shot combat stats, for everything a <bullet class=.../>
    can point at: ordinary bullets AND missile macros (a missilelauncher/
    missileturret's <bullet class=.../> points at a missile_..._macro the
    exact same way a normal weapon's points at a bullet_..._macro -- just
    with <explosiondamage>/<missile> instead of <damage>/<bullet>).

      damage_hull, damage_shield, damage_hull_while_shielded
                  Per-SHOT damage, already multiplied by amount x barrelamount
                  -- X4 weapons often release several barrels/pellets per
                  trigger pull (e.g. the L Pulse Turret fires 2 barrels per
                  shot; the Shard Turret fires 6 pellets), and the raw
                  <damage value=> is only ONE of those. damage_shield is
                  damage_hull PLUS the bullet's shield= attribute (a bonus on
                  top, not a replacement total -- confirmed against the ARG
                  Ion Blaster Mk1/Mk2 tooltips: file hull=125 shield=500,
                  real Shield Damage shown is 625, i.e. hull+shield); defaults
                  to just the hull value when there's no shield= attribute at
                  all. Falls back to <areadamage value=>/<shield=> when
                  <damage> has no value= at all (flak-type weapons keep their
                  damage there).
      reload_rate Sustained shots/sec, averaged over a full ammo-clip-then-
                  reload cycle for weapons that have one. <reload> carries
                  EITHER rate= (shots/sec) or time= (seconds/shot) -- the same
                  stat written two different ways, not two mechanics (e.g. the
                  ARG L and M Pulse Turrets are the same weapon family and use
                  time=/rate= respectively) -- both are normalized here.
      heat_per_shot, heat_initial
                  Heat this bullet generates per shot (already x amount x
                  barrelamount) and any heat the weapon starts "pre-loaded"
                  with. Combined with the WEAPON's own <heat overheat= ...>
                  block in load_equipment() to get time-to-overheat/cooldown
                  -- not emitted directly, intermediate values only.
      range_m, projectile_speed_m_s, ammo_clip, ammo_clip_reload_s
                  Effective range (explicit <bullet range=> if present, else
                  speed x lifetime), raw projectile speed, and the raw ammo
                  clip size/reload for hover display.
    """
    bullets: dict[str, dict] = {}
    paths = _glob(
        idx,
        "assets/fx/weaponfx/macros/bullet_*.xml",
        "extensions/*/assets/fx/weaponfx/macros/bullet_*.xml",
        "assets/props/weaponsystems/*/macros/missile_*.xml",
        "extensions/*/assets/props/weaponsystems/*/macros/missile_*.xml",
    )
    for _rel, root in _load_merged_roots(idx, paths):
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue
        mid = macro_el.get("name", "").lower()
        if not mid:
            continue

        is_missile = macro_el.get("class") == "missile"
        phys_el = root.find(".//missile") if is_missile else root.find(".//bullet")
        dmg_el  = root.find(".//explosiondamage") if is_missile else root.find(".//damage")
        area_el = root.find(".//areadamage")
        reload_el = root.find(".//reload")
        ammo_el   = root.find(".//ammunition")
        heat_el   = root.find(".//heat")

        amount  = _int(phys_el, "amount")      or 1
        barrels = _int(phys_el, "barrelamount") or 1
        multiplier = amount * barrels

        entry: dict = {}

        # Flak-type weapons store damage in <areadamage> instead of <damage>
        dmg_hull = _float(dmg_el, "value")
        if dmg_hull is None:
            dmg_hull = _float(area_el, "value")
        if dmg_hull is not None:
            # damage_shield = hull damage + the shield= bonus (NOT a
            # replacement total) -- confirmed against the ARG Ion Blaster
            # Mk1/Mk2 tooltips this session (file hull=125 shield=500, real
            # Shield Damage shown is 625 = 125+500, not 500). This also
            # retroactively explains why beam weapons earlier looked like
            # they needed a x4 shield multiplier: their files happen to have
            # hull = 3x shield, so hull+shield and shield*4 coincide there by
            # pure chance -- the additive rule is the real, general one.
            speed = _float(phys_el, "speed")
            is_beam = bool(speed and speed >= 1e8)
            shield_bonus = _float(dmg_el, "shield")
            if shield_bonus is None:
                shield_bonus = _float(area_el, "shield")
            dmg_shield = dmg_hull + (shield_bonus or 0.0)

            entry["damage_hull"]   = _num(dmg_hull * multiplier)
            entry["damage_shield"] = _num(dmg_shield * multiplier)
            dmg_hull_shielded = _float(dmg_el, "hull")
            if dmg_hull_shielded:
                entry["damage_hull_while_shielded"] = _num(dmg_hull_shielded * multiplier)
            entry["is_beam"] = is_beam

        # Range + projectile speed.
        speed    = _float(phys_el, "speed")
        lifetime = _float(phys_el, "lifetime")
        rng      = _float(phys_el, "range")
        if rng:
            entry["range_m"] = _num(rng)
        elif speed and lifetime:
            entry["range_m"] = _num(speed * lifetime)
        if speed is not None:
            entry["projectile_speed_m_s"] = _num(speed)

        # Reload: normalize rate=/time= to an interval, then average over the
        # ammo clip (if any) for the true sustained rate of fire.
        rate     = _float(reload_el, "rate")
        interval = (1.0 / rate) if rate else _float(reload_el, "time")
        clip        = _float(ammo_el, "value")
        clip_reload = _float(ammo_el, "reload")
        if interval:
            if clip and clip_reload is not None:
                cycle = (clip - 1) * interval + clip_reload
                sustained = (clip / cycle) if cycle else None
            else:
                sustained = 1.0 / interval
            if sustained:
                entry["reload_rate"] = round(sustained, 3)
        if clip:
            entry["ammo_clip"] = int(clip)
        if clip_reload is not None:
            entry["ammo_clip_reload_s"] = clip_reload

        # Heat-per-shot (the weapon's own overheat/coolrate/cooldelay block
        # lives on the WEAPON macro, not here -- load_equipment() combines
        # the two once it knows which weapon/turret this bullet belongs to).
        heat_per_shot = _float(heat_el, "value")
        if heat_per_shot:
            entry["heat_per_shot"] = heat_per_shot * multiplier
            entry["heat_initial"]  = (_float(heat_el, "initial") or 0.0) * multiplier

        if entry:
            bullets[mid] = entry
    return bullets


# ──────────────────────────────────────────────────────────────────────────
#  Pass 2 — equipment macros
# ──────────────────────────────────────────────────────────────────────────

def load_equipment(idx: CatalogIndex, bullets: dict[str, dict], prices: dict[str, tuple[int, int, int]]):
    """Returns (records, aliases, name_pages).

    records   list of {macro, slot, name_ref, ...stats} (name still unresolved)
    aliases   alias macro id → canonical macro id
    name_pages t-file page ids referenced by the identification names, so the
              caller knows which pages to load before resolving.
    """
    records: list[dict] = []
    aliases: dict[str, str] = {}
    name_pages: set[str] = set()

    paths = _glob(
        idx,
        # weapons + turrets (categorised under weaponsystems/<cat>/macros)
        "assets/props/weaponsystems/*/macros/*.xml",
        "extensions/*/assets/props/weaponsystems/*/macros/*.xml",
        # shields
        "assets/props/surfaceelements/macros/shield_*.xml",
        "extensions/*/assets/props/surfaceelements/macros/shield_*.xml",
        # engines + thrusters (both live under engines/macros)
        "assets/props/engines/macros/*.xml",
        "extensions/*/assets/props/engines/macros/*.xml",
    )

    for rel, root in _load_merged_roots(idx, paths):
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue
        macro = macro_el.get("name", "").lower()
        cls   = macro_el.get("class", "")
        if not macro:
            continue

        ident = root.find(".//identification")
        # type="thrustertypes" is what separates a thruster from a main engine —
        # both carry class="engine".
        ident_type = ident.get("type", "") if ident is not None else ""

        # ── classify into a slot bucket ──────────────────────────────────────
        # missileturret/missilelauncher are real ship-hardpoint equipment, not
        # deployables -- confirmed via their component's hardpoint-mount tags
        # this session ("turret ... missile" / "...weapon...missile"), unlike
        # mines (deployable="1") or the spacesuit bomblauncher (a player EVA
        # item, mount tag "...spacesuit weapon"). They slot in exactly where
        # their name suggests: a launcher takes a weapon mount, a turret takes
        # a turret mount.
        if cls == "weapon":
            slot = "weapon"
        elif cls == "turret":
            slot = "turret"
        elif cls == "missilelauncher":
            slot = "weapon"
        elif cls == "missileturret":
            slot = "turret"
        elif cls == "shieldgenerator":
            slot = "shield"
        elif cls == "engine":
            slot = "thruster" if ident_type == "thrustertypes" else "engine"
        else:
            continue   # bullets, mines, effects, decorative — not equipment

        # ── an alias-only macro (no identification of its own) inherits from
        #    the macro it points at; record and resolve after concrete macros. ─
        if ident is None:
            ref = (macro_el.get("ref") or macro_el.get("alias") or "").lower()
            if ref:
                aliases[macro] = ref
            continue

        # hidden="1" marks equipment the game never shows the player (police
        # engines, drone/missile/escape-pod engines, mines). Not catalog items.
        if ident.get("hidden") == "1":
            continue

        rec: dict = {"macro": macro, "slot": slot}

        name_ref = ident.get("name", "")
        rec["name_ref"] = name_ref
        for page, _id in _REF_RE.findall(name_ref):
            name_pages.add(page)

        mk = _int(ident, "mk")
        if mk is not None:
            rec["mk"] = mk
        size = _size_from_macro(macro)
        if size:
            rec["size"] = size
        race = ident.get("makerrace")
        if race:
            rec["race"] = race
        price_range = prices.get(macro)
        if price_range:
            rec["price"] = price_range[1]       # average — unchanged existing behaviour
            rec["price_min"] = price_range[0]
            rec["price_max"] = price_range[2]   # live shop price can exceed even this

        # ── slot-specific stats ──────────────────────────────────────────────
        if slot in ("weapon", "turret"):
            rec["class"] = cls   # tells a missile-/regular- turret/weapon apart for the UI
            grp = _group_from_path(rel)
            if grp:
                rec["group"] = grp
            if (v := _int(root.find(".//rotationspeed"), "max"))      is not None: rec["rotation_speed"] = v
            if (v := _int(root.find(".//rotationacceleration"), "max")) is not None: rec["rotation_accel"] = v
            if (v := _int(root.find(".//hull"), "max"))               is not None: rec["hull_max"] = v
            if (v := _int(root.find(".//storage"), "capacity"))       is not None: rec["storage_capacity"] = v

            # damage/reload/heat-per-shot come from the referenced bullet (or
            # missile) macro
            bullet_el = root.find(".//bullet")
            bref = (bullet_el.get("class") or "").lower() if bullet_el is not None else ""
            rec.update(bullets.get(bref, {}))

            # Burst damage rate: weapon-class items use the FULL damage_shield
            # total (hull + shield bonus) x reload_rate as their headline --
            # confirmed against the Ion Blasters (756 shield x 0.5/s = 378,
            # matching the real tooltip) as well as every weapon-class item
            # with no shield bonus at all, where damage_shield == damage_hull
            # so this is equivalent to plain hull x rate (Behemoth Main
            # Battery, M/S Plasma Cannon, M Beam Emitter all matched this way).
            # Turret-class items use plain damage_hull x rate, EXCEPT
            # turret-class beams need an extra x4 on hull that the shield-bonus
            # formula doesn't explain (ARG M Beam Turret: 126 hull x4 x
            # 0.143/s = 72, matching the real tooltip; hull+shield=168 x rate
            # gives only 24, which does NOT match) -- still an open question,
            # not generalized further without more data points.
            rate = rec.get("reload_rate")
            if rate:
                if slot == "weapon":
                    base = rec.get("damage_shield")
                else:
                    base = rec.get("damage_hull")
                    if rec.get("is_beam") and base is not None:
                        base *= 4
                if base is not None:
                    rec["damage_rate_burst"] = _num(base * rate)

            # Heat: a second, independent throttle on top of the ammo clip,
            # only present on items with a weapon-level <heat> block (most
            # turrets don't have one in this dataset). Falls back to the
            # burst rate (never further throttled) when there's no heat data.
            heat_el = root.find(".//heat")
            heat_per_shot = rec.get("heat_per_shot")
            if heat_el is not None and heat_per_shot and rate:
                overheat = _float(heat_el, "overheat")
                coolrate = _float(heat_el, "coolrate")
                if overheat and coolrate:
                    initial           = rec.get("heat_initial") or 0.0
                    cooldelay         = _float(heat_el, "cooldelay") or 0.0
                    overheatcooldelay = _float(heat_el, "overheatcooldelay") or 0.0
                    avg_heat_rate = heat_per_shot * rate
                    if avg_heat_rate:
                        tto = (overheat - initial) / avg_heat_rate
                        cooldown = cooldelay + overheatcooldelay + overheat / coolrate
                        # 3dp, not 1dp -- same reasoning as _num(): the game
                        # truncates these to 1dp for its tooltip rather than
                        # rounding, so the UI needs the extra digits to
                        # reproduce that truncation itself.
                        rec["time_to_overheat"]  = round(tto, 3)
                        rec["cooldown_duration"] = round(cooldown, 3)
                        if rec.get("damage_rate_burst") is not None:
                            rec["damage_rate_sustained"] = _num(
                                rec["damage_rate_burst"] * tto / (tto + cooldown))
            if "damage_rate_sustained" not in rec and rec.get("damage_rate_burst") is not None:
                rec["damage_rate_sustained"] = rec["damage_rate_burst"]

        elif slot == "shield":
            recharge = root.find(".//recharge")
            if (v := _int(recharge, "max"))    is not None: rec["capacity"]       = v
            if (v := _int(recharge, "rate"))   is not None: rec["recharge_rate"]  = v
            # delay is genuinely fractional for several races (e.g. Argon M
            # 12.5s, Xenon L 17.25s) -- _int() was truncating it (12.5 -> 12),
            # silently wrong for ~25 macros; _round() (1dp) matches how the
            # file already handles every other non-integer stat.
            if (v := _round(recharge, "delay")) is not None: rec["recharge_delay"] = v
            # disruptionstability only appears on M/L/XL shields with their own
            # separate hull (not on "integrated" shields, which have no
            # standalone HP to disrupt) -- absence is meaningful, not missing data.
            if (v := _int(recharge, "disruptionstability")) is not None: rec["disruption_stability"] = v
            # The shield generator's own hit points -- same concept as
            # weapon/turret's hull_max above, just read from a different slot's
            # branch (shields use <hull integrated="1"/> instead when they
            # have no separate HP, so this is absent for those).
            if (v := _int(root.find(".//hull"), "max")) is not None: rec["hull_max"] = v

        elif slot == "engine":
            thrust = root.find(".//thrust")
            travel = root.find(".//travel")
            boost  = root.find(".//boost")
            if (v := _int(thrust, "forward"))    is not None: rec["thrust_forward"]  = v
            if (v := _int(thrust, "reverse"))    is not None: rec["thrust_reverse"]  = v
            if (v := _round(travel, "thrust"))   is not None: rec["travel_thrust"]   = v
            if (v := _round(travel, "charge"))   is not None: rec["travel_charge"]   = v
            if (v := _round(boost,  "thrust"))   is not None: rec["boost_thrust"]    = v
            if (v := _round(boost,  "duration")) is not None: rec["boost_duration"]  = v
            if (v := _round(boost,  "recharge")) is not None: rec["boost_recharge"]  = v
            # The engine's own hit points -- same concept as weapon/turret's and
            # shield's hull_max above, just read from this slot's branch. Absent
            # on "integrated" engines (S/M/XS sizes use <hull integrated="1"/>
            # instead -- no separate HP to damage; only L/XL have their own hull).
            if (v := _int(root.find(".//hull"), "max")) is not None: rec["hull_max"] = v

        elif slot == "thruster":
            thrust = root.find(".//thrust")
            if (v := _int(thrust, "strafe")) is not None: rec["strafe"] = v
            if (v := _int(thrust, "pitch"))  is not None: rec["pitch"]  = v
            if (v := _int(thrust, "yaw"))    is not None: rec["yaw"]    = v
            if (v := _int(thrust, "roll"))   is not None: rec["roll"]   = v

        # ── a macro can ALSO carry an alias= naming a second id that should
        #    resolve to this same definition (e.g. turret_arg_m_beam_01 →
        #    alias turret_arg_m_beam_02). Register alias → this macro. ─────────
        alias = (macro_el.get("alias") or "").lower()
        if alias and alias != macro:
            aliases[alias] = macro

        records.append(rec)

    return records, aliases, name_pages


# ──────────────────────────────────────────────────────────────────────────
#  Emit
# ──────────────────────────────────────────────────────────────────────────

def _fmt_value(v) -> str:
    return repr(v) if isinstance(v, str) else str(v)


def gen_equipment_py(records: list[dict], aliases: dict[str, str]) -> str:
    # One line per macro, fields in _FIELD_ORDER, sorted by macro for clean diffs.
    stat_lines = []
    for rec in sorted(records, key=lambda r: r["macro"]):
        inner = ", ".join(
            f"'{k}': {_fmt_value(rec[k])}"
            for k in _FIELD_ORDER if k in rec
        )
        stat_lines.append(f"    '{rec['macro']}': {{{inner}}},")

    # Only keep aliases whose canonical target actually made it into the catalog.
    known = {r["macro"] for r in records}
    alias_lines = [
        f"    '{a}': '{c}',"
        for a, c in sorted(aliases.items())
        if c in known and a not in known
    ]

    return (
        GENERATED_BANNER +
        "\n# Equipment macro id → static game stats.\n"
        "#   slot, class    — slot is weapon/turret/shield/engine/thruster (what hardpoint\n"
        "#                    it fits); class is the raw macro class (e.g. missileturret),\n"
        "#                    kept alongside slot so the UI can tell those apart\n"
        "#   name           — display name (identification ref, t-file resolved)\n"
        "#   mk, size, race — mark, size class (s/m/l/xl), maker faction\n"
        "#   price, price_min, price_max — average/min/max wares.xml buy price. The live\n"
        "#                    in-game shop price can run above even price_max (reputation/\n"
        "#                    station markup the static files don't capture) — treat as a\n"
        "#                    range, not an exact figure\n"
        "#   weapon/turret  — damage_hull, damage_shield, damage_hull_while_shielded (all\n"
        "#                    per-shot, already scaled by barrels/pellets-per-shot),\n"
        "#                    reload_rate (sustained shots/sec), range_m, projectile_speed_m_s,\n"
        "#                    ammo_clip, ammo_clip_reload_s, rotation_speed, rotation_accel,\n"
        "#                    hull_max (its own hitpoints), storage_capacity (missile bay,\n"
        "#                    missileturret/missilelauncher only), damage_rate_burst,\n"
        "#                    damage_rate_sustained, time_to_overheat, cooldown_duration\n"
        "#                    (the last 4 are derived, matched against real tooltips —\n"
        "#                    see gamefiles/generate_equipment.py's load_bullets/load_equipment).\n"
        "#                    time_to_overheat is the UNMODIFIED weapon-only baseline (heat\n"
        "#                    factor 1.0) — confirmed this session that it's also genuinely\n"
        "#                    ship-dependent via SHIP_STATS' weapon_heat_factor, which the UI\n"
        "#                    applies at display time once a hull is selected (see\n"
        "#                    ui/js/sectors.js's weaponTipHtml). damage_rate_sustained and\n"
        "#                    cooldown_duration are NOT affected by that factor.\n"
        "#   shield         — capacity, recharge_rate, recharge_delay, disruption_stability\n"
        "#                    (resistance to disruptor/ion shutdown — absent on \"integrated\"\n"
        "#                    shields, which have no separate hull to disrupt), hull_max\n"
        "#                    (the shield generator's own hit points — also absent when\n"
        "#                    integrated)\n"
        "#   engine         — thrust_forward, thrust_reverse (kN), travel_thrust, boost_thrust\n"
        "#                    (multipliers on forward thrust, not absolute kN), travel_charge\n"
        "#                    (s to spool up travel drive), boost_duration/boost_recharge (s\n"
        "#                    boost lasts / s before it's available again), hull_max (the\n"
        "#                    engine's own hit points — absent on \"integrated\" engines, i.e.\n"
        "#                    S/M/XS sizes with no separate hull to damage; only L/XL have one)\n"
        "#   thruster       — strafe, pitch, yaw, roll\n"
        "EQUIPMENT_STATS: dict[str, dict] = {\n" +
        "\n".join(stat_lines) + "\n}\n\n" +
        "\n# Alias macro id → canonical macro id. Some macros answer to a second\n"
        "# name (a <macro alias=...> attribute); a save can reference either, so\n"
        "# the loadout reader falls back through this map before giving up.\n"
        "EQUIPMENT_ALIASES: dict[str, str] = {\n" +
        "\n".join(alias_lines) + "\n}\n"
    )


def dedupe_variant_records(records: list[dict]) -> tuple[list[dict], dict[str, str]]:
    """Collapses X4's own duplicate ware listings into one catalog entry.

    X4 ships several equipment families (most visibly every M-size turret/
    weapon, e.g. turret_arg_m_beam_01_mk1 / turret_arg_m_beam_02_mk1) as TWO
    separate <ware> entries pointing at two near-identical macros -- same
    name/mk/size/race/price/combat stats, verified directly against
    wares.xml. Both are real, independently purchasable items in-game, but
    showing two indistinguishable rows in the ship-builder catalog is pure
    noise the player can't act on.

    Within each (slot, name, mk, size, race) group, the lowest macro id
    becomes canonical and absorbs any field a sibling defines that it's
    missing (so e.g. hull_max, which X4 only puts on the "_02" macro of a
    pair, isn't lost). A group is only merged when its members don't
    disagree on any field they both define -- a real stat conflict (logged,
    not silently dropped) means they're genuinely different items and stay
    separate, e.g. the one turret_arg_m_plasma_01/02 pair whose rotation
    speed actually differs.

    Returns (deduped_records, extra_aliases). extra_aliases maps each
    dropped macro id to its replacement, merged into EQUIPMENT_ALIASES
    alongside the XML alias= ones -- so a save referencing the dropped
    macro still resolves to a name and stats.
    """
    groups: dict[tuple, list[dict]] = {}
    for rec in records:
        key = (rec["slot"], rec["name"], rec.get("mk"), rec.get("size"), rec.get("race"))
        groups.setdefault(key, []).append(rec)

    kept: list[dict] = []
    extra_aliases: dict[str, str] = {}

    for group in groups.values():
        if len(group) == 1:
            kept.append(group[0])
            continue
        group = sorted(group, key=lambda r: r["macro"])
        anchor = group[0]
        for rec in group[1:]:
            conflicts = {k: (anchor[k], rec[k]) for k in set(anchor) & set(rec)
                         if k != "macro" and anchor[k] != rec[k]}
            if conflicts:
                kept.append(rec)   # genuinely different item -- keep separate
                print(f"[dedupe] {anchor['macro']} vs {rec['macro']} both named "
                      f"'{anchor['name']}' but disagree on {conflicts} -- kept separate")
            else:
                for k, v in rec.items():   # fill in anything anchor is missing
                    anchor.setdefault(k, v)
                extra_aliases[rec["macro"]] = anchor["macro"]
        kept.append(anchor)

    return kept, extra_aliases


# ──────────────────────────────────────────────────────────────────────────

def main() -> int:
    game_dir = find_x4_install()
    if game_dir is None:
        print("FAIL: no X4 installation found — nothing generated.")
        return 1
    print(f"Reading game files from: {game_dir}")

    idx = CatalogIndex.from_game_dir(game_dir)

    bullets = load_bullets(idx)
    print(f"Indexed {len(bullets)} bullet/missile macros (damage table)")

    prices = load_macro_price_ranges(idx)   # macro → (min, average, max) buy price
    records, aliases, name_pages = load_equipment(idx, bullets, prices)
    print(f"Found {len(records)} equipment macros, {len(aliases)} alias refs")

    # Resolve display names now that we know which t-file pages they reference.
    texts = load_texts(idx, name_pages)
    for rec in records:
        rec["name"] = clean_text(rec.pop("name_ref", ""), texts)

    # Drop anything with no display name. X4 only names player-facing gear, so a
    # blank name means an internal/utility macro (mines, etc.) that slipped past
    # the hidden="1" filter — not something a player can equip.
    before = len(records)
    records = [r for r in records if r["name"] and "{" not in r["name"]]
    if before - len(records):
        print(f"Dropped {before - len(records)} records with no display name")

    # Collapse X4's own duplicate ware listings (see dedupe_variant_records'
    # docstring) before emitting -- one catalog row per real item, not one
    # per <ware> entry.
    before = len(records)
    records, extra_aliases = dedupe_variant_records(records)
    aliases.update(extra_aliases)
    if before - len(records):
        print(f"Merged {before - len(records)} duplicate-listing records into "
              f"existing entries ({len(extra_aliases)} aliased)")

    by_slot: dict[str, int] = {}
    for rec in records:
        by_slot[rec["slot"]] = by_slot.get(rec["slot"], 0) + 1
    print("By slot: " + ", ".join(f"{k}={v}" for k, v in sorted(by_slot.items())))

    out_path = DATA_DIR / "equipment_stats.py"
    out_path.write_text(gen_equipment_py(records, aliases),
                        encoding="utf-8", newline="\n")
    print(f"Wrote {out_path.relative_to(REPO)}")
    print("\nDone — review with: git diff data/equipment_stats.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
