# ════════════════════════════════════════════════════════════════════════════
#       EQUIPMENT CATALOG GENERATOR — prop macros → data/equipment_stats.py
# ════════════════════════════════════════════════════════════════════════════
#
# Builds the equipment catalog the ship-loadout feature needs: every weapon,
# turret, shield, engine and thruster the game ships, with a readable name and
# the stats players care about. Read straight from the .cat/.dat archives (base
# + DLC), exactly like gamefiles/generate_data.py — generate-and-commit, so a
# game patch shows up as a reviewable `git diff data/equipment_stats.py`.
#
# Run after a game update or DLC install:
#
#   python gamefiles/generate_equipment.py
#
# OUTPUT  data/equipment_stats.py
#   EQUIPMENT_STATS    macro id → {slot, name, stats...}
#   EQUIPMENT_ALIASES  alias macro id → canonical macro id (some macros answer
#                      to a second name; a save can reference either)
#
# WHERE THE DATA LIVES (verified against the 9.00 files):
#   weapons   assets/props/weaponsystems/<cat>/macros/weapon_*.xml  class="weapon"
#   turrets   assets/props/weaponsystems/<cat>/macros/turret_*.xml  class="turret"
#   shields   assets/props/surfaceelements/macros/shield_*.xml      class="shieldgenerator"
#   engines   assets/props/engines/macros/engine_*.xml              class="engine"
#   thrusters assets/props/engines/macros/thruster_*.xml            class="engine" + type="thrustertypes"
#   bullets   assets/fx/weaponfx/macros/bullet_*.xml                class="bullet"
#
# WEAPON DAMAGE IS ONE HOP AWAY: a weapon/turret macro doesn't hold its own
# damage — it points at a <bullet class="bullet_..._macro"/>, and the damage
# lives in that bullet macro. So we index the bullets first, then resolve.
# ════════════════════════════════════════════════════════════════════════════

import pathlib
import sys

# Allow running as a script from anywhere: put the repo root on sys.path.
REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from lxml import etree as ET

from gamefiles.catalog import CatalogIndex, find_x4_install
from gamefiles.langtext import _REF_RE, clean_text, load_texts
from gamefiles.generate_data import load_macro_prices

DATA_DIR = REPO / "data"

# Ship size classes as they appear as a token in a macro name
# (weapon_arg_m_ion_01_mk1_macro → "m"). Ordered longest-first so "xl"/"xs"
# are tested before the single-letter sizes when scanning tokens.
_SIZES = ("xs", "xl", "s", "m", "l")

GENERATED_BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "#  AUTO-GENERATED by gamefiles/generate_equipment.py — DO NOT EDIT BY HAND.\n"
    "#  Source: assets/props/{weaponsystems,surfaceelements,engines} + weaponfx\n"
    "#  bullet macros, read directly from the X4 install's .cat archives.\n"
    "#  Re-run after a game update or DLC install:\n"
    "#      python gamefiles/generate_equipment.py\n"
    "#  then review the git diff for what the patch changed.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)

# Field order for the emitted per-entry dicts: identity first, then the
# slot-specific stats. Absent fields are simply skipped.
_FIELD_ORDER = [
    "slot", "name", "mk", "size", "race", "group", "price",
    # weapon / turret
    "damage_hull", "damage_shield", "reload_rate", "range_m",
    # shield
    "capacity", "recharge_rate", "recharge_delay",
    # engine
    "thrust_forward", "thrust_reverse", "travel_thrust", "boost_thrust",
    # thruster
    "strafe", "pitch", "yaw", "roll",
]


# ──────────────────────────────────────────────────────────────────────────
#  Small parse helpers
# ──────────────────────────────────────────────────────────────────────────

def _size_from_macro(macro: str) -> str | None:
    """The size token in a macro name, or None (e.g. lasertowers have none)."""
    toks = macro.split("_")
    for s in _SIZES:
        if s in toks:
            return s
    return None


def _group_from_path(vpath: str) -> str | None:
    """The weaponsystems category folder, e.g. .../weaponsystems/energy/... → 'energy'."""
    parts = vpath.split("/")
    try:
        return parts[parts.index("weaponsystems") + 1]
    except (ValueError, IndexError):
        return None


def _int(el, attr: str):
    """Attribute as int, or None if missing/blank/non-numeric."""
    if el is None:
        return None
    v = el.get(attr)
    try:
        return int(float(v)) if v not in (None, "") else None
    except (ValueError, TypeError):
        return None


def _round(el, attr: str, ndigits: int = 1):
    """Attribute as a rounded float, or None if missing."""
    if el is None:
        return None
    v = el.get(attr)
    try:
        return round(float(v), ndigits) if v not in (None, "") else None
    except (ValueError, TypeError):
        return None


def _glob(idx: CatalogIndex, *patterns: str) -> list[str]:
    """Union of catalog matches for several wildcards, deduped and sorted."""
    seen: set[str] = set()
    for p in patterns:
        seen.update(idx.find(p))
    return sorted(seen)


# ──────────────────────────────────────────────────────────────────────────
#  Pass 1 — bullets (the weapon/turret damage table)
# ──────────────────────────────────────────────────────────────────────────

def load_bullets(idx: CatalogIndex) -> dict[str, dict]:
    """macro id → {damage_hull, damage_shield, reload_rate, range_m}.

    A weapon/turret's <bullet class="X"/> names one of these; X4 keeps the
    actual damage on the bullet, not the weapon. Range is the bullet's reach:
    speed (m/s) × lifetime (s).
    """
    bullets: dict[str, dict] = {}
    for vp in _glob(idx,
                    "assets/fx/weaponfx/macros/bullet_*.xml",
                    "extensions/*/assets/fx/weaponfx/macros/bullet_*.xml"):
        root = ET.fromstring(idx.read(vp))
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue
        mid = macro_el.get("name", "").lower()
        if not mid:
            continue

        dmg_el    = root.find(".//damage")
        reload_el = root.find(".//reload")
        bullet_el = root.find(".//bullet")

        entry: dict = {}
        if (v := _int(dmg_el, "value"))  is not None: entry["damage_hull"]   = v
        if (v := _int(dmg_el, "shield")) is not None: entry["damage_shield"] = v
        if (v := _round(reload_el, "rate", 2)) is not None: entry["reload_rate"] = v

        # Range: beam bullets carry an explicit range= (their speed is set to
        # light-speed, so speed×lifetime is meaningless). Prefer that; fall back
        # to speed (m/s) × lifetime (s) for ordinary projectiles.
        rng = _int(bullet_el, "range")
        if rng is not None:
            entry["range_m"] = rng
        else:
            speed    = _round(bullet_el, "speed",    1)
            lifetime = _round(bullet_el, "lifetime", 3)
            if speed and lifetime:
                entry["range_m"] = round(speed * lifetime)

        if entry:
            bullets[mid] = entry
    return bullets


# ──────────────────────────────────────────────────────────────────────────
#  Pass 2 — equipment macros
# ──────────────────────────────────────────────────────────────────────────

def load_equipment(idx: CatalogIndex, bullets: dict[str, dict], prices: dict[str, int]):
    """Returns (records, aliases, name_pages).

    records   list of {macro, slot, name_ref, ...stats} (name still unresolved)
    aliases   alias macro id → canonical macro id
    name_pages t-file page ids referenced by the identification names, so the
              caller knows which pages to load before resolving.
    """
    records: list[dict] = []
    aliases: dict[str, str] = {}
    name_pages: set[str] = set()

    paths = _glob(
        idx,
        # weapons + turrets (categorised under weaponsystems/<cat>/macros)
        "assets/props/weaponsystems/*/macros/*.xml",
        "extensions/*/assets/props/weaponsystems/*/macros/*.xml",
        # shields
        "assets/props/surfaceelements/macros/shield_*.xml",
        "extensions/*/assets/props/surfaceelements/macros/shield_*.xml",
        # engines + thrusters (both live under engines/macros)
        "assets/props/engines/macros/*.xml",
        "extensions/*/assets/props/engines/macros/*.xml",
    )

    for vp in paths:
        root = ET.fromstring(idx.read(vp))
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue
        macro = macro_el.get("name", "").lower()
        cls   = macro_el.get("class", "")
        if not macro:
            continue

        ident = root.find(".//identification")
        # type="thrustertypes" is what separates a thruster from a main engine —
        # both carry class="engine".
        ident_type = ident.get("type", "") if ident is not None else ""

        # ── classify into a slot bucket ──────────────────────────────────────
        if cls == "weapon":
            slot = "weapon"
        elif cls == "turret":
            slot = "turret"
        elif cls == "shieldgenerator":
            slot = "shield"
        elif cls == "engine":
            slot = "thruster" if ident_type == "thrustertypes" else "engine"
        else:
            continue   # bullets, effects, decorative — not equipment

        # ── an alias-only macro (no identification of its own) inherits from
        #    the macro it points at; record and resolve after concrete macros. ─
        if ident is None:
            ref = (macro_el.get("ref") or macro_el.get("alias") or "").lower()
            if ref:
                aliases[macro] = ref
            continue

        # hidden="1" marks equipment the game never shows the player (police
        # engines, drone/missile/escape-pod engines, mines). Not catalog items.
        if ident.get("hidden") == "1":
            continue

        rec: dict = {"macro": macro, "slot": slot}

        name_ref = ident.get("name", "")
        rec["name_ref"] = name_ref
        for page, _id in _REF_RE.findall(name_ref):
            name_pages.add(page)

        mk = _int(ident, "mk")
        if mk is not None:
            rec["mk"] = mk
        size = _size_from_macro(macro)
        if size:
            rec["size"] = size
        race = ident.get("makerrace")
        if race:
            rec["race"] = race
        price = prices.get(macro)
        if price:
            rec["price"] = price

        # ── slot-specific stats ──────────────────────────────────────────────
        if slot in ("weapon", "turret"):
            grp = _group_from_path(vp)
            if grp:
                rec["group"] = grp
            # damage comes from the referenced bullet macro
            bullet_el = root.find(".//bullet")
            bref = (bullet_el.get("class") or "").lower() if bullet_el is not None else ""
            rec.update(bullets.get(bref, {}))

        elif slot == "shield":
            recharge = root.find(".//recharge")
            if (v := _int(recharge, "max"))   is not None: rec["capacity"]       = v
            if (v := _int(recharge, "rate"))  is not None: rec["recharge_rate"]  = v
            if (v := _int(recharge, "delay")) is not None: rec["recharge_delay"] = v

        elif slot == "engine":
            thrust = root.find(".//thrust")
            travel = root.find(".//travel")
            boost  = root.find(".//boost")
            if (v := _int(thrust, "forward"))  is not None: rec["thrust_forward"] = v
            if (v := _int(thrust, "reverse"))  is not None: rec["thrust_reverse"] = v
            if (v := _round(travel, "thrust")) is not None: rec["travel_thrust"]  = v
            if (v := _round(boost,  "thrust")) is not None: rec["boost_thrust"]   = v

        elif slot == "thruster":
            thrust = root.find(".//thrust")
            if (v := _int(thrust, "strafe")) is not None: rec["strafe"] = v
            if (v := _int(thrust, "pitch"))  is not None: rec["pitch"]  = v
            if (v := _int(thrust, "yaw"))    is not None: rec["yaw"]    = v
            if (v := _int(thrust, "roll"))   is not None: rec["roll"]   = v

        # ── a macro can ALSO carry an alias= naming a second id that should
        #    resolve to this same definition (e.g. turret_arg_m_beam_01 →
        #    alias turret_arg_m_beam_02). Register alias → this macro. ─────────
        alias = (macro_el.get("alias") or "").lower()
        if alias and alias != macro:
            aliases[alias] = macro

        records.append(rec)

    return records, aliases, name_pages


# ──────────────────────────────────────────────────────────────────────────
#  Emit
# ──────────────────────────────────────────────────────────────────────────

def _fmt_value(v) -> str:
    return repr(v) if isinstance(v, str) else str(v)


def gen_equipment_py(records: list[dict], aliases: dict[str, str]) -> str:
    # One line per macro, fields in _FIELD_ORDER, sorted by macro for clean diffs.
    stat_lines = []
    for rec in sorted(records, key=lambda r: r["macro"]):
        inner = ", ".join(
            f"'{k}': {_fmt_value(rec[k])}"
            for k in _FIELD_ORDER if k in rec
        )
        stat_lines.append(f"    '{rec['macro']}': {{{inner}}},")

    # Only keep aliases whose canonical target actually made it into the catalog.
    known = {r["macro"] for r in records}
    alias_lines = [
        f"    '{a}': '{c}',"
        for a, c in sorted(aliases.items())
        if c in known and a not in known
    ]

    return (
        GENERATED_BANNER +
        "\n# Equipment macro id → static game stats.\n"
        "#   slot           — weapon / turret / shield / engine / thruster\n"
        "#   name           — display name (identification ref, t-file resolved)\n"
        "#   mk, size, race — mark, size class (s/m/l/xl), maker faction\n"
        "#   weapon/turret  — damage_hull, damage_shield, reload_rate, range_m\n"
        "#   shield         — capacity, recharge_rate, recharge_delay\n"
        "#   engine         — thrust_forward, thrust_reverse, travel_thrust, boost_thrust\n"
        "#   thruster       — strafe, pitch, yaw, roll\n"
        "EQUIPMENT_STATS: dict[str, dict] = {\n" +
        "\n".join(stat_lines) + "\n}\n\n" +
        "\n# Alias macro id → canonical macro id. Some macros answer to a second\n"
        "# name (a <macro alias=...> attribute); a save can reference either, so\n"
        "# the loadout reader falls back through this map before giving up.\n"
        "EQUIPMENT_ALIASES: dict[str, str] = {\n" +
        "\n".join(alias_lines) + "\n}\n"
    )


# ──────────────────────────────────────────────────────────────────────────

def main() -> int:
    game_dir = find_x4_install()
    if game_dir is None:
        print("FAIL: no X4 installation found — nothing generated.")
        return 1
    print(f"Reading game files from: {game_dir}")

    idx = CatalogIndex.from_game_dir(game_dir)

    bullets = load_bullets(idx)
    print(f"Indexed {len(bullets)} bullet macros (damage table)")

    prices = load_macro_prices(idx)   # macro → average buy price
    records, aliases, name_pages = load_equipment(idx, bullets, prices)
    print(f"Found {len(records)} equipment macros, {len(aliases)} alias refs")

    # Resolve display names now that we know which t-file pages they reference.
    texts = load_texts(idx, name_pages)
    for rec in records:
        rec["name"] = clean_text(rec.pop("name_ref", ""), texts)

    # Drop anything with no display name. X4 only names player-facing gear, so a
    # blank name means an internal/utility macro (mines, etc.) that slipped past
    # the hidden="1" filter — not something a player can equip.
    before = len(records)
    records = [r for r in records if r["name"] and "{" not in r["name"]]
    if before - len(records):
        print(f"Dropped {before - len(records)} records with no display name")

    by_slot: dict[str, int] = {}
    for rec in records:
        by_slot[rec["slot"]] = by_slot.get(rec["slot"], 0) + 1
    print("By slot: " + ", ".join(f"{k}={v}" for k, v in sorted(by_slot.items())))

    out_path = DATA_DIR / "equipment_stats.py"
    out_path.write_text(gen_equipment_py(records, aliases),
                        encoding="utf-8", newline="\n")
    print(f"Wrote {out_path.relative_to(REPO)}")
    print("\nDone — review with: git diff data/equipment_stats.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
