# Core role: Generates the software ware catalog (docking/scanning/trading/
# targeting upgrades) by reading wares.xml directly -- unlike weapons/shields/
# engines, every software_* ware points at one shared dummy component macro
# (software_dummy_macro), so there's no per-item macro to pull stats from the
# way generate_equipment.py does. Name/description/price live on the <ware>
# entry itself.
#
# Output: data/software_stats.py with SOFTWARE_STATS (ware id -> name/description/price)
# Run after game update or DLC install: python gamefiles/generate_software.py
#
# DESIGN: generate-and-commit for reviewable diffs on game patches.

import pathlib
import re
import sys

# Allow running as a script from anywhere: put the repo root on sys.path.
REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from gamefiles.catalog import CatalogIndex, find_x4_install
from gamefiles.generate_data import load_merged_wares
from gamefiles.langtext import _REF_RE, clean_text, load_texts

DATA_DIR = REPO / "data"

GENERATED_BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "#  AUTO-GENERATED by gamefiles/generate_software.py — DO NOT EDIT BY HAND.\n"
    "#  Source: libraries/wares.xml (software_* ware entries), read directly from\n"
    "#  the X4 install's .cat archives.\n"
    "#  Re-run after a game update or DLC install:\n"
    "#      python gamefiles/generate_software.py\n"
    "#  then review the git diff for what the patch changed.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)

# The Hacking Tool and Oxygen Upgrade are personal spacesuit items unlocked by
# a specific story mission, not something the player ever buys -- flagged in
# wares.xml by this tag and given a degenerate price of 1/1/1 (every real
# software ware has a proper min/average/max band). Same "not a real catalog
# item" reasoning as generate_equipment.py's tutorial/story-variant filtering.
_STORY_GATED_TAG = "nocustomgamestart"

# Several Mk2/Mk3 tiers ship with a description ref that resolves to an empty
# string in the game's own t-file (confirmed this session, not a parsing gap)
# -- Egosoft only bothered writing tooltip copy for the Mk1 of that family.
# The Mk2/Mk3 is the same underlying software, one tier stronger, so the Mk1
# copy is still an accurate description; backfill_mk1_descriptions() below
# copies it onto any blank sibling in the same family so the UI never shows
# an empty tooltip. Purely algorithmic (id prefix minus the trailing mkN),
# not a hardcoded per-id table, so it keeps working if a future DLC adds
# another tier to an existing family.
_MK_SUFFIX_RE = re.compile(r"^(.*)mk(\d+)$")


def backfill_mk1_descriptions(records: list[dict]) -> int:
    """Fills blank descriptions from the Mk1 sibling in the same family.
    Returns the count of records backfilled."""
    by_family: dict[str, dict[int, dict]] = {}
    for r in records:
        m = _MK_SUFFIX_RE.match(r["id"])
        if not m:
            continue
        by_family.setdefault(m.group(1), {})[int(m.group(2))] = r

    filled = 0
    for tiers in by_family.values():
        base = tiers.get(1)
        if not base or not base["description"]:
            continue   # nothing to borrow (e.g. the mining scanner family)
        for mk, r in tiers.items():
            if mk != 1 and not r["description"]:
                r["description"] = base["description"]
                filled += 1
    return filled


# EDITORIAL — hand-written, NOT extracted from any game file (doesn't exist
# there to extract, unlike every other description in this catalog). Covers
# the wares still blank after backfill_mk1_descriptions(): Economy Analytics
# Mk1 (no other tier to borrow from) and both Mining Scanner tiers (Mk1
# itself has no game text, so there's nothing for Mk2 to inherit either).
# Paraphrased from player-documented mechanics on the Egosoft forum and the
# X4 Foundations Fandom wiki (neither of which quotes an official in-game
# string for these three -- it seems Egosoft genuinely never wrote one), kept
# to the same one-sentence length as the game's own descriptions. Re-review
# this block by hand after a game update; it won't auto-refresh like the rest
# of the file.
SOFTWARE_DESCRIPTION_OVERRIDES = {
    "software_economymk1": (
        "This analytics software adds a market overview to the map, tracking "
        "buy and sell offers for wares across scanned sectors from the moment "
        "it's installed."
    ),
    "software_scannerminingmk1": (
        "This scanning software analyses asteroid and gas fields to reveal "
        "their resource composition and estimate the yield."
    ),
    "software_scannerminingmk2": (
        "This scanning software increases scan resolution, giving a more "
        "accurate yield estimate for resource fields at greater range."
    ),
}


def load_software(idx: CatalogIndex) -> tuple[list[dict], set[str]]:
    """Returns (records, name_pages).

    records    list of {id, name_ref, description_ref, price, price_min, price_max}
    name_pages t-file page ids referenced by the names/descriptions, so the
               caller knows which pages to load before resolving.
    """
    root = load_merged_wares(idx)
    records: list[dict] = []
    name_pages: set[str] = set()

    for w in root.findall("ware"):
        wid = w.get("id", "")
        if not wid.startswith("software_"):
            continue
        tags = (w.get("tags") or "").split()
        if _STORY_GATED_TAG in tags:
            continue

        price = w.find("price")
        if price is None:
            continue
        try:
            price_min = int(price.get("min", 0))
            price_avg = int(price.get("average", 0))
            price_max = int(price.get("max", 0))
        except (ValueError, TypeError):
            continue

        name_ref = w.get("name", "")
        desc_ref = w.get("description", "")
        for page, _id in _REF_RE.findall(name_ref):
            name_pages.add(page)
        for page, _id in _REF_RE.findall(desc_ref):
            name_pages.add(page)

        records.append({
            "id": wid, "name_ref": name_ref, "description_ref": desc_ref,
            "price": price_avg, "price_min": price_min, "price_max": price_max,
        })
    return records, name_pages


def gen_software_py(records: list[dict]) -> str:
    # One line per ware, sorted by id for clean diffs.
    lines = []
    for r in sorted(records, key=lambda r: r["id"]):
        inner = (
            f"'name': {r['name']!r}, 'description': {r['description']!r}, "
            f"'price': {r['price']}, 'price_min': {r['price_min']}, 'price_max': {r['price_max']}"
        )
        lines.append(f"    '{r['id']}': {{{inner}}},")

    return (
        GENERATED_BANNER +
        "\n# Software ware id → static game stats.\n"
        "#   name, description — display name / tooltip text (t-file resolved).\n"
        "#                    A handful of Mk2/Mk3 tiers have no tooltip copy of their own\n"
        "#                    in the game's own text files — those get their Mk1 sibling's\n"
        "#                    description instead (see backfill_mk1_descriptions() in\n"
        "#                    gamefiles/generate_software.py). Economy Analytics Mk1 and\n"
        "#                    both Mining Scanner tiers have NO game text at all (not a\n"
        "#                    parsing gap — confirmed absent from the t-files); their\n"
        "#                    description here is hand-written editorial text, see\n"
        "#                    SOFTWARE_DESCRIPTION_OVERRIDES in generate_software.py.\n"
        "#   price, price_min, price_max — average/min/max wares.xml buy price. The live\n"
        "#                    in-game shop price can run above even price_max (reputation/\n"
        "#                    station markup the static files don't capture) — treat as a\n"
        "#                    range, not an exact figure.\n"
        "SOFTWARE_STATS: dict[str, dict] = {\n" +
        "\n".join(lines) + "\n}\n"
    )


def main() -> int:
    game_dir = find_x4_install()
    if game_dir is None:
        print("FAIL: no X4 installation found — nothing generated.")
        return 1
    print(f"Reading game files from: {game_dir}")

    idx = CatalogIndex.from_game_dir(game_dir)
    records, name_pages = load_software(idx)
    print(f"Found {len(records)} software wares")

    texts = load_texts(idx, name_pages)
    for rec in records:
        rec["name"] = clean_text(rec.pop("name_ref", ""), texts)
        rec["description"] = clean_text(rec.pop("description_ref", ""), texts)

    filled = backfill_mk1_descriptions(records)
    if filled:
        print(f"Backfilled {filled} blank description(s) from their Mk1 sibling")

    # Only ever fills what backfill left blank -- never overrides real game text.
    overridden = 0
    for rec in records:
        if not rec["description"] and rec["id"] in SOFTWARE_DESCRIPTION_OVERRIDES:
            rec["description"] = SOFTWARE_DESCRIPTION_OVERRIDES[rec["id"]]
            overridden += 1
    if overridden:
        print(f"Applied {overridden} hand-written editorial description(s)")

    # Drop anything with no display name (shouldn't happen for software_* wares,
    # but matches generate_equipment.py's safety net for the same situation).
    before = len(records)
    records = [r for r in records if r["name"] and "{" not in r["name"]]
    if before - len(records):
        print(f"Dropped {before - len(records)} records with no display name")

    out_path = DATA_DIR / "software_stats.py"
    out_path.write_text(gen_software_py(records), encoding="utf-8", newline="\n")
    print(f"Wrote {out_path.relative_to(REPO)}")
    print("\nDone — review with: git diff data/software_stats.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
