# Core role: Regenerates game-derived lookup tables (wares, prices, production) by parsing X4's .cat/.dat archives; designed to show diffs after game updates.
#
# Output: data/wares.py, data/ware_prices.py, data/production_stats.py
# Run after game update or DLC install: python gamefiles/generate_data.py
#
# DESIGN: generate-and-commit, not read-at-runtime. Data files stay importable without game install;
# value changes show as reviewable diffs instead of silent runtime drift.
#
# EDITORIAL: WARE_GROUP_PRIORITY is hand-maintained (doesn't exist in game files). Edit it below.

import pathlib
import re
import sys

# Allow running as a script from anywhere: put the repo root on sys.path.
REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from lxml import etree as ET

from gamefiles.catalog import CatalogIndex, find_x4_install
from gamefiles.xmlpatch import apply_diff
# The {page,id} t-file resolver now lives in one shared module so the equipment
# generator can reuse it. Imported names keep their original spelling so every
# call site below (clean_text, load_texts, _REF_RE) stays unchanged.
from gamefiles.langtext import _COMMENT_RE, _REF_RE, clean_text, load_texts

DATA_DIR = REPO / "data"

# Wares the scanner needs that are NOT tagged "economy" in wares.xml:
# rawscrap/nividiumgems show up in station cargo (scrap processing, gem
# manufacture) so the volume/transport tables must cover them.
EXTRA_WARE_IDS = {"rawscrap", "nividiumgems"}

# Header prepended to every generated file. The per-file blocks below add
# their own table-specific documentation under it.
GENERATED_BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "#  AUTO-GENERATED by gamefiles/generate_data.py — DO NOT EDIT BY HAND.\n"
    "#  Source: libraries/wares.xml (+ DLC diffs) read directly from the X4\n"
    "#  install's .cat archives. Re-run after a game update or DLC install:\n"
    "#      python gamefiles/generate_data.py\n"
    "#  then review the git diff for what the patch changed.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)


# Imports from gamefiles.langtext are shared with generate_equipment.py


# ──────────────────────────────────────────────────────────────────────────
#  Game-data assembly
# ──────────────────────────────────────────────────────────────────────────

def load_merged_wares(idx: CatalogIndex):
    """Base wares.xml with every DLC's diff applied, in catalog order."""
    root = ET.fromstring(idx.read("libraries/wares.xml"))
    for vp in idx.find("extensions/*/libraries/wares.xml"):
        apply_diff(root, ET.fromstring(idx.read(vp)), source=vp)
    return root


def load_macro_prices(idx: CatalogIndex) -> dict[str, int]:
    """component macro id (lowercase) → average buy price, from wares.xml.

    Ships are sold as wares; each priced ware links back to its component via
    <component ref="..._macro"/>, so the ref IS the macro id. Used to price
    hulls in ship_stats. Equipment uses load_macro_price_ranges() instead —
    see its docstring for why a single number isn't enough there.
    """
    root = load_merged_wares(idx)
    prices: dict[str, int] = {}
    for w in root.findall("ware"):
        comp  = w.find("component")
        price = w.find("price")
        if comp is None or price is None:
            continue
        ref = (comp.get("ref") or "").lower()
        if ref:
            try:
                prices[ref] = int(price.get("average", 0))
            except (ValueError, TypeError):
                pass
    return prices


def load_macro_price_ranges(idx: CatalogIndex) -> dict[str, tuple[int, int, int]]:
    """component macro id (lowercase) → (min, average, max) buy price.

    Equipment-specific sibling of load_macro_prices(). The live in-game shop
    price observed during testing (e.g. 64718cr for a turret whose static
    range here was 43277-52894) runs ABOVE even the static max — there's a
    reputation/station markup the .cat files can't capture. A single
    "average" number would silently look more precise than it is; exposing
    the range is honest about that uncertainty for equipment tooltips.
    """
    root = load_merged_wares(idx)
    prices: dict[str, tuple[int, int, int]] = {}
    for w in root.findall("ware"):
        comp  = w.find("component")
        price = w.find("price")
        if comp is None or price is None:
            continue
        ref = (comp.get("ref") or "").lower()
        if not ref:
            continue
        try:
            min_raw = price.get("min", "0")
            min_v   = int(min_raw)
            avg_v   = int(price.get("average", 0))
            max_v   = int(price.get("max", 0))
            # Split Vendetta's shipped wares.xml has min="1536515365" for
            # shield_spl_m_standard_02_mk1 -- "15365" pasted twice in a row
            # (confirmed against the live, MD5-verified .cat/.dat archive, so
            # it's Egosoft's data bug, not a parsing one). A real price range
            # can never have min > max, so only when that invariant breaks do
            # we try undoing a same-length self-duplication in the min text.
            if min_v > max_v:
                half = len(min_raw) // 2
                if half and len(min_raw) % 2 == 0 and min_raw[:half] == min_raw[half:]:
                    min_v = int(min_raw[:half])
            prices[ref] = (min_v, avg_v, max_v)
        except (ValueError, TypeError):
            pass
    return prices


# Owner factions that never run a wharf/shipyard the player can buy from —
# Xenon and Kha'ak are permanently hostile; "ownerless" means no faction flies
# it at all (story/event-reward hulls). A hull owned ONLY by these is never
# sold, though Xenon/Kha'ak ones may still be captured by boarding (a runtime
# mechanic with no static-file flag, so we keep them in the catalog instead
# of dropping them).
_NON_PLAYER_FACTIONS = {"xenon", "khaak", "ownerless"}
_NO_BLUEPRINT_TAGS    = {"noblueprint", "noplayerblueprint", "noplayerbuild"}

# Owner sets meaning "no NPC faction ever flies this" — distinct from
# "ownerless" (a real derelict/event ship with no faction, but still a
# flyable hull someone might hand the player). "player" alone is a wares.xml
# scripting placeholder for internal mission/logistics props (e.g. the
# "transdrone" cargo bots) — nobody, including the player, ever pilots one in
# the normal sense, so unlike ownerless hulls these are dropped entirely
# rather than kept as capture-only. Cross-checked against qsna.eu's X4 ship
# builder, which omits exactly these macros.
_PLACEHOLDER_ONLY_OWNERS = {"player"}


def load_macro_availability(idx: CatalogIndex) -> dict[str, dict]:
    """component macro id (lowercase) → {"owners": set[str], "purchasable": bool}.

    Read from each ship's wares.xml <ware><owner faction="..."/></ware> entry.
    A macro is ABSENT from this dict — and load_ship_data() drops it entirely
    — if any of:
      * it has no <ware> entry at all (NPC skin variant, escape pod,
        colony-ship set-piece part, etc. — never offered to anyone),
      * its <ware> entry has zero <owner> factions (deployable drones,
        lasertowers, a handful of "_story" mission props — nobody in the
        game world is ever assigned to fly, sell, or guard them), or
      * its only owner is the "player" scripting placeholder (see
        _PLACEHOLDER_ONLY_OWNERS) — an internal prop, not a real ship.
    A macro present with purchasable=False has a real owner (so it's a flown,
    encounterable ship) but no faction the player can ever buy from — still
    a real ship the player could end up owning via capture or a story
    reward, so it stays in the catalog, just marked accordingly.
    """
    root = load_merged_wares(idx)
    out: dict[str, dict] = {}
    for w in root.findall("ware"):
        comp = w.find("component")
        if comp is None:
            continue
        ref = (comp.get("ref") or "").lower()
        if not ref:
            continue
        owners = {o.get("faction") for o in w.findall("owner") if o.get("faction")}
        if not owners or owners <= _PLACEHOLDER_ONLY_OWNERS:
            continue
        tags = set((w.get("tags") or "").split())
        purchasable = bool(owners - _NON_PLAYER_FACTIONS) and not (tags & _NO_BLUEPRINT_TAGS)
        out[ref] = {"owners": owners, "purchasable": purchasable}
    return out


def load_group_textids(idx: CatalogIndex) -> dict[str, int]:
    """
    waregroups.xml: group id → page 20215 base textId.
    e.g. "hightech" → 501; the factory display name sits at textId+3.
    """
    root = ET.fromstring(idx.read("libraries/waregroups.xml"))
    ids = {}
    for grp in root.findall("group"):
        m = _REF_RE.match(grp.get("name", ""))
        if m and m.group(1) == "20215":
            ids[grp.get("id")] = int(m.group(2))
    return ids


def select_wares(root) -> list:
    """
    The wares our tables cover: everything tagged "economy" (tradeable goods,
    including mineables and DLC wares) plus the explicit extras. Equipment,
    software, inventory items etc. are excluded — the scanner never sees them
    as cargo or production output.
    """
    out = []
    for w in root.findall("ware"):
        tags = (w.get("tags") or "").split()
        if "economy" in tags or w.get("id") in EXTRA_WARE_IDS:
            out.append(w)
    # Sorted by id so regeneration is deterministic → clean git diffs.
    out.sort(key=lambda w: w.get("id"))
    return out


# ──────────────────────────────────────────────────────────────────────────
#  File emitters
# ──────────────────────────────────────────────────────────────────────────

# WARE_GROUP_PRIORITY is editorial (see header) — emitted verbatim.
PRIORITY_BLOCK = '''
# ─────────────────────────────────────────────────────────────────────────────
#  WARE GROUP PRIORITY  (page 20215 base textId → priority rank)
#  EDITORIAL — maintained in gamefiles/generate_data.py, not derived from game
#  files. When a station produces wares from multiple groups, the group with
#  the lowest priority number wins and names the station, mirroring X4's own
#  auto-naming (hullparts + energycells → "High Tech Factory").
#  Groups absent from this dict rank last (language.py falls back to 999).
# ─────────────────────────────────────────────────────────────────────────────

WARE_GROUP_PRIORITY: dict[int, int] = {
    501:  1,   # High Tech Goods      → "High Tech Factory"
    1001: 2,   # Ship Technology      → "Ship Technology Factory"
    901:  3,   # Refined Goods        → "Refined Goods Complex"
    701:  4,   # Minerals             → "Mineral Refinery"
    401:  5,   # Gases                → "Gas Refinery"
    801:  6,   # Pharmaceutical Goods → "Pharmaceutical Goods Factory"
    101:  7,   # Agricultural Goods   → "Agricultural Goods Factory"
    301:  8,   # Food                 → "Farm"
    601:  9,   # Ice                  → "Ice Refinery"
    201: 10,   # Energy               → "Energy Complex"
    1201: 11,  # Water                → "Water Refinery"
}
'''


def _fmt_dict(name: str, type_hint: str, items: list[tuple[str, str]],
              comment: str = "") -> str:
    """Renders a dict literal with aligned values, one entry per line."""
    width = max((len(k) for k, _ in items), default=0) + 2  # +2 for quotes
    lines = [f"{name}: {type_hint} = {{"]
    for key, value in items:
        lines.append(f"    {('\"' + key + '\":').ljust(width + 1)} {value},")
    lines.append("}")
    return (comment + "\n" if comment else "") + "\n".join(lines) + "\n"


def gen_wares_py(wares, group_textids, texts) -> str:
    names, volumes, transports, groups = [], [], [], []
    for w in wares:
        wid = w.get("id")
        display = clean_text(w.get("name", ""), texts)
        names.append((wid, repr(display)))
        volumes.append((wid, f'{float(w.get("volume", "1")):.1f}'))
        transports.append((wid, repr(w.get("transport", "container"))))
        # WARE_GROUPS only covers wares buildable in a player station —
        # signalled in wares.xml by the presence of a factoryname reference.
        gid = group_textids.get(w.get("group", ""))
        if gid is not None and w.get("factoryname"):
            groups.append((wid, str(gid)))

    parts = [
        GENERATED_BANNER,
        _fmt_dict(
            "WARE_NAMES", "dict[str, str]", names,
            "\n# Ware id → display name (wares.xml name ref resolved via "
            "t/0001-l044.xml page 20201).\n"
            "# Used to label production modules and cargo; unknown ids fall "
            "back to title-case."),
        _fmt_dict(
            "WARE_VOLUME", "dict[str, float]", volumes,
            "\n# Ware id → volume in m³ per unit (wares.xml volume attribute)."
            "\n# Converts cargo amounts into m³ for storage fill percentages."),
        _fmt_dict(
            "WARE_TRANSPORT", "dict[str, str]", transports,
            "\n# Ware id → storage class: container / solid / liquid "
            "(wares.xml transport\n# attribute). Attributes trade "
            "reservations to the right storage type."),
        _fmt_dict(
            "WARE_GROUPS", "dict[str, int]", groups,
            "\n# Ware id → page 20215 base textId of its ware group "
            "(waregroups.xml).\n# Only wares with a factoryname in wares.xml "
            "(player-buildable) are listed.\n# The group factory display name "
            "lives at textId+3 — e.g. hightech 501 →\n# 504 \"High Tech "
            "Factory\" — the +3 offset X4 uses on this page."),
        PRIORITY_BLOCK,
    ]
    return "\n".join(parts)


def gen_ware_prices_py(wares) -> str:
    items = []
    for w in wares:
        p = w.find("price")
        if p is None:
            continue
        items.append((w.get("id"),
                      f'{{"min": {int(p.get("min", 0))}, '
                      f'"average": {int(p.get("average", 0))}, '
                      f'"max": {int(p.get("max", 0))}}}'))
    return GENERATED_BANNER + _fmt_dict(
        "WARE_PRICES", "dict[str, dict]", items,
        "\n# Ware id → market price band in credits (wares.xml <price>).\n"
        "# The station budget calculation values trade wares at the MAX "
        "price.")


def gen_production_stats_py(wares) -> str:
    blocks = []
    for w in wares:
        prods = w.findall("production")
        if not prods:
            continue  # mineables and pure trade goods have no recipe
        methods = []
        for prod in prods:
            inputs = {i.get("ware"): int(i.get("amount", 0))
                      for i in prod.findall("primary/ware")}
            input_str = ", ".join(f"'{k}': {v}" for k, v in sorted(inputs.items()))
            methods.append(f"            '{prod.get('method', 'default')}': "
                           f"{{{input_str}}},")
        # time/amount come from the FIRST (default) production entry; faction
        # methods only differ in inputs, which is all the methods dict holds.
        first = prods[0]
        blocks.append(
            f"    '{w.get('id')}': {{\n"
            f"        \"group\":   '{w.get('group', '')}',\n"
            f"        \"time\":    {int(float(first.get('time', 0)))},\n"
            f"        \"amount\":  {int(first.get('amount', 0))},\n"
            f"        \"methods\": {{\n" + "\n".join(methods) + "\n"
            f"        }},\n"
            f"    }},")
    return (GENERATED_BANNER +
            "\n# Ware id → production recipe (wares.xml <production> nodes)."
            "\n#   group   — ware category (wares.xml group attribute)"
            "\n#   time    — production cycle duration in seconds"
            "\n#   amount  — units produced per cycle"
            "\n#   methods — method id → {input ware: amount per cycle}."
            "\n#             'default' is the standard recipe; faction methods"
            "\n#             (teladi, split, ...) appear where inputs differ."
            "\n#             Empty dict = no inputs needed (energy cells).\n"
            "PRODUCTION_STATS: dict[str, dict] = {\n"
            + "\n".join(blocks) + "\n}\n")


# ──────────────────────────────────────────────────────────────────────────
#  station_names.py — WARE_FACTORY_NAMES
# ──────────────────────────────────────────────────────────────────────────

def gen_station_names_py(wares, texts) -> str:
    """
    Builds WARE_FACTORY_NAMES: ware_id → FactoryEntry(name, text_id).

    factoryname="{20201,N}" on each <ware> gives us the text_id (N). The
    factory display name sits at text_id itself on page 20201 (e.g. id 1204
    → "Hull Part Factory"). The ware display name sits at text_id-3 (1201 →
    "Hull Parts") — emitted as a comment so the file is self-documenting.
    Only wares with a factoryname reference are player-buildable and listed.
    """
    entries = []
    REF = re.compile(r'^\{(\d+),(\d+)\}$')
    for w in wares:
        fn = w.get("factoryname", "")
        m = REF.match(fn)
        if not m:
            continue
        text_id = int(m.group(2))
        factory_name = clean_text(texts.get(f"20201:{text_id}", ""), texts)
        ware_name    = clean_text(texts.get(f"20201:{text_id - 3}", ""), texts)
        if not factory_name:
            continue
        entries.append((w.get("id"), text_id, factory_name, ware_name,
                        w.get("group", "")))

    lines = [
        GENERATED_BANNER,
        "# Ware id → FactoryEntry(name, text_id) for player-buildable stations.",
        "# name     — factory display name from page 20201 of the language file",
        "# text_id  — page 20201 id; callers that need the ware display name",
        "#            find it at text_id-3 on the same page.",
        "#",
        "# Used by resolve_station_type() in scanner/language.py:",
        "#   • 1 unique ware produced → WARE_FACTORY_NAMES[ware_id].name",
        "#   • 2+ unique wares        → group factory name (data/wares.py WARE_GROUPS)",
        "",
        "from typing import NamedTuple",
        "",
        "",
        "class FactoryEntry(NamedTuple):",
        '    """Factory name and its page 20201 text ID from the X4 language file."""',
        "    name:    str  # display string, e.g. \"Hull Part Factory\"",
        "    text_id: int  # page 20201 id — ware display name is at text_id-3",
        "",
        "",
        "WARE_FACTORY_NAMES: dict[str, FactoryEntry] = {",
    ]
    # Group entries by ware group for readability, same as the hand-written file.
    from collections import defaultdict
    by_group = defaultdict(list)
    for eid, text_id, fname, wname, group in entries:
        by_group[group].append((eid, text_id, fname, wname))
    for group in sorted(by_group):
        lines.append(f"    # {group}")
        for eid, text_id, fname, wname in sorted(by_group[group]):
            lines.append(f'    "{eid}": FactoryEntry({repr(fname)}, {text_id}),'
                         f'  # display: {repr(wname)} (id {text_id - 3})')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────
#  ships.py + ship_stats.py
# ──────────────────────────────────────────────────────────────────────────

# Slot tags in ship component XMLs: equipment type + mount size. Thruster is NOT
# a connection (it's a thruster= attribute on the ship), so it isn't counted here.
_HP_TYPES = {"weapon", "turret", "shield", "engine"}
_HP_SIZES = {"small": "s", "medium": "m", "large": "l", "extralarge": "xl"}


def load_hardpoints(idx: CatalogIndex) -> dict[str, dict]:
    """component name (lowercase) → {equip_type: {size: count}}.

    Read from the ship COMPONENT XMLs (not the macros): each equipment mount is a
    <connection> whose tags carry an equipment type (weapon/turret/shield/engine)
    and a size (small/medium/large/extralarge). Hull variants (_a/_b/_macro) share
    one component, so the macro→component ref in load_ship_data maps them here.
    """
    out: dict[str, dict] = {}
    paths = (idx.find("assets/units/*/ship_*.xml") +
             idx.find("extensions/*/assets/units/*/ship_*.xml"))
    for vp in paths:
        comp_el = ET.fromstring(idx.read(vp)).find(".//component")
        if comp_el is None:
            continue
        name = comp_el.get("name", "").lower()
        if not name:
            continue
        hp: dict[str, dict] = {}
        for conn in comp_el.iter("connection"):
            toks  = set((conn.get("tags") or "").split())
            types = toks & _HP_TYPES
            sizes = toks & _HP_SIZES.keys()
            if not types or not sizes:
                continue
            for t in types:
                for s in sizes:
                    bucket = hp.setdefault(t, {})
                    bucket[_HP_SIZES[s]] = bucket.get(_HP_SIZES[s], 0) + 1
        if hp:
            out[name] = hp
    return out


def _fmt_hardpoints(hp: dict) -> str:
    """Render a {type: {size: count}} dict as a deterministic one-line literal."""
    if not hp:
        return "{}"
    parts = []
    for t in sorted(hp):
        inner = ", ".join(f"'{s}': {hp[t][s]}" for s in sorted(hp[t]))
        parts.append(f"'{t}': {{{inner}}}")
    return "{" + ", ".join(parts) + "}"


def load_ship_data(idx: CatalogIndex, texts: dict, prices: dict[str, int],
                   hardpoints: dict[str, dict],
                   availability: dict[str, dict]) -> list[dict]:
    """
    Reads every ship_*.xml macro from the catalogs (base + DLC) and returns a
    list of per-ship dicts (see the keys built below). price is the hull's
    average buy price (0 if the hull isn't sold); hardpoints is the slot
    layout of the macro's referenced component.

    A dict (not the old positional tuple) because this now carries ~17 fields
    — adding one more as a positional slot would mean re-counting every
    unpack site in the file to find where it landed; a dict key is self-
    documenting at every call site instead.

    weapon_heat_factor is the hull's <modifiers><weapon heat=X/></modifiers>
    multiplier (1.0 when the macro has no such element, the common case) --
    confirmed this session against real Time to Overheat tooltips: e.g. the
    Quasar Vanguard and Cerberus Vanguard both carry heat="1.3" and both show
    a Time to Overheat 1.3x shorter than the weapon's own unmodified figure,
    while ships with no <modifiers> block (Eclipse Vanguard, Minotaur
    Vanguard) match the unmodified weapon stat exactly. Time to Overheat is
    therefore genuinely ship-dependent, not a pure weapon stat -- Sustained
    Weapon Damage and Cooldown Duration are unaffected by it.

    EVERY macro is kept here, including drones/NPC skin variants/set-piece
    parts — SHIP_NAMES (gen_ships_py) is used to label any ship the live
    scanner encounters (police drones, defense lasertowers, NPC traders...),
    not just the design builder's hull catalog, so narrowing the list here
    would silently degrade names for ships that genuinely appear in scans.

    flown is True if some faction actually owns/flies the hull in wares.xml
    (see load_macro_availability) — False means it's a pure asset that's
    never a real or encounterable ship (NPC skin variant, escape pod,
    deployable drone, colony-ship set-piece part). purchasable is True only
    if flown is also True AND the player can buy it new at a shipyard (False
    for Xenon/Kha'ak/story-reward hulls, which are still flown/capturable).
    Both flags exist so jsonexport's hull catalog can drop non-flown hulls
    while still badging capture-only ones instead of hiding them.

    ship_type/purpose/makerrace/crew_capacity/missile_storage/unit_storage/
    description/variation all come straight off <properties> in this same
    macro file — no extra file read. cargo_max/cargo_tags are deliberately
    NOT resolved here: the cargo bay is a separate macro referenced through
    this macro's own <connections> block (a different file per hull, living
    in several different assets/ subdirectories — not the fixed component-XML
    glob hardpoints come from). The ref is captured into _storage_macro_ref
    and resolved afterwards by load_cargo_for_ships(), which the caller must
    run before writing these dicts out — see main().

    DLC ship macros are full documents (not diffs), so they're simply parsed
    alongside the base-game ones — no patch application needed.
    """
    ships = []
    # Base game and DLC paths share the same inner structure; collect all at once.
    all_paths = (idx.find("assets/units/*/macros/ship_*.xml") +
                 idx.find("extensions/*/assets/units/*/macros/ship_*.xml"))

    for vp in all_paths:
        root = ET.fromstring(idx.read(vp))
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue

        macro_id = macro_el.get("name", "")
        if not macro_id:
            continue

        ship_class = macro_el.get("class", "")
        ident      = root.find(".//identification")
        hull_el    = root.find(".//hull")
        ship_el    = root.find(".//ship")
        purpose_el = root.find(".//purpose")
        people_el  = root.find(".//people")
        storage_el = root.find(".//storage")

        name_ref = ident.get("name", "") if ident is not None else ""
        display  = clean_text(name_ref, texts) if name_ref else macro_id

        desc_ref = ident.get("description", "") if ident is not None else ""
        description = clean_text(desc_ref, texts) if desc_ref else ""

        variation_ref = ident.get("variation", "") if ident is not None else ""
        variation = clean_text(variation_ref, texts) if variation_ref else ""

        makerrace = (ident.get("makerrace", "") if ident is not None else "").lower()

        max_hull = int(hull_el.get("max", 0)) if hull_el is not None else 0
        price    = prices.get(macro_id.lower(), 0)
        avail    = availability.get(macro_id.lower())
        flown       = avail is not None
        purchasable = avail["purchasable"] if avail else False

        # The macro points at its hull component; that component owns the slots.
        comp_ref = macro_el.find("component")
        ref      = (comp_ref.get("ref") or "").lower() if comp_ref is not None else ""
        hp       = hardpoints.get(ref, {})

        weapon_heat_el = root.find(".//modifiers/weapon")
        try:
            weapon_heat_factor = float(weapon_heat_el.get("heat", 1.0)) if weapon_heat_el is not None else 1.0
        except (ValueError, TypeError):
            weapon_heat_factor = 1.0

        def _int_or_none(el, attr):
            if el is None or not el.get(attr):
                return None
            try:
                return int(el.get(attr))
            except (TypeError, ValueError):
                return None

        crew_capacity   = _int_or_none(people_el, "capacity")
        missile_storage = _int_or_none(storage_el, "missile")
        unit_storage    = _int_or_none(storage_el, "unit")

        # Cargo bay macro ref, e.g. <connections><connection><macro
        # ref="storage_arg_l_destroyer_01_a_macro"/></connection></connections>
        # — sibling to <properties> on the macro, NOT inside it. The
        # connection's own name varies (con_storage01/con_storage_01/...), so
        # match by the referenced macro's "storage_" prefix instead.
        storage_macro_ref = ""
        conns_el = macro_el.find("connections")
        if conns_el is not None:
            for conn in conns_el.findall("connection"):
                sm = conn.find("macro")
                smref = (sm.get("ref") or "").lower() if sm is not None else ""
                if smref.startswith("storage_"):
                    storage_macro_ref = smref
                    break

        ships.append({
            "macro_id":            macro_id,
            "display":             display,
            "description":         description,
            "variation":           variation,
            "class":               ship_class,
            "max_hull":            max_hull,
            "price":               price,
            "hardpoints":          hp,
            "purchasable":         purchasable,
            "flown":               flown,
            "weapon_heat_factor":  weapon_heat_factor,
            "ship_type":           ship_el.get("type", "") if ship_el is not None else "",
            "purpose":             purpose_el.get("primary", "") if purpose_el is not None else "",
            "makerrace":           makerrace,
            "crew_capacity":       crew_capacity,
            "missile_storage":     missile_storage,
            "unit_storage":        unit_storage,
            "cargo_max":           None,
            "cargo_tags":          "",
            "_storage_macro_ref":  storage_macro_ref,
        })

    ships.sort(key=lambda s: s["macro_id"])
    return ships


def load_cargo_for_ships(idx: CatalogIndex, ships: list[dict]) -> None:
    """
    Resolves each ship's cargo-bay macro (captured as _storage_macro_ref by
    load_ship_data) into a max m3 + ware-type tag, mutating every ship dict
    in place and removing the internal _storage_macro_ref key.

    A second pass because the cargo-bay macro is a standalone file scattered
    across several assets/ subdirectories per hull (ship-specific ones live
    next to the hull's own macro, generic shared ones live under
    assets/props/storagemodules/) — there's no single fixed glob like
    hardpoints' component files, so each ref is resolved by filename via
    idx.find("*/<ref>.xml") instead of a directory pattern.
    """
    # ref -> (cargo_max, cargo_tags); several hulls share the same generic
    # storage macro (e.g. storage_gen_s_eight), so cache to avoid re-reading it.
    cache: dict[str, tuple[int | None, str]] = {}

    for ship in ships:
        ref = ship.pop("_storage_macro_ref")
        if not ref:
            continue
        if ref not in cache:
            matches = idx.find(f"*/{ref}.xml")
            cargo_el = ET.fromstring(idx.read(matches[0])).find(".//cargo") if matches else None
            if cargo_el is None:
                cache[ref] = (None, "")
            else:
                try:
                    cmax = int(cargo_el.get("max", 0))
                except (TypeError, ValueError):
                    cmax = None
                cache[ref] = (cmax, cargo_el.get("tags", ""))
        ship["cargo_max"], ship["cargo_tags"] = cache[ref]


def gen_ships_py(ships) -> str:
    items = [(s["macro_id"], repr(s["display"])) for s in ships]
    return (GENERATED_BANNER +
            "\n# Ship macro id → display name (ship macro XML identification/@name\n"
            "# resolved via page 20101 of the language file).\n"
            "# Used by the ship scanner to label ships; unknown macros fall back\n"
            "# to hull origin + role derived from the macro name itself.\n" +
            _fmt_dict("SHIP_NAMES", "dict[str, str]", items))


def gen_ship_stats_py(ships) -> str:
    blocks = []
    for s in ships:
        blocks.append(
            f"    '{s['macro_id']}': {{\n"
            f"        'class':              '{s['class']}',\n"
            f"        'max_hull':           {s['max_hull']},\n"
            f"        'price':              {s['price']},\n"
            f"        'hardpoints':         {_fmt_hardpoints(s['hardpoints'])},\n"
            f"        'purchasable':        {s['purchasable']},\n"
            f"        'flown':              {s['flown']},\n"
            f"        'weapon_heat_factor': {s['weapon_heat_factor']},\n"
            f"        'ship_type':          {s['ship_type']!r},\n"
            f"        'purpose':            {s['purpose']!r},\n"
            f"        'makerrace':          {s['makerrace']!r},\n"
            f"        'crew_capacity':      {s['crew_capacity']!r},\n"
            f"        'missile_storage':    {s['missile_storage']!r},\n"
            f"        'unit_storage':       {s['unit_storage']!r},\n"
            f"        'cargo_max':          {s['cargo_max']!r},\n"
            f"        'cargo_tags':         {s['cargo_tags']!r},\n"
            f"        'description':        {s['description']!r},\n"
            f"        'variation':          {s['variation']!r},\n"
            f"    }},")
    return (GENERATED_BANNER +
            "\n# Ship macro id → static game stats (ship macro XML + component XML +\n"
            "# cargo-bay macro + wares.xml).\n"
            "#   class          — ship size class (ship_s, ship_m, ship_l, ship_xl, ship_xs)\n"
            "#   max_hull       — base maximum hull HP before mods\n"
            "#   price          — average buy price in credits (0 if the hull isn't sold)\n"
            "#   hardpoints     — slot layout {type: {size: count}} from the hull component\n"
            "#                    (type = weapon/turret/shield/engine; size = s/m/l/xl)\n"
            "#   purchasable    — True if the player can buy this new at a shipyard. False\n"
            "#                    for hulls only obtainable by capture or story reward (e.g.\n"
            "#                    Xenon/Kha'ak ships) — still real, ownable ships.\n"
            "#   flown          — False means no faction owns/flies this hull at all (NPC\n"
            "#                    skin variant, escape pod, deployable drone, colony-ship\n"
            "#                    set-piece part) — never a real or encounterable ship.\n"
            "#                    The design builder's hull catalog drops these; naming\n"
            "#                    tables (ships.py) keep them so any scanned entity still\n"
            "#                    resolves to a name.\n"
            "#   weapon_heat_factor — multiplies every mounted weapon's heat generation\n"
            "#                    (1.0 = no effect, the common case). Confirmed against real\n"
            "#                    tooltips: lowers Time to Overheat proportionally, does NOT\n"
            "#                    affect Sustained Weapon Damage or Cooldown Duration.\n"
            "#   ship_type      — the macro's own <ship type=...> role tag (e.g. 'destroyer',\n"
            "#                    'heavyfighter', 'largeminer') — the game's own role\n"
            "#                    classification, not guessed from the macro id.\n"
            "#   purpose        — coarser <purpose primary=...> bucket: fight/trade/mine/\n"
            "#                    build/auxiliary/salvage. '' if the macro has none.\n"
            "#   makerrace      — <identification makerrace=...>, lowercase race key (e.g.\n"
            "#                    'argon') — same key space as equipment's race field.\n"
            "#   crew_capacity  — <people capacity=...>; None if the macro has no crew slot.\n"
            "#   missile_storage/unit_storage — <storage missile=.. unit=..> counts; None if\n"
            "#                    the macro has no such storage element.\n"
            "#   cargo_max      — m3 capacity from the hull's cargo-bay macro (resolved via\n"
            "#                    the ship macro's storage <connection>); None if the hull\n"
            "#                    has no cargo bay (most fighters/drones).\n"
            "#   cargo_tags     — ware-type tags on that cargo bay (e.g. 'container', 'solid',\n"
            "#                    'liquid'); '' if cargo_max is None.\n"
            "#   description/variation — flavour text + variant name (e.g. 'Vanguard'),\n"
            "#                    resolved from the language file; '' if the macro has none.\n"
            "SHIP_STATS: dict[str, dict] = {\n" +
            "\n".join(blocks) + "\n}\n")


# ──────────────────────────────────────────────────────────────────────────
#  station_stats.py — STATION_STATS
# ──────────────────────────────────────────────────────────────────────────

def gen_station_stats_py(idx: CatalogIndex) -> str:
    """
    Reads all station structure module XMLs and shield equipment XMLs,
    building STATION_STATS keyed by lowercase macro name.

    Structure macros  (assets/structures/*/macros/*.xml, base + DLC):
      hull        → <hull max="N"/>
      cargo       → <cargo max="N"/>   (storage modules)
      produces    → <production><queue ware="..."/>  (production modules)

    Shield equipment  (assets/props/surfaceelements/macros/shield_*.xml, base + DLC):
      max_shield  → <recharge max="N"/>
      Alias macros (a <macro> with a ref/alias attribute and no <recharge> of
      its own) inherit max_shield from the macro they reference.

    Only entries with at least one meaningful value are emitted — decorative
    pieces and pure connection modules (no hull/shield/cargo/produces) are
    dropped. This matches the scanner behaviour: STATION_STATS is used as a
    filter; components missing from it are skipped during module parsing.
    """
    stats: dict[str, dict] = {}

    # ── Structure modules ────────────────────────────────────────────────
    struct_paths = (
        idx.find("assets/structures/*/macros/*.xml") +
        idx.find("extensions/*/assets/structures/*/macros/*.xml")
    )
    # Like shields, a structure macro can be a pure alias: a ref/alias to another
    # macro with no stats of its own. Record those and resolve in a second pass.
    struct_aliases: dict[str, str] = {}
    for vp in struct_paths:
        root = ET.fromstring(idx.read(vp))
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue
        macro_id = macro_el.get("name", "").lower()
        if not macro_id:
            continue

        entry: dict = {}

        hull_el = root.find(".//hull")
        if hull_el is not None:
            v = int(hull_el.get("max", 0) or 0)
            if v > 0:
                entry["max_hull"] = v

        cargo_el = root.find(".//cargo")
        if cargo_el is not None:
            v = int(cargo_el.get("max", 0) or 0)
            if v > 0:
                entry["cargo_capacity"] = v

        queue_el = root.find(".//production/queue")
        if queue_el is not None:
            ware = queue_el.get("ware", "")
            if ware:
                entry["produces"] = ware

        if entry:
            stats[macro_id] = entry
        else:
            # No stats of its own → inherit from the macro it points at.
            ref = (macro_el.get("ref") or macro_el.get("alias") or "").lower()
            if ref:
                struct_aliases[macro_id] = ref

    # Resolve structure aliases against the concrete macros gathered above. Copy
    # the whole entry (hull/cargo/produces) so the alias behaves like its target.
    for macro_id, ref in struct_aliases.items():
        target = stats.get(ref)
        if target:
            stats[macro_id] = dict(target)

    # ── Shield equipment ─────────────────────────────────────────────────
    # Shields live under assets/props/surfaceelements/, not equipment/.
    shield_paths = (
        idx.find("assets/props/surfaceelements/macros/shield_*.xml") +
        idx.find("extensions/*/assets/props/surfaceelements/macros/shield_*.xml")
    )
    # Some shield macros are pure aliases: they carry a ref/alias to another
    # macro and have no <recharge> of their own, inheriting that macro's stats
    # (e.g. shield_xen_m_standard_02_mk1 → ..._04_mk1, added in 9.00). Record
    # them and resolve in a second pass, once every concrete macro is loaded —
    # otherwise the referenced macro might not be in `stats` yet.
    shield_aliases: dict[str, str] = {}
    for vp in shield_paths:
        root = ET.fromstring(idx.read(vp))
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue
        macro_id = macro_el.get("name", "").lower()
        if not macro_id:
            continue

        recharge_el = root.find(".//recharge")
        if recharge_el is not None:
            v = int(recharge_el.get("max", 0) or 0)
            if v > 0:
                stats[macro_id] = {"max_shield": v}
        else:
            # No recharge of its own → inherit from the macro it points at.
            ref = (macro_el.get("ref") or macro_el.get("alias") or "").lower()
            if ref:
                shield_aliases[macro_id] = ref

    # Resolve aliases against the concrete macros gathered above. Skip any whose
    # target is missing or had no shield value, so we never emit an entry the
    # scanner can't use.
    for macro_id, ref in shield_aliases.items():
        target = stats.get(ref)
        if target and "max_shield" in target:
            stats[macro_id] = {"max_shield": target["max_shield"]}

    # ── Format output ────────────────────────────────────────────────────
    def _entry_str(e: dict) -> str:
        lines = []
        if "max_hull"       in e: lines.append(f"        'max_hull':       {e['max_hull']},")
        if "max_shield"     in e: lines.append(f"        'max_shield':     {e['max_shield']},")
        if "cargo_capacity" in e: lines.append(f"        'cargo_capacity': {e['cargo_capacity']},")
        if "produces"       in e: lines.append(f"        'produces':       {repr(e['produces'])},")
        return "\n".join(lines)

    blocks = [f"    '{k}': {{\n{_entry_str(v)}\n    }},"
              for k, v in sorted(stats.items())]

    return (
        GENERATED_BANNER +
        "\n# Station module + shield equipment macro → static game stats.\n"
        "#   max_hull       — base maximum hull HP (structure modules)\n"
        "#   max_shield     — shield recharge capacity in HP (shield equipment)\n"
        "#   cargo_capacity — maximum cargo volume in m³ (storage modules)\n"
        "#   produces       — ware id produced by this module (production modules)\n"
        "# Used by StationHandler._parse_modules() and ShipHandler for shield HP.\n"
        "# Entries with no meaningful values (decorative, connection pieces) are omitted.\n"
        "STATION_STATS = {\n" +
        "\n".join(blocks) + "\n}\n"
    )


# ──────────────────────────────────────────────────────────────────────────
#  sector_stats.py — SECTOR_SUNLIGHT
# ──────────────────────────────────────────────────────────────────────────

# Classifies dataset macro strings from mapdefaults.xml.
_SECTOR_CLASSIFY_RE  = re.compile(r'^Cluster_\d+_Sector\d+_macro$', re.IGNORECASE)
_CLUSTER_CLASSIFY_RE = re.compile(r'^Cluster_\d+_macro$',            re.IGNORECASE)
# Extracts cluster part from a lowercase sector macro: "cluster_601_sector001_macro" → "cluster_601"
_SECTOR_PARENT_RE    = re.compile(r'^(cluster_\d+)_sector\d+_macro$')
# Extracts cluster/sector numbers for page-20004 lang-ID calculation.
_SECTOR_NUMS_RE      = re.compile(r'^cluster_(\d+)_sector(\d+)_macro$')
# The lang-file sector-name pattern: "{20003,N}(Display Name)" — name is in parens.
_SECTOR_NAME_PAREN_RE = re.compile(r'\(([^)]+)\)\s*$')


def _sector_display_name(sector_macro: str, texts_20004: dict) -> str:
    """Resolve a lowercase sector macro to its human-readable display name.

    Page 20004 lang-ID formula (confirmed by scanner/language.py):
      lang_id = str(cluster_num * 10) + str(sector_num * 10 + 1).zfill(3)
    e.g. cluster_01_sector001_macro → cluster=1, sector=1
         → "10" + "011" = "10011" → looks up {20004:10011}
    """
    m = _SECTOR_NUMS_RE.match(sector_macro)
    if not m:
        return ""
    lang_id = str(int(m.group(1)) * 10) + str(int(m.group(2)) * 10 + 1).zfill(3)
    raw = texts_20004.get(f"20004:{lang_id}", "")
    nm = _SECTOR_NAME_PAREN_RE.search(raw)
    return nm.group(1) if nm else ""


def gen_sector_stats_py(idx: CatalogIndex, texts_20004: dict) -> str:
    """
    Generates SECTOR_SUNLIGHT keyed by lowercase sector macro.

    Reads libraries/mapdefaults.xml (base + DLC). DLCs that ship a <diff>
    patch are applied in catalog order; additive DLCs have their <dataset>
    entries merged directly.

    Boron DLC stores sunlight at the cluster level (Cluster_601_macro) rather
    than on individual sectors. Sector sunlight is derived from the parent
    cluster for any sector that lacks its own <area sunlight="..."/> entry.
    """
    # ── Merge mapdefaults ────────────────────────────────────────────────
    base_root = ET.fromstring(idx.read("libraries/mapdefaults.xml"))
    for vp in idx.find("extensions/*/libraries/mapdefaults.xml"):
        dlc_root = ET.fromstring(idx.read(vp))
        if dlc_root.tag == "diff":
            apply_diff(base_root, dlc_root, source=vp)
        else:
            # Non-diff DLC: merge datasets into the base <defaults> block.
            dst = base_root.find("defaults") or base_root
            src = dlc_root.find("defaults") or dlc_root
            for ds in src.findall("dataset"):
                dst.append(ds)

    defaults_el = base_root.find("defaults") or base_root

    # ── Collect sunlights by macro type ──────────────────────────────────
    cluster_sun: dict[str, float] = {}   # cluster macro → sunlight
    sector_sun:  dict[str, float] = {}   # sector macro  → sunlight
    all_sectors: set[str]         = set()  # every sector-like macro seen

    for ds in defaults_el.findall("dataset"):
        macro = ds.get("macro", "")
        if _SECTOR_CLASSIFY_RE.match(macro):
            all_sectors.add(macro.lower())
        # Sunlight lives at <dataset><properties><area sunlight="..."/>
        area = ds.find("properties/area")
        sun_str = area.get("sunlight") if area is not None else None
        if sun_str is None:
            continue
        sun = float(sun_str)
        if _CLUSTER_CLASSIFY_RE.match(macro):
            cluster_sun[macro.lower()] = sun
        elif _SECTOR_CLASSIFY_RE.match(macro):
            sector_sun[macro.lower()] = sun

    # ── Resolve sunlight for every known sector ───────────────────────────
    # Sectors with direct sunlight use it; others fall back to their parent
    # cluster (Boron DLC pattern). Sectors with no resolution are omitted —
    # the scanner falls back to 1.0 for any macro not in the table.
    result: dict[str, float] = {}
    for sm in sorted(all_sectors):
        if sm in sector_sun:
            result[sm] = sector_sun[sm]
        else:
            m_p = _SECTOR_PARENT_RE.match(sm)
            if m_p:
                parent = m_p.group(1) + "_macro"
                if parent in cluster_sun:
                    result[sm] = cluster_sun[parent]

    # ── Format output ────────────────────────────────────────────────────
    key_width = max((len(k) for k in result), default=30) + 2
    lines = ["SECTOR_SUNLIGHT: dict[str, float] = {"]
    for sm, sun in sorted(result.items()):
        name    = _sector_display_name(sm, texts_20004)
        comment = f"  # {name}" if name else ""
        key_str = ('"' + sm + '":').ljust(key_width + 1)
        lines.append(f"    {key_str} {repr(sun)},{comment}")
    lines.append("}")

    return (
        GENERATED_BANNER +
        "\n# Sector macro → sunlight multiplier (libraries/mapdefaults.xml + DLC).\n"
        "# Keys are lowercase sector macros, matching what the save-file scanner reads.\n"
        "# Sunlight affects energy cell production only:\n"
        "#   effective_output = base_output * sunlight\n"
        "# 1.0 = standard output; above 1.0 = more cells per cycle.\n"
        "# Sectors absent from this table fall back to 1.0 in the scanner.\n" +
        "\n".join(lines) + "\n"
    )


# ──────────────────────────────────────────────────────────────────────────

def main() -> int:
    game_dir = find_x4_install()
    if game_dir is None:
        print("FAIL: no X4 installation found — nothing generated.")
        return 1
    print(f"Reading game files from: {game_dir}")

    idx = CatalogIndex.from_game_dir(game_dir)

    # ── Wares (wares.xml + DLC diffs + waregroups.xml + t-file page 20201) ──
    wares_root = load_merged_wares(idx)
    wares = select_wares(wares_root)
    group_textids = load_group_textids(idx)
    # Page 20201 serves both the wares tables and station_names.
    texts_20201 = load_texts(idx, {"20201"})
    print(f"Selected {len(wares)} wares "
          f"({len(EXTRA_WARE_IDS)} via explicit extras list)")

    # ── Ships (ship macro XMLs + t-file pages 20101 + 20111) ────────────
    # 20101 — ship base names and full variant entries (refs to 20111)
    # 20111 — variant suffixes ("Vanguard", "Sentinel") and type qualifiers
    #         ("\(Gas\)", "\(Mineral\)") referenced inside the 20101 entries
    texts_ships = load_texts(idx, {"20101", "20111"})
    prices = load_macro_prices(idx)         # macro → average buy price (hulls + equipment)
    hardpoints = load_hardpoints(idx)       # component → {type: {size: count}}
    availability = load_macro_availability(idx)  # macro → owners + purchasable
    ships = load_ship_data(idx, texts_ships, prices, hardpoints, availability)
    load_cargo_for_ships(idx, ships)
    print(f"Found {len(ships)} ship macros "
          f"({sum(1 for s in ships if s['price'])} priced, {sum(1 for s in ships if s['hardpoints'])} with slots, "
          f"{sum(1 for s in ships if s['flown'])} flown, "
          f"{sum(1 for s in ships if s['flown'] and not s['purchasable'])} capture/story-only, "
          f"{sum(1 for s in ships if s['cargo_max'])} with cargo data)")

    # ── Station stats (structure modules + shields, page 20004 for sector names) ──
    # Page 20004 is also used by gen_sector_stats_py for display-name comments.
    texts_20004 = load_texts(idx, {"20004"})

    outputs = {
        "wares.py":            gen_wares_py(wares, group_textids, texts_20201),
        "ware_prices.py":      gen_ware_prices_py(wares),
        "production_stats.py": gen_production_stats_py(wares),
        "station_names.py":    gen_station_names_py(wares, texts_20201),
        "ships.py":            gen_ships_py(ships),
        "ship_stats.py":       gen_ship_stats_py(ships),
        "station_stats.py":    gen_station_stats_py(idx),
        "sector_stats.py":     gen_sector_stats_py(idx, texts_20004),
    }
    for fname, content in outputs.items():
        path = DATA_DIR / fname
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"Wrote {path.relative_to(REPO)}")

    print("\nDone — review with: git diff data/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
