# Core role: Generates the deployables/EVA-gear catalog (satellites, mines,
# resource probes, spacesuit gear) by parsing their macros from the X4
# install's .cat archives, the same way generate_equipment.py does for ship
# hardpoint equipment -- these were previously excluded there (see its
# "mines and all spacesuit gear are excluded" header note) because they
# aren't ship-hardpoint items, so they never had a generator of their own.
#
# Output: data/item_stats.py with ITEM_STATS (macro -> stats)
# Run after game update or DLC install: python gamefiles/generate_items.py
#
# DESIGN: generate-and-commit for reviewable diffs on game patches. Like
# generate_software.py, "is this a real, purchasable item" is decided purely
# by whether wares.xml prices it -- mission-only variants (a "_story" mine,
# an alias-only "_a" mine that shares its canonical sibling's ware entry, a
# cut Split Vendetta mine with no <ware> at all) are dropped for lack of a
# price rather than needing their own name-based exclusion list.

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from lxml import etree as ET

from gamefiles.catalog import CatalogIndex, find_x4_install
from gamefiles.generate_data import load_macro_price_ranges, load_merged_wares
from gamefiles.langtext import _REF_RE, clean_text, load_texts

DATA_DIR = REPO / "data"

GENERATED_BANNER = (
    "# ─────────────────────────────────────────────────────────────────────────────\n"
    "#  AUTO-GENERATED by gamefiles/generate_items.py — DO NOT EDIT BY HAND.\n"
    "#  Source: assets/props/{equipment/satelite,equipment/probe,weaponsystems/mines,\n"
    "#  weaponsystems/spacesuit,engines} + weaponfx bomb/bullet macros, read directly\n"
    "#  from the X4 install's .cat archives.\n"
    "#  Re-run after a game update or DLC install:\n"
    "#      python gamefiles/generate_items.py\n"
    "#  then review the git diff for what the patch changed.\n"
    "# ─────────────────────────────────────────────────────────────────────────────\n"
)

# Field order for the emitted per-entry dicts: identity first, then the
# category-specific stats grouped together. Absent fields are skipped.
_FIELD_ORDER = [
    "category", "class", "name", "description",
    "price", "price_min", "price_max",
    # satellite
    "detection_range_m",
    # mine / spacesuit ammo (bomb)
    "explosion_damage", "on_collision", "friendfoe", "proximity_trigger_m",
    # resource probe
    "decay_delay_s", "lifetime_s",
    # spacesuit weapon
    "damage_hull", "range_m", "reload_rate", "repair",
    # spacesuit engine
    "thrust_forward", "boost_thrust", "boost_duration",
    # shared
    "hull_max",
]


# ──────────────────────────────────────────────────────────────────────────
#  Small parse helpers (same conventions as generate_equipment.py)
# ──────────────────────────────────────────────────────────────────────────

def _float(el, attr: str):
    if el is None:
        return None
    v = el.get(attr)
    try:
        return float(v) if v not in (None, "") else None
    except (ValueError, TypeError):
        return None


def _num(v):
    """Round to 3dp, then collapse to a plain int when that's exact."""
    if v is None:
        return None
    r = round(v, 3)
    return int(r) if r == int(r) else r


def _glob(idx: CatalogIndex, *patterns: str) -> list[str]:
    seen: set[str] = set()
    for p in patterns:
        seen.update(idx.find(p))
    return sorted(seen)


def _read_macros(idx: CatalogIndex, *patterns: str) -> dict[str, ET._Element]:
    """macro id (lowercase) -> its <macro> element, for every file matching
    any of the given patterns. Unlike generate_equipment.py's equipment pass,
    none of these categories have DLCs shipping a <diff> patch over a base
    file at the same relative path -- every DLC mine/spacesuit file seen here
    is a complete, standalone macro -- so no merge step is needed."""
    out: dict[str, ET._Element] = {}
    for vp in _glob(idx, *patterns):
        root = ET.fromstring(idx.read(vp))
        macro_el = root.find(".//macro")
        if macro_el is None:
            continue
        mid = macro_el.get("name", "").lower()
        if mid:
            out[mid] = macro_el
    return out


# ──────────────────────────────────────────────────────────────────────────
#  Per-category stat extraction
# ──────────────────────────────────────────────────────────────────────────

def _satellite_stats(props: ET._Element) -> dict:
    out: dict = {}
    radar = props.find("radar")
    hull = props.find("hull")
    r = _float(radar, "range")
    if r is not None:
        out["detection_range_m"] = _num(r)
    h = _float(hull, "max")
    if h is not None:
        out["hull_max"] = _num(h)
    return out


def _explosion_stats(props: ET._Element) -> dict:
    """Shared by mines and the spacesuit bomb-launcher's limpet ammo -- both
    are a <explosiondamage>-carrying deployable with the same trigger/range
    shape. value/hull is a hull-damage explosive; shield-only (no value/hull)
    means an EMP-type charge that only drains shields (the limpet EMP bomb)."""
    out: dict = {}
    dmg_el = props.find("explosiondamage")
    dmg = _float(dmg_el, "value")
    if dmg is None:
        dmg = _float(dmg_el, "hull")
    if dmg is None:
        dmg = _float(dmg_el, "shield")
    if dmg is not None:
        out["explosion_damage"] = _num(dmg)

    trigger = props.find("trigger")
    if trigger is not None:
        if trigger.get("oncollision") is not None:
            out["on_collision"] = trigger.get("oncollision") == "1"
        if trigger.get("friendfoe") is not None:
            out["friendfoe"] = trigger.get("friendfoe") == "1"

    rng = props.find("range")
    t = _float(rng, "trigger")
    if t is not None:
        out["proximity_trigger_m"] = _num(t)

    hull = props.find("hull")
    h = _float(hull, "max")
    if h is not None:
        out["hull_max"] = _num(h)
    return out


def _probe_stats(props: ET._Element) -> dict:
    out: dict = {}
    hull = props.find("hull")
    h = _float(hull, "max")
    if h is not None:
        out["hull_max"] = _num(h)

    decay = props.find("hulldecay")
    dmg   = _float(decay, "damage")
    delay = _float(decay, "delay")
    if dmg and delay:
        out["decay_delay_s"] = _num(delay)
        if h:
            # How long the probe survives before its own slow decay destroys
            # it -- max hull / (damage per tick) x seconds per tick.
            out["lifetime_s"] = _num((h / dmg) * delay)
    return out


def _bullet_stats(bullet_props: ET._Element | None) -> dict:
    """damage_hull/range_m/repair for one spacesuit weapon's bullet macro.
    Same value/hull fallback as _explosion_stats -- the hand laser's bullet
    carries its (tiny) damage as hull= rather than value=."""
    out: dict = {}
    if bullet_props is None:
        return out
    dmg_el = bullet_props.find("damage")
    dmg = _float(dmg_el, "value")
    if dmg is None:
        dmg = _float(dmg_el, "hull")
    if dmg is not None:
        out["damage_hull"] = _num(dmg)
    if dmg_el is not None and dmg_el.get("repair") == "1":
        out["repair"] = True

    bul_el = bullet_props.find("bullet")
    rng = _float(bul_el, "range")
    if rng is not None:
        out["range_m"] = _num(rng)
    return out


def _spacesuit_weapon_stats(props: ET._Element, bullets: dict[str, ET._Element]) -> dict:
    out: dict = {}
    reload_el = props.find("reload")
    rate = _float(reload_el, "rate")
    interval = (1.0 / rate) if rate else _float(reload_el, "time")
    if interval:
        out["reload_rate"] = round(1.0 / interval, 3)

    bullet_ref = props.find("bullet")
    bid = (bullet_ref.get("class") or "").lower() if bullet_ref is not None else ""
    bullet_el = bullets.get(bid)
    if bullet_el is not None:
        out.update(_bullet_stats(bullet_el.find("properties")))
    return out


def _spacesuit_engine_stats(props: ET._Element) -> dict:
    out: dict = {}
    thrust = props.find("thrust")
    f = _float(thrust, "forward")
    if f is not None:
        out["thrust_forward"] = _num(f)

    boost = props.find("boost")
    bt = _float(boost, "thrust")
    bd = _float(boost, "duration")
    if bt is not None:
        out["boost_thrust"] = _num(bt)
    if bd is not None:
        out["boost_duration"] = _num(bd)
    return out


# ──────────────────────────────────────────────────────────────────────────
#  Assembly
# ──────────────────────────────────────────────────────────────────────────

# (glob patterns, stat-extractor, category label) -- extractor takes just the
# macro's <properties> element except spacesuit weapons, which also need the
# bullet table to look up their damage (handled as a special case below).
_CATEGORY_GLOBS = {
    "satellite": (
        ["assets/props/equipment/satelite/macros/*macro*.xml",
         "extensions/*/assets/props/equipment/satelite/macros/*macro*.xml"],
        _satellite_stats,
    ),
    "mine": (
        ["assets/props/weaponsystems/mines/macros/*macro*.xml",
         "extensions/*/assets/props/weaponsystems/mines/macros/*macro*.xml"],
        _explosion_stats,
    ),
    "probe": (
        ["assets/props/equipment/probe/macros/*macro*.xml",
         "extensions/*/assets/props/equipment/probe/macros/*macro*.xml"],
        _probe_stats,
    ),
}

_SPACESUIT_WEAPON_GLOBS = [
    "assets/props/weaponsystems/spacesuit/macros/*macro*.xml",
    "extensions/*/assets/props/weaponsystems/spacesuit/macros/*macro*.xml",
]
_SPACESUIT_ENGINE_GLOBS = [
    "assets/props/engines/macros/engine_gen_spacesuit_*macro*.xml",
    "assets/props/engines/macros/engine_spacesuit_weak_macro.xml",
    "extensions/*/assets/props/engines/macros/engine_gen_spacesuit_*macro*.xml",
    "extensions/*/assets/props/engines/macros/engine_spacesuit_weak_macro.xml",
]
_SPACESUIT_AMMO_GLOBS = [
    "assets/fx/weaponfx/macros/bomb_player_limpet_*macro*.xml",
    "extensions/*/assets/fx/weaponfx/macros/bomb_player_limpet_*macro*.xml",
]
_BULLET_GLOBS = [
    "assets/fx/weaponfx/macros/bullet_spacesuit_*macro*.xml",
    "extensions/*/assets/fx/weaponfx/macros/bullet_spacesuit_*macro*.xml",
]


def load_items(idx: CatalogIndex) -> tuple[list[dict], set[str]]:
    """Returns (records, name_pages), same shape as generate_software.py's
    load_software(). Every candidate macro across all four categories is
    kept only if wares.xml prices it -- see module docstring."""
    prices = load_macro_price_ranges(idx)
    ware_root = load_merged_wares(idx)
    ware_by_comp: dict[str, ET._Element] = {}
    for w in ware_root.findall("ware"):
        comp = w.find("component")
        if comp is not None and comp.get("ref"):
            ware_by_comp[comp.get("ref").lower()] = w

    records: list[dict] = []
    name_pages: set[str] = set()

    def _emit(mid: str, category: str, macro_el: ET._Element, stats: dict) -> None:
        price = prices.get(mid)
        ware = ware_by_comp.get(mid)
        if price is None or ware is None:
            return  # not a real, purchasable item (mission prop, cut content, alias)
        name_ref = ware.get("name", "")
        desc_ref = ware.get("description", "")
        for page, _id in _REF_RE.findall(name_ref):
            name_pages.add(page)
        for page, _id in _REF_RE.findall(desc_ref):
            name_pages.add(page)
        records.append({
            "id": mid, "category": category, "class": macro_el.get("class", ""),
            "name_ref": name_ref, "description_ref": desc_ref,
            "price": price[1], "price_min": price[0], "price_max": price[2],
            **stats,
        })

    for category, (patterns, extractor) in _CATEGORY_GLOBS.items():
        for mid, macro_el in _read_macros(idx, *patterns).items():
            props = macro_el.find("properties")
            _emit(mid, category, macro_el, extractor(props) if props is not None else {})

    bullets = _read_macros(idx, *_BULLET_GLOBS)
    for mid, macro_el in _read_macros(idx, *_SPACESUIT_WEAPON_GLOBS).items():
        props = macro_el.find("properties")
        stats = _spacesuit_weapon_stats(props, bullets) if props is not None else {}
        _emit(mid, "spacesuit", macro_el, stats)
    for mid, macro_el in _read_macros(idx, *_SPACESUIT_ENGINE_GLOBS).items():
        props = macro_el.find("properties")
        stats = _spacesuit_engine_stats(props) if props is not None else {}
        _emit(mid, "spacesuit", macro_el, stats)
    for mid, macro_el in _read_macros(idx, *_SPACESUIT_AMMO_GLOBS).items():
        props = macro_el.find("properties")
        stats = _explosion_stats(props) if props is not None else {}
        _emit(mid, "spacesuit", macro_el, stats)

    return records, name_pages


def gen_items_py(records: list[dict]) -> str:
    lines = []
    for r in sorted(records, key=lambda r: (r["category"], r["id"])):
        parts = []
        for field in _FIELD_ORDER:
            if field in r and r[field] is not None:
                parts.append(f"{field!r}: {r[field]!r}")
        lines.append(f"    '{r['id']}': {{{', '.join(parts)}}},")

    return (
        GENERATED_BANNER +
        "\n# Deployable/EVA item macro id -> static game stats.\n"
        "#   category  — 'satellite' | 'mine' | 'probe' | 'spacesuit', for UI grouping.\n"
        "#   class     — the raw macro class attribute (satellite/mine/resourceprobe/\n"
        "#               weapon/bomb/engine).\n"
        "#   name, description — display name / tooltip text (t-file resolved).\n"
        "#   price, price_min, price_max — average/min/max wares.xml buy price, same\n"
        "#               caveat as equipment_stats.py: the live shop price can run above\n"
        "#               even price_max (reputation/station markup the static files can't\n"
        "#               capture).\n"
        "#   explosion_damage — mines and the spacesuit bomb-launcher's limpet ammo;\n"
        "#               hull damage, except the EMP limpet which only drains shields.\n"
        "#   lifetime_s — resource probes only: how long it survives its own slow\n"
        "#               hull decay before it's destroyed.\n"
        "ITEM_STATS: dict[str, dict] = {\n" +
        "\n".join(lines) + "\n}\n"
    )


def main() -> int:
    game_dir = find_x4_install()
    if game_dir is None:
        print("FAIL: no X4 installation found — nothing generated.")
        return 1
    print(f"Reading game files from: {game_dir}")

    idx = CatalogIndex.from_game_dir(game_dir)
    records, name_pages = load_items(idx)
    print(f"Found {len(records)} deployable/EVA items")

    texts = load_texts(idx, name_pages)
    for rec in records:
        rec["name"] = clean_text(rec.pop("name_ref", ""), texts)
        rec["description"] = clean_text(rec.pop("description_ref", ""), texts)

    before = len(records)
    records = [r for r in records if r["name"] and "{" not in r["name"]]
    if before - len(records):
        print(f"Dropped {before - len(records)} records with no display name")

    out_path = DATA_DIR / "item_stats.py"
    out_path.write_text(gen_items_py(records), encoding="utf-8", newline="\n")
    print(f"Wrote {out_path.relative_to(REPO)}")
    print("\nDone — review with: git diff data/item_stats.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
