"""
generate_ship_stats.py
======================
Reads all ship macro XML files from the 'ship xml/' folder and writes
data/ship_stats.py, which contains the SHIP_STATS lookup dict.

SHIP_STATS maps each ship macro name to a dict of static specs pulled
directly from the game's macro definition files. Currently extracts:

    max_hull  — the ship's base maximum hull HP (before mods)

Designed to be extended: add new keys here as more stats are needed.

HOW TO RUN:
    python generate_ship_stats.py

Re-run after adding new XML files to 'ship xml/' (e.g. after a DLC
update) to keep data/ship_stats.py in sync.
"""

import pathlib
import xml.etree.ElementTree as ET

# ── Paths ─────────────────────────────────────────────────────────────────────

# The folder containing extracted ship macro XMLs from the game
XML_DIR  = pathlib.Path(__file__).parent / "ship xml"

# The output file that will be imported by the scanner
OUT_FILE = pathlib.Path(__file__).parent / "data" / "ship_stats.py"

# ── Ship class names that represent whole ships (not subcomponents) ───────────
# X4 macro XMLs include part macros (hab modules, storage sections, etc.)
# that share the same folder. We only want entries for whole ships, which
# always have a class attribute starting with one of these values.
SHIP_CLASSES = {"ship_xs", "ship_s", "ship_m", "ship_l", "ship_xl"}

# ── Parse every XML file in the directory tree ────────────────────────────────

ship_xml_path = XML_DIR
if not ship_xml_path.exists():
    print(f"[Error] Folder not found: {ship_xml_path}")
    exit(1)

xml_files = list(ship_xml_path.rglob("*.xml"))
print(f"[Info] Found {len(xml_files)} XML files in '{XML_DIR.name}/'")

stats = {}  # { macro_name: { 'max_hull': int, ... } }
skipped = 0

for xml_file in xml_files:
    try:
        tree = ET.parse(xml_file)
        root = tree.getroot()

        # Each file has a single <macro name="..." class="..."> element
        macro_elem = root.find("macro")
        if macro_elem is None:
            skipped += 1
            continue

        macro_name  = macro_elem.get("name", "")
        macro_class = macro_elem.get("class", "")

        # Skip subcomponent macros — we only want whole-ship entries
        if macro_class not in SHIP_CLASSES:
            skipped += 1
            continue

        # Look for <hull max="..."/> inside <properties>
        hull_elem = macro_elem.find("properties/hull")
        if hull_elem is None:
            # A ship macro with no hull entry is unusual — skip silently
            skipped += 1
            continue

        max_hull_str = hull_elem.get("max")
        if max_hull_str is None:
            skipped += 1
            continue

        # Store as int — hull values in X4 macro files are always whole numbers
        stats[macro_name] = {
            "max_hull": int(max_hull_str),
        }

    except ET.ParseError as e:
        # If an XML file is malformed, report it and move on rather than crash
        print(f"[Warning] Could not parse {xml_file.name}: {e}")
        skipped += 1

print(f"[Info] Extracted stats for {len(stats)} ships  ({skipped} files skipped)")

# ── Write data/ship_stats.py ──────────────────────────────────────────────────

# Sort by macro name so the file is stable and easy to diff in git
sorted_stats = dict(sorted(stats.items()))

lines = []
lines.append("# ─────────────────────────────────────────────────────────────────────────────")
lines.append("#  SHIP STATS")
lines.append("#  Maps ship macro names to their static game stats, extracted from the")
lines.append("#  macro XML files in 'ship xml/'.")
lines.append("#")
lines.append("#  AUTO-GENERATED by generate_ship_stats.py — do not edit by hand.")
lines.append("#  Re-run generate_ship_stats.py after adding new XMLs to 'ship xml/'.")
lines.append("#")
lines.append("#  CURRENT KEYS PER ENTRY:")
lines.append("#    max_hull  — base maximum hull HP before any mods are applied")
lines.append("# ─────────────────────────────────────────────────────────────────────────────")
lines.append("")
lines.append("SHIP_STATS = {")

for macro_name, entry in sorted_stats.items():
    # Each entry is a dict so new stats can be added later without restructuring
    lines.append(f"    {macro_name!r}: {{")
    lines.append(f"        'max_hull': {entry['max_hull']},")
    lines.append(f"    }},")

lines.append("}")
lines.append("")

OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
print(f"[Done] Written to {OUT_FILE}")
