"""
generate_production_stats.py
============================
Reads libraries/wares.xml and writes data/production_stats.py.

PRODUCTION_STATS maps each economy ware ID to its production recipe:
    group   — ware category (hightech, refined, energy, gases, etc.)
    time    — production cycle duration in seconds
    amount  — units produced per cycle
    methods — dict of method_id → {input_ware_id: amount_consumed_per_cycle}
              Only player-buildable methods are included (noplayerbuild entries
              are skipped). Mineable resources (ore, silicon, ice, etc.) have no
              <production> element and are excluded entirely.

HOW TO RUN:
    python Generators/generate_production_stats.py

REQUIRED INPUT:
    XML Library/libraries/wares.xml — extracted from X4's .cat files.
    XRCatTool command (run from the X4 install directory):
        for /L %i in (1,1,9) do XRCatTool -in "0%i.cat" -out "<project>\\XML Library" -include "libraries/wares\\.xml"

Re-run after a game update or DLC install.

HOW PRODUCTION_STATS IS USED:
    data/production_stats.py is imported by the scanner and display layers to
    compute per-station economy metrics: cycle rate, units per hour, and
    input consumption rates for the economy tab.
"""

import pathlib
import xml.etree.ElementTree as ET

ROOT      = pathlib.Path(__file__).parent.parent
WARES_XML = ROOT / "XML Library" / "libraries" / "wares.xml"
OUT_FILE  = ROOT / "data" / "production_stats.py"


def parse_wares(xml_path: pathlib.Path) -> dict:
    tree = ET.parse(xml_path)
    root = tree.getroot()

    stats = {}

    for ware in root.findall("ware"):
        ware_id = ware.get("id")
        tags    = ware.get("tags", "").split()
        group   = ware.get("group", "")

        if "economy" not in tags:
            continue

        methods    = {}
        time_val   = None
        amount_val = None

        for prod in ware.findall("production"):
            prod_tags   = prod.get("tags", "").split()
            method_id   = prod.get("method", "default")

            if "noplayerbuild" in prod_tags:
                continue

            # time and amount are the same across faction methods for any given ware —
            # only the inputs differ. Use the first buildable production as the
            # canonical values.
            if time_val is None:
                time_val   = int(prod.get("time",   0))
                amount_val = int(prod.get("amount", 0))

            inputs  = {}
            primary = prod.find("primary")
            if primary is not None:
                for w in primary.findall("ware"):
                    inputs[w.get("ware")] = int(w.get("amount", 0))

            methods[method_id] = inputs

        # Skip wares with no player-buildable production (mineable resources, etc.)
        if not methods:
            continue

        stats[ware_id] = {
            "group":   group,
            "time":    time_val,
            "amount":  amount_val,
            "methods": methods,
        }

    return stats


def write_output(stats: dict, out_path: pathlib.Path) -> None:
    lines = [
        "# ─────────────────────────────────────────────────────────────────────────────",
        "#  PRODUCTION STATS",
        "#  Generated by Generators/generate_production_stats.py from libraries/wares.xml.",
        "#  Re-run the generator after a game update or DLC install.",
        "#",
        "#  Keys   : ware ID (lowercase, matches keys in data/wares.py WARE_NAMES)",
        "#  Values :",
        "#    group   — ware category (hightech, refined, energy, gases, etc.)",
        "#    time    — production cycle duration in seconds",
        "#    amount  — units produced per cycle",
        "#    methods — dict of method_id → {input_ware_id: amount_consumed_per_cycle}",
        "#              'default' is the standard method. Faction methods ('argon',",
        "#              'teladi', 'paranid') appear only where they differ in inputs.",
        "#              Energy cells has an empty inputs dict — it needs no raw inputs.",
        "#              Mineable resources (ore, silicon, ice, etc.) are absent entirely.",
        "# ─────────────────────────────────────────────────────────────────────────────",
        "",
        "PRODUCTION_STATS: dict[str, dict] = {",
    ]

    for ware_id, data in sorted(stats.items()):
        lines.append(f"    {ware_id!r}: {{")
        lines.append(f'        "group":   {data["group"]!r},')
        lines.append(f'        "time":    {data["time"]},')
        lines.append(f'        "amount":  {data["amount"]},')
        lines.append(f'        "methods": {{')
        for method_id, inputs in sorted(data["methods"].items()):
            if inputs:
                parts = ", ".join(f"{k!r}: {v}" for k, v in sorted(inputs.items()))
                lines.append(f"            {method_id!r}: {{{parts}}},")
            else:
                lines.append(f"            {method_id!r}: {{}},")
        lines.append(f"        }},")
        lines.append(f"    }},")

    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[Output] Written to: {out_path}")
    print(f"[Stats]  {len(stats)} economy wares with player-buildable production recipes")


if __name__ == "__main__":
    if not WARES_XML.exists():
        print(f"[Error] wares.xml not found at: {WARES_XML}")
        raise SystemExit(1)

    print(f"[Input]  Parsing {WARES_XML}...")
    stats = parse_wares(WARES_XML)
    write_output(stats, OUT_FILE)
