"""
generate_ware_prices.py
=======================
Reads libraries/wares.xml and writes data/ware_prices.py.

WARE_PRICES maps each economy ware ID to its market price band:
    min     — the lowest the game will let the ware trade at
    average — the neutral/reference price
    max     — the highest the game will let the ware trade at

WHY THIS EXISTS:
    The station budget calculation values "trade wares" (wares a station buys
    and sells purely to trade, not to feed production) at the MAX market price.
    Those wares are often mineables (ore, silicon, gases) which have no
    <production> recipe and therefore never appear in PRODUCTION_STATS — so we
    need a separate price table that covers every economy ware, producible or
    not.

HOW TO RUN:
    python Generators/generate_ware_prices.py

REQUIRED INPUT:
    XML Library/libraries/wares.xml — extracted from X4's .cat files.
    XRCatTool command (run from the X4 install directory):
        for /L %i in (1,1,9) do XRCatTool -in "0%i.cat" -out "<project>\\XML Library" -include "libraries/wares\\.xml"

Re-run after a game update or DLC install.
"""

import pathlib
import xml.etree.ElementTree as ET

ROOT      = pathlib.Path(__file__).parent.parent
WARES_XML = ROOT / "XML Library" / "libraries" / "wares.xml"
OUT_FILE  = ROOT / "data" / "ware_prices.py"


def parse_prices(xml_path: pathlib.Path) -> dict:
    tree = ET.parse(xml_path)
    root = tree.getroot()

    prices = {}

    for ware in root.findall("ware"):
        ware_id = ware.get("id")
        tags    = ware.get("tags", "").split()

        # Only economy wares trade on the market — equipment, software, and
        # other non-economy entries have no meaningful market band.
        if "economy" not in tags:
            continue

        price = ware.find("price")
        if price is None:
            continue

        prices[ware_id] = {
            "min":     int(price.get("min",     0)),
            "average": int(price.get("average", 0)),
            "max":     int(price.get("max",     0)),
        }

    return prices


def write_output(prices: dict, out_path: pathlib.Path) -> None:
    lines = [
        "# ─────────────────────────────────────────────────────────────────────────────",
        "#  WARE PRICES",
        "#  Generated by Generators/generate_ware_prices.py from libraries/wares.xml.",
        "#  Re-run the generator after a game update or DLC install.",
        "#",
        "#  Keys   : ware ID (lowercase, matches keys in data/wares.py WARE_NAMES)",
        "#  Values : {'min': int, 'average': int, 'max': int} — the market price band.",
        "#",
        "#  Used by the station budget calculation to value 'trade wares' (wares a",
        "#  station buys and sells purely to trade) at the MAX market price. Covers",
        "#  every economy ware, including mineables that have no production recipe.",
        "# ─────────────────────────────────────────────────────────────────────────────",
        "",
        "WARE_PRICES: dict[str, dict] = {",
    ]

    for ware_id, band in sorted(prices.items()):
        lines.append(
            f'    {ware_id!r}: {{"min": {band["min"]}, '
            f'"average": {band["average"]}, "max": {band["max"]}}},'
        )

    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[Output] Written to: {out_path}")
    print(f"[Stats]  {len(prices)} economy wares with price bands")


if __name__ == "__main__":
    if not WARES_XML.exists():
        print(f"[Error] wares.xml not found at: {WARES_XML}")
        raise SystemExit(1)

    print(f"[Input]  Parsing {WARES_XML}...")
    prices = parse_prices(WARES_XML)
    write_output(prices, OUT_FILE)
