#!/usr/bin/env python3
"""
list_sectors.py
---------------
Standalone script — does not import any X4 Foresight project modules.

Scans save_001.xml (or save_001.xml.gz) from the project root, lists every
unique sector found in the save file, and lists all stations in The Void.

Usage:
    python Generators/list_sectors.py

Requirements:
    - save_001.xml (or save_001.xml.gz) in the project root
    - 0001-l044.xml in the project root for human-readable names (optional;
      without it, raw macro strings are shown instead)
"""

import gzip
import pathlib
import re
import time

from lxml import etree as ET

# ─── Paths ────────────────────────────────────────────────────────────────────
# This script lives in Generators/, so the project root is one level up.
PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
SAVE_PATH    = PROJECT_ROOT / "save_001.xml"
LANG_PATH    = PROJECT_ROOT / "0001-l044.xml"

# Transparently try the compressed version if the plain XML isn't present.
if not SAVE_PATH.exists():
    SAVE_PATH = PROJECT_ROOT / "save_001.xml.gz"

# Wares file — used to resolve exact in-game factory names (e.g. "Solar Power Plant").
# The fallback chain is tried in order; the first path that exists is used.
# To switch to the game's own extracted files, add that path as a second entry.
_WARES_CANDIDATES = [
    PROJECT_ROOT / "XML Library" / "libraries" / "wares.xml",
    # Example: pathlib.Path(r"C:\SteamLibrary\steamapps\common\X4 Foundations\extracted\libraries\wares.xml"),
]
WARES_PATH = next((p for p in _WARES_CANDIDATES if p.exists()), _WARES_CANDIDATES[0])

# ─── Constants ────────────────────────────────────────────────────────────────
# All component class values that represent a station-level object.
STATION_CLASSES = {"station", "factory", "headquarters", "complex"}

# All component class values that represent a ship.
# Used to build the ship-tracking stack so $homebase assignments can be
# attributed to the correct ship even when ships are nested inside carriers.
SHIP_CLASSES = {"ship_s", "ship_m", "ship_l", "ship_xl"}

# Faction abbreviations inlined from data/factions.py.
# Used to prefix NPC station names in X4's UI style, e.g. "ARG Trade Station I".
FACTION_ABBR = {
    "argon":            "ARG",
    "antigone":         "ANT",
    "hatikvah":         "HAT",
    "paranid":          "PAR",
    "trinity":          "TRI",
    "split":            "ZYA",
    "fallensplit":      "FAF",
    "freesplit":        "FRF",
    "teladi":           "TEL",
    "ministry":         "MIN",
    "xenon":            "XEN",
    "khaak":            "KHK",
    "buccaneers":       "BUC",
    "scaleplate":       "SCA",
    "loanshark":        "RIP",
    "holyorder":        "HOP",
    "holyorderfanatic": "HOF",
    "yaki":             "YAK",
    "pioneers":         "PIO",
    "terran":           "TER",
    "boron":            "BOR",
}

# Roman numerals for the nameindex attribute (X4 uses this as a duplicate counter).
_ROMAN = [
    "", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
    "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX",
]

# ─── Regex patterns (pre-compiled) ───────────────────────────────────────────
# Language file sector entries look like "{20003,270001}(The Void)".
# Extracts the human name from the parentheses at the end.
_SECTOR_NAME_RE = re.compile(r'\(([^)]+)\)\s*$')

# Matches sector macro strings like "cluster_43_sector001_macro".
_SECTOR_MACRO_RE = re.compile(r'cluster_(\d+)_sector(\d+)_macro', re.IGNORECASE)

# Matches bare {page,id} language references, e.g. "{20102,5}" or "{20215,3}".
# Used to resolve the basename attribute on station elements.
_TEXT_REF_RE = re.compile(r'^\{(\d+),(\d+)\}$')

# Extracts the ware ID from production module macros like "prod_arg_energycells_macro".
# The faction token uses non-greedy matching to handle multi-part names (e.g. prod_gen_...).
_PROD_MACRO_RE = re.compile(r'^prod_(?:\w+?)_(\w+)_macro$', re.IGNORECASE)

# ─── Ship display name lookup ────────────────────────────────────────────────
# Copied from data/ships.py (auto-generated by generate_ship_names.py).
# Maps macro → exact in-game display name. _parse_ship_macro() tries this first
# and only falls through to the regex if the macro isn't listed here.
SHIP_NAMES = {
    'ship_arg_l_destroyer_01_a_macro': 'Behemoth Vanguard',
    'ship_arg_l_destroyer_01_b_macro': 'Behemoth Sentinel',
    'ship_arg_l_destroyer_02_a_macro': 'Behemoth E',
    'ship_arg_l_miner_liquid_01_a_macro': 'Magnetar (Gas) Vanguard',
    'ship_arg_l_miner_liquid_01_b_macro': 'Magnetar (Gas) Sentinel',
    'ship_arg_l_miner_solid_01_a_macro': 'Magnetar (Mineral) Vanguard',
    'ship_arg_l_miner_solid_01_b_macro': 'Magnetar (Mineral) Sentinel',
    'ship_arg_l_trans_container_01_a_macro': 'Veles Vanguard',
    'ship_arg_l_trans_container_01_b_macro': 'Veles Sentinel',
    'ship_arg_l_trans_container_02_a_macro': 'Mokosi Vanguard',
    'ship_arg_l_trans_container_02_b_macro': 'Mokosi Sentinel',
    'ship_arg_l_trans_container_03_a_macro': 'Incarcatura Vanguard',
    'ship_arg_l_trans_container_03_b_macro': 'Incarcatura Sentinel',
    'ship_arg_l_trans_container_04_a_macro': 'Shuyaku Vanguard',
    'ship_arg_l_trans_container_04_b_macro': 'Shuyaku Sentinel',
    'ship_arg_l_trans_container_05_a_macro': 'Sonra Vanguard',
    'ship_arg_l_trans_container_05_b_macro': 'Sonra Sentinel',
    'ship_arg_m_bomber_01_a_macro': 'Minotaur Vanguard',
    'ship_arg_m_bomber_01_b_macro': 'Minotaur Sentinel',
    'ship_arg_m_bomber_02_a_macro': 'Minotaur Raider',
    'ship_arg_m_frigate_01_a_macro': 'Cerberus Vanguard',
    'ship_arg_m_frigate_01_b_macro': 'Cerberus Sentinel',
    'ship_arg_m_miner_liquid_01_a_macro': 'Sunder (Gas) Vanguard',
    'ship_arg_m_miner_liquid_01_b_macro': 'Sunder (Gas) Sentinel',
    'ship_arg_m_miner_solid_01_a_macro': 'Drill (Mineral) Vanguard',
    'ship_arg_m_miner_solid_01_b_macro': 'Drill (Mineral) Sentinel',
    'ship_arg_m_trans_container_01_a_macro': 'Mercury Vanguard',
    'ship_arg_m_trans_container_01_b_macro': 'Mercury Sentinel',
    'ship_arg_m_trans_container_02_a_macro': 'Ides Vanguard',
    'ship_arg_m_trans_container_02_b_macro': 'Ides Sentinel',
    'ship_arg_s_fighter_01_a_macro': 'Nova Vanguard',
    'ship_arg_s_fighter_01_b_macro': 'Nova Sentinel',
    'ship_arg_s_fighter_02_a_macro': 'Elite Vanguard',
    'ship_arg_s_fighter_02_b_macro': 'Elite Sentinel',
    'ship_arg_s_fighter_03_a_macro': 'Pulsar Vanguard',
    'ship_arg_s_fighter_04_a_macro': 'Quasar Vanguard',
    'ship_arg_s_heavyfighter_01_a_macro': 'Eclipse Vanguard',
    'ship_arg_s_heavyfighter_01_b_macro': 'Eclipse Sentinel',
    'ship_arg_s_heavyfighter_02_a_macro': 'Eclipse Vanguard',
    'ship_arg_s_miner_solid_01_a_macro': 'Courier (Mineral)',
    'ship_arg_s_racer_01_a_macro': 'Elite Sport',
    'ship_arg_s_scout_01_a_macro': 'Discoverer Vanguard',
    'ship_arg_s_scout_01_b_macro': 'Discoverer Sentinel',
    'ship_arg_s_trans_container_01_a_macro': 'Courier Vanguard',
    'ship_arg_s_trans_container_01_b_macro': 'Courier Sentinel',
    'ship_arg_s_trans_container_02_a_macro': 'Callisto Vanguard',
    'ship_arg_s_trans_container_02_b_macro': 'Callisto Sentinel',
    'ship_arg_xl_builder_01_a_macro': 'Mammoth Vanguard',
    'ship_arg_xl_builder_01_b_macro': 'Mammoth Sentinel',
    'ship_arg_xl_carrier_01_a_macro': 'Colossus Vanguard',
    'ship_arg_xl_carrier_01_b_macro': 'Colossus Sentinel',
    'ship_arg_xl_carrier_02_a_macro': 'Colossus E',
    'ship_arg_xl_resupplier_01_a_macro': 'Nomad Vanguard',
    'ship_arg_xl_resupplier_01_b_macro': 'Nomad Sentinel',
    'ship_arg_xs_cv_01_a_macro': 'Mass Transporter C',
    'ship_arg_xs_cv_02_a_macro': 'Mass Transporter D',
    'ship_arg_xs_police_01_a_macro': 'Argon Station Security Vessel',
    'ship_arg_xs_pv_01_a_macro': 'Civilian Ship A',
    'ship_arg_xs_pv_01_b_macro': 'Civilian Ship A',
    'ship_arg_xs_pv_01_c_macro': 'Civilian Ship A',
    'ship_arg_xs_pv_01_d_macro': 'Civilian Ship A',
    'ship_arg_xs_pv_02_a_macro': 'Tour Bus A',
    'ship_arg_xs_pv_03_a_macro': 'Mass Transporter A',
    'ship_arg_xs_pv_03_b_macro': 'Mass Transporter A',
    'ship_arg_xs_pv_04_a_macro': 'Mass Transporter B',
    'ship_arg_xs_pv_04_b_macro': 'Mass Transporter B',
    'ship_arg_xs_pv_05_a_macro': 'Short Range Transporter A',
    'ship_arg_xs_pv_05_b_macro': 'Short Range Transporter A',
    'ship_arg_xs_pv_05_c_macro': 'Short Range Transporter A',
    'ship_arg_xs_spacesuit_01_a_macro': 'Space Suit',
    'ship_atf_l_destroyer_01_a_macro': 'Syn',
    'ship_atf_xl_battleship_01_a_macro': 'Asgard',
    'ship_bor_l_carrier_01_a_macro': 'Guppy',
    'ship_bor_l_destroyer_01_a_macro': 'Ray',
    'ship_bor_l_miner_liquid_01_a_macro': 'Rorqual (Gas)',
    'ship_bor_l_miner_solid_01_a_macro': 'Rorqual (Mineral)',
    'ship_bor_l_trans_container_01_a_macro': 'Sturgeon',
    'ship_bor_m_corvette_01_a_macro': 'Hydra',
    'ship_bor_m_corvette_02_a_macro': 'Hydra Regal',
    'ship_bor_m_gunboat_01_a_macro': 'Thresher',
    'ship_bor_m_miner_liquid_01_a_macro': 'Porpoise (Gas)',
    'ship_bor_m_miner_solid_01_a_macro': 'Porpoise (Mineral)',
    'ship_bor_m_trans_container_01_a_macro': 'Dolphin',
    'ship_bor_s_fighter_01_a_macro': 'Mako',
    'ship_bor_s_heavyfighter_01_a_macro': 'Barracuda',
    'ship_bor_s_miner_solid_01_a_macro': 'Grouper (Mineral)',
    'ship_bor_s_scout_01_a_macro': 'Piranha',
    'ship_bor_s_scout_02_a_macro': 'Irukandji',
    'ship_bor_s_trans_container_01_a_macro': 'Terrapin',
    'ship_bor_xl_builder_01_a_macro': 'Walrus',
    'ship_bor_xl_carrier_01_a_macro': 'Shark',
    'ship_bor_xl_resupplier_01_a_macro': 'Orca',
    'ship_bor_xs_cv_01_a_macro': 'Mass Transporter C',
    'ship_bor_xs_cv_02_a_macro': 'Mass Transporter D',
    'ship_bor_xs_cv_03_a_macro': 'Mass Transporter F',
    'ship_bor_xs_pv_01_a_macro': 'Civilian Ship B',
    'ship_bor_xs_pv_02_a_macro': 'Tour Bus B',
    'ship_bor_xs_pv_03_a_macro': 'Short Range Transporter B',
    'ship_bor_xs_pv_04_a_macro': 'Short Range Transporter C',
    'ship_bor_xs_pv_05_a_macro': 'Short Range Transporter D',
    'ship_bor_xs_spacesuit_01_a_macro': 'Space Suit',
    'ship_gen_m_transdrone_container_01_a_macro': 'Medium Drop Drone',
    'ship_gen_m_transdrone_container_02_a_macro': 'Medium Terraforming Drone',
    'ship_gen_m_tugboat_01_a_macro': 'Manticore',
    'ship_gen_m_yacht_01_a_macro': 'Astrid',
    'ship_gen_s_fighter_01_a_macro': 'Nodan Vanguard',
    'ship_gen_s_fighter_01_b_macro': 'Nodan Sentinel',
    'ship_gen_s_fightingdrone_01_a_macro': 'Defence Drone',
    'ship_gen_s_fightingdrone_explosive_01_a_macro': 'Defence Drone',
    'ship_gen_s_miningdrone_liquid_01_a_macro': 'Gas Collector Drone',
    'ship_gen_s_miningdrone_solid_01_a_macro': 'Mining Drone',
    'ship_gen_s_racer_01_a_macro': 'Dart',
    'ship_gen_s_transdrone_container_01_a_macro': 'Small Drop Drone',
    'ship_gen_s_transdrone_container_02_a_macro': 'Small Terraforming Drone',
    'ship_gen_xs_boardingpod_01_a_macro': 'Boarding Pod',
    'ship_gen_xs_buildingdrone_01_a_macro': 'Building Drone',
    'ship_gen_xs_cargodrone_container_01_a_macro': 'Cargo Drone',
    'ship_gen_xs_cargodrone_empty_01_a_macro': 'Cargo Drone',
    'ship_gen_xs_cargodrone_equipment_01_a_macro': 'Cargo Drone',
    'ship_gen_xs_cargodrone_liquid_01_a_macro': 'Cargo Drone',
    'ship_gen_xs_cargodrone_pickup_01_a_macro': 'Cargo Drone',
    'ship_gen_xs_cargodrone_solid_01_a_macro': 'Cargo Drone',
    'ship_gen_xs_distressbeacon_01_a_macro': 'Autonomous Distress Drone',
    'ship_gen_xs_escapepod_01_a_macro': 'Escape Pod',
    'ship_gen_xs_repairdrone_01_a_macro': 'Repair Drone',
    'ship_gen_xs_spacesuit_01_a_macro': 'Space Suit',
    'ship_kha_l_destroyer_01_a_macro': 'Ravager',
    'ship_kha_m_fighter_01_a_macro': "Queen's Guard",
    'ship_kha_m_fighter_02_a_macro': 'Hive Guard',
    'ship_kha_s_fighter_01_a_macro': 'Protector',
    'ship_kha_s_fighter_02_a_macro': 'Forager',
    'ship_kha_xl_battleship_01_a_macro': 'Obliterator',
    'ship_par_l_destroyer_01_a_macro': 'Odysseus Vanguard',
    'ship_par_l_destroyer_01_b_macro': 'Odysseus Sentinel',
    'ship_par_l_destroyer_02_a_macro': 'Odysseus E',
    'ship_par_l_miner_liquid_01_a_macro': 'Chthonios (Gas) Vanguard',
    'ship_par_l_miner_liquid_01_b_macro': 'Chthonios (Gas) Sentinel',
    'ship_par_l_miner_liquid_02_a_macro': 'Chthonios E (Gas)',
    'ship_par_l_miner_solid_01_a_macro': 'Chthonios (Mineral) Vanguard',
    'ship_par_l_miner_solid_01_b_macro': 'Chthonios (Mineral) Sentinel',
    'ship_par_l_miner_solid_02_a_macro': 'Chthonios E (Mineral)',
    'ship_par_l_trans_container_01_a_macro': 'Helios Vanguard',
    'ship_par_l_trans_container_01_b_macro': 'Helios Sentinel',
    'ship_par_l_trans_container_02_a_macro': 'Selene Vanguard',
    'ship_par_l_trans_container_02_b_macro': 'Selene Sentinel',
    'ship_par_l_trans_container_03_a_macro': 'Helios E',
    'ship_par_m_corvette_01_a_macro': 'Nemesis Vanguard',
    'ship_par_m_corvette_01_b_macro': 'Nemesis Sentinel',
    'ship_par_m_frigate_01_a_macro': 'Gorgon Vanguard',
    'ship_par_m_frigate_01_b_macro': 'Gorgon Sentinel',
    'ship_par_m_miner_liquid_01_a_macro': 'Plutus (Gas) Vanguard',
    'ship_par_m_miner_liquid_01_b_macro': 'Plutus (Gas) Sentinel',
    'ship_par_m_miner_solid_01_a_macro': 'Plutus (Mineral) Vanguard',
    'ship_par_m_miner_solid_01_b_macro': 'Plutus (Mineral) Sentinel',
    'ship_par_m_trans_container_01_a_macro': 'Demeter Vanguard',
    'ship_par_m_trans_container_01_b_macro': 'Demeter Sentinel',
    'ship_par_m_trans_container_02_a_macro': 'Hermes Vanguard',
    'ship_par_m_trans_container_02_b_macro': 'Hermes Sentinel',
    'ship_par_m_trans_container_03_a_macro': 'Prometheus',
    'ship_par_s_fighter_01_a_macro': 'Perseus Vanguard',
    'ship_par_s_fighter_01_b_macro': 'Perseus Sentinel',
    'ship_par_s_fighter_02_a_macro': 'Theseus Vanguard',
    'ship_par_s_fighter_02_b_macro': 'Theseus Sentinel',
    'ship_par_s_heavyfighter_01_a_macro': 'Ares',
    'ship_par_s_miner_solid_01_a_macro': 'Tethys (Mineral)',
    'ship_par_s_racer_01_a_macro': 'Theseus Sport',
    'ship_par_s_scout_01_a_macro': 'Pegasus Vanguard',
    'ship_par_s_scout_01_b_macro': 'Pegasus Sentinel',
    'ship_par_s_trans_container_01_a_macro': 'Tethys Vanguard',
    'ship_par_s_trans_container_01_b_macro': 'Tethys Sentinel',
    'ship_par_xl_builder_01_a_macro': 'Heracles Vanguard',
    'ship_par_xl_builder_01_b_macro': 'Heracles Sentinel',
    'ship_par_xl_carrier_01_a_macro': 'Zeus Vanguard',
    'ship_par_xl_carrier_01_b_macro': 'Zeus Sentinel',
    'ship_par_xl_carrier_02_a_macro': 'Zeus E',
    'ship_par_xl_resupplier_01_a_macro': 'Atlas Vanguard',
    'ship_par_xl_resupplier_01_b_macro': 'Atlas Sentinel',
    'ship_par_xl_resupplier_02_a_macro': 'Atlas E',
    'ship_par_xs_police_01_a_macro': 'Paranid Station Security Vessel',
    'ship_par_xs_pv_01_a_macro': 'Civilian Ship B',
    'ship_par_xs_pv_02_a_macro': 'Mass Transporter E',
    'ship_par_xs_pv_03_a_macro': 'Civilian Ship C',
    'ship_par_xs_pv_04_a_macro': 'Short Range Transporter B',
    'ship_par_xs_spacesuit_01_a_macro': 'Space Suit',
    'ship_pir_l_miner_solid_01_a_macro': 'Donia',
    'ship_pir_l_scavenger_01_a_macro': 'Barbarossa',
    'ship_pir_l_scavenger_01_a_storyhighcapacity_macro': 'Barbarossa',
    'ship_pir_l_scrapper_01_macro': 'Teuta',
    'ship_pir_s_fighter_01_a_macro': 'Kyd',
    'ship_pir_s_fighter_02_a_macro': 'Lux',
    'ship_pir_s_heavyfighter_01_a_macro': 'Shih',
    'ship_pir_s_trans_condensate_01_a_macro': 'Raleigh (Condensate)',
    'ship_pir_s_trans_container_01_a_macro': 'Raleigh (Container)',
    'ship_pir_xl_battleship_01_a_macro': 'Erlking',
    'ship_pir_xl_builder_01_macro': 'Gannascus',
    'ship_spl_l_destroyer_01_a_macro': 'Rattlesnake',
    'ship_spl_l_miner_liquid_01_a_macro': 'Wyvern (Gas)',
    'ship_spl_l_miner_solid_01_a_macro': 'Wyvern (Mineral)',
    'ship_spl_l_trans_container_01_a_macro': 'Buffalo',
    'ship_spl_m_bomber_01_a_macro': 'Viper',
    'ship_spl_m_corvette_01_a_macro': 'Dragon',
    'ship_spl_m_corvette_01_b_macro': 'Dragon Raider',
    'ship_spl_m_frigate_01_a_macro': 'Cobra',
    'ship_spl_m_miner_liquid_01_a_macro': 'Alligator (Gas)',
    'ship_spl_m_miner_solid_01_a_macro': 'Alligator (Mineral)',
    'ship_spl_m_trans_container_01_a_macro': 'Boa',
    'ship_spl_s_fighter_01_a_macro': 'Mamba',
    'ship_spl_s_fighter_02_a_macro': 'Asp',
    'ship_spl_s_fighter_02_b_macro': 'Asp Raider',
    'ship_spl_s_heavyfighter_01_a_macro': 'Chimera',
    'ship_spl_s_heavyfighter_02_a_macro': 'Balaur',
    'ship_spl_s_miner_solid_01_a_macro': 'Tuatara (Mineral)',
    'ship_spl_s_scenariofighter_01_a_macro': 'Chimera',
    'ship_spl_s_scout_01_a_macro': 'Jaguar',
    'ship_spl_s_trans_container_01_a_macro': 'Tuatara',
    'ship_spl_s_trans_container_01_plot_01_macro': 'Tuatara',
    'ship_spl_xl_ark_01_a_macro': 'Colony Ship',
    'ship_spl_xl_battleship_01_a_macro': 'Python',
    'ship_spl_xl_builder_01_a_macro': 'Elephant',
    'ship_spl_xl_carrier_01_a_macro': 'Raptor',
    'ship_spl_xl_resupplier_01_a_macro': 'Monitor',
    'ship_spl_xs_cv_01_a_macro': 'Short Range Transporter B',
    'ship_spl_xs_cv_01_b_macro': 'Short Range Transporter B',
    'ship_spl_xs_cv_02_a_macro': 'Short Range Transporter C',
    'ship_spl_xs_cv_02_b_macro': 'Short Range Transporter C',
    'ship_spl_xs_cv_03_a_macro': 'Short Range Transporter D',
    'ship_spl_xs_cv_03_b_macro': 'Short Range Transporter D',
    'ship_spl_xs_police_01_a_macro': 'Split Station Security Vessel',
    'ship_spl_xs_pv_01_a_macro': 'Civilian Ship B',
    'ship_spl_xs_pv_01_b_macro': 'Civilian Ship B',
    'ship_spl_xs_pv_01_c_macro': 'Civilian Ship B',
    'ship_spl_xs_pv_02_a_macro': 'Civilian Ship C',
    'ship_spl_xs_pv_02_b_macro': 'Civilian Ship C',
    'ship_spl_xs_pv_02_c_macro': 'Civilian Ship C',
    'ship_spl_xs_pv_03_a_macro': 'Civilian Ship D',
    'ship_spl_xs_pv_03_b_macro': 'Civilian Ship D',
    'ship_spl_xs_pv_03_c_macro': 'Civilian Ship D',
    'ship_spl_xs_spacesuit_01_a_macro': 'Space Suit',
    'ship_tel_l_destroyer_01_a_macro': 'Phoenix Vanguard',
    'ship_tel_l_destroyer_01_b_macro': 'Phoenix Sentinel',
    'ship_tel_l_destroyer_02_a_macro': 'Phoenix E',
    'ship_tel_l_miner_liquid_01_a_macro': 'Crane (Gas) Vanguard',
    'ship_tel_l_miner_liquid_01_b_macro': 'Crane (Gas) Sentinel',
    'ship_tel_l_miner_liquid_02_a_macro': 'Crane E (Gas)',
    'ship_tel_l_miner_solid_01_a_macro': 'Crane (Mineral) Vanguard',
    'ship_tel_l_miner_solid_01_b_macro': 'Crane (Mineral) Sentinel',
    'ship_tel_l_miner_solid_02_a_macro': 'Crane E (Mineral)',
    'ship_tel_l_trans_container_01_a_macro': 'Pelican Vanguard',
    'ship_tel_l_trans_container_01_b_macro': 'Pelican Sentinel',
    'ship_tel_l_trans_container_02_a_macro': 'Heron Vanguard',
    'ship_tel_l_trans_container_02_b_macro': 'Heron Sentinel',
    'ship_tel_l_trans_container_03_a_macro': 'Heron E',
    'ship_tel_m_bomber_01_a_macro': 'Peregrine Vanguard',
    'ship_tel_m_bomber_01_b_macro': 'Peregrine Sentinel',
    'ship_tel_m_frigate_01_a_macro': 'Osprey Vanguard',
    'ship_tel_m_frigate_01_b_macro': 'Osprey Sentinel',
    'ship_tel_m_miner_liquid_01_a_macro': 'Manorina (Gas) Vanguard',
    'ship_tel_m_miner_liquid_01_b_macro': 'Manorina (Gas) Sentinel',
    'ship_tel_m_miner_solid_01_a_macro': 'Manorina (Mineral) Vanguard',
    'ship_tel_m_miner_solid_01_b_macro': 'Manorina (Mineral) Sentinel',
    'ship_tel_m_trans_container_01_a_macro': 'Vulture Vanguard',
    'ship_tel_m_trans_container_01_b_macro': 'Vulture Sentinel',
    'ship_tel_m_trans_container_02_a_macro': 'Tern Vanguard',
    'ship_tel_m_trans_container_02_b_macro': 'Tern Sentinel',
    'ship_tel_m_trans_container_03_a_macro': 'Cormorant Vanguard',
    'ship_tel_s_fighter_01_a_macro': 'Falcon Vanguard',
    'ship_tel_s_fighter_01_b_macro': 'Falcon Sentinel',
    'ship_tel_s_fighter_02_a_macro': 'Buzzard Vanguard',
    'ship_tel_s_fighter_02_b_macro': 'Buzzard Sentinel',
    'ship_tel_s_miner_solid_01_a_macro': 'Magpie (Mineral)',
    'ship_tel_s_racer_01_a_macro': 'Kestrel Sport',
    'ship_tel_s_scout_01_a_macro': 'Kestrel Vanguard',
    'ship_tel_s_scout_01_b_macro': 'Kestrel Sentinel',
    'ship_tel_s_scout_02_a_macro': 'Guillemot Vanguard',
    'ship_tel_s_scout_02_b_macro': 'Guillemot Sentinel',
    'ship_tel_s_trans_container_01_a_macro': 'Magpie Vanguard',
    'ship_tel_s_trans_container_01_b_macro': 'Magpie Sentinel',
    'ship_tel_s_trans_container_02_a_macro': 'Raven',
    'ship_tel_xl_builder_01_a_macro': 'Albatross Vanguard',
    'ship_tel_xl_builder_01_b_macro': 'Albatross Sentinel',
    'ship_tel_xl_carrier_01_a_macro': 'Condor Vanguard',
    'ship_tel_xl_carrier_01_b_macro': 'Condor Sentinel',
    'ship_tel_xl_resupplier_01_a_macro': 'Stork Vanguard',
    'ship_tel_xl_resupplier_01_b_macro': 'Stork Sentinel',
    'ship_tel_xs_police_01_a_macro': 'Teladi Station Security Vessel A',
    'ship_tel_xs_police_02_a_macro': 'Teladi Station Security Vessel B',
    'ship_tel_xs_police_03_a_macro': 'Teladi Station Security Vessel C',
    'ship_tel_xs_pv_01_a_macro': 'Civilian Ship D',
    'ship_tel_xs_pv_01_b_macro': 'Civilian Ship D',
    'ship_tel_xs_pv_02_a_macro': 'Short Range Transporter C',
    'ship_tel_xs_pv_02_b_macro': 'Short Range Transporter C',
    'ship_tel_xs_pv_03_a_macro': 'Tour Bus B',
    'ship_tel_xs_pv_03_b_macro': 'Tour Bus B',
    'ship_tel_xs_pv_04_a_macro': 'Mass Transporter F',
    'ship_tel_xs_pv_04_b_macro': 'Mass Transporter F',
    'ship_tel_xs_spacesuit_01_a_macro': 'Space Suit',
    'ship_tel_xs_spacesuit_01_b_macro': 'Space Suit',
    'ship_ter_l_destroyer_01_a_macro': 'Osaka',
    'ship_ter_l_flagship_01_a_macro': 'Sapporo',
    'ship_ter_l_flagship_01_b_macro': 'Sapporo',
    'ship_ter_l_miner_liquid_01_a_macro': 'Hokkaido (Gas)',
    'ship_ter_l_miner_solid_01_a_macro': 'Hokkaido (Mineral)',
    'ship_ter_l_research_01_a_macro': 'Okinawa Research',
    'ship_ter_l_trans_container_01_a_macro': 'Okinawa',
    'ship_ter_m_corvette_01_a_macro': 'Katana',
    'ship_ter_m_corvette_02_a_macro': 'Odachi',
    'ship_ter_m_corvette_02_b_macro': 'Odachi',
    'ship_ter_m_frigate_01_a_macro': 'Falx',
    'ship_ter_m_gunboat_01_a_macro': 'Jian',
    'ship_ter_m_miner_liquid_01_a_macro': 'Bolo (Gas)',
    'ship_ter_m_miner_solid_01_a_macro': 'Bolo (Mineral)',
    'ship_ter_m_trans_container_01_a_macro': 'Baldric',
    'ship_ter_s_fighter_01_a_macro': 'Kukri',
    'ship_ter_s_fighter_02_a_macro': 'Kalis',
    'ship_ter_s_fighter_03_a_macro': 'Takoba',
    'ship_ter_s_fighter_04_a_macro': 'Cutlass',
    'ship_ter_s_fighter_04_b_macro': 'Cutlass',
    'ship_ter_s_heavyfighter_01_a_macro': 'Gladius',
    'ship_ter_s_miner_solid_01_a_macro': 'Kopis (Mineral)',
    'ship_ter_s_scout_01_a_macro': 'Rapier',
    'ship_ter_s_scout_02_a_macro': 'Nimcha',
    'ship_ter_s_trans_container_01_a_macro': 'Frog',
    'ship_ter_s_xperimental_01_a_macro': 'Xperimental Shuttle',
    'ship_ter_xl_builder_01_a_macro': 'Kyushu',
    'ship_ter_xl_carrier_01_a_macro': 'Tokyo',
    'ship_ter_xl_resupplier_01_a_macro': 'Honshu',
    'ship_ter_xs_cv_01_a_macro': 'Short Range Transporter',
    'ship_ter_xs_cv_02_a_macro': 'Maintenance Vessel',
    'ship_ter_xs_police_01_a_macro': 'Terran Station Security Vessel',
    'ship_ter_xs_pv_01_a_macro': 'Civilian Ship A',
    'ship_ter_xs_pv_02_a_macro': 'Civilian Ship B',
    'ship_ter_xs_pv_03_a_macro': 'Tour Bus',
    'ship_tfm_xl_carrier_01_a_macro': 'Unknown Ship',
    'ship_tfm_xl_carrier_02_a_macro': 'Unknown Ship',
    'ship_tfm_xl_carrier_02_b_macro': '#dace',
    'ship_xen_l_terraformer_01_a_macro': 'H',
    'ship_xen_m_corvette_01_a_macro': 'B',
    'ship_xen_m_corvette_02_a_macro': 'PE',
    'ship_xen_m_fighter_01_a_macro': 'P',
    'ship_xen_m_miner_01_a_macro': 'S',
    'ship_xen_m_miner_solid_01_a_macro': 'SE',
    'ship_xen_s_fighter_01_a_macro': 'N',
    'ship_xen_s_fighter_02_a_macro': 'M',
    'ship_xen_s_heavyfighter_01_a_macro': 'F',
    'ship_xen_s_scout_01_a_macro': 'T',
    'ship_xen_xl_carrier_01_a_macro': 'I',
    'ship_xen_xl_destroyer_01_a_macro': 'K',
    'ship_xen_xl_mothership_01_a_macro': 'M0',
    'ship_xen_xs_pv_01_a_macro': 'Drone 1',
    'ship_xen_xs_pv_02_a_macro': 'Drone 2',
    'ship_xen_xs_pv_03_a_macro': 'Drone 3',
    'ship_xen_xs_pv_04_a_macro': 'Drone 4',
    'ship_yak_m_corvette_01_a_macro': 'Kuraokami',
    'ship_yak_s_fighter_01_a_macro': 'Moreya',
}

# Matches ship macro strings: ship_{faction}_{size}_{role}[_{subtype}]_{variant}_macro
# Groups: (1) faction, (2) size, (3) role, (4) optional subtype (letters only —
# digits mark the start of the variant number and end the named portion).
# Uses [^_]+ to match each token up to the next underscore delimiter.
_SHIP_MACRO_RE = re.compile(
    r'^ship_([^_]+)_([^_]+)_([^_]+)(?:_([a-zA-Z][^_]*))?_\d',
    re.IGNORECASE,
)

# Readable display names for X4 ship role tokens.
# Title-casing alone fails for compound roles like "heavyfighter", so we map
# the known roles explicitly and fall back to .title() for anything else.
_SHIP_ROLE_NAMES = {
    'trans':        'Transport',
    'miner':        'Miner',
    'fighter':      'Fighter',
    'heavyfighter': 'Heavy Fighter',
    'bomber':       'Bomber',
    'corvette':     'Corvette',
    'frigate':      'Frigate',
    'destroyer':    'Destroyer',
    'carrier':      'Carrier',
    'builder':      'Builder',
    'resupplier':   'Resupplier',
    'scout':        'Scout',
    'gunboat':      'Gunboat',
}


def _parse_ship_macro(macro: str) -> str:
    """
    Returns the in-game display name for a ship macro.

    Tries SHIP_NAMES first — this gives the exact name the player sees in the
    UI (e.g. "Sunder (Gas) Vanguard" instead of "ARG M Miner (Liquid)").

    Falls back to regex parsing for any macro not in the table — mod-added
    ships, DLC ships released after the table was generated, etc. The fallback
    produces a readable label from the macro's faction/size/role/subtype tokens.
    """
    name = SHIP_NAMES.get(macro)
    if name:
        return name

    # ── Regex fallback ────────────────────────────────────────────────────────
    m = _SHIP_MACRO_RE.match(macro)
    if not m:
        return macro   # nothing better available

    faction = FACTION_ABBR.get(m.group(1).lower(), m.group(1).upper())
    size    = m.group(2).upper()
    role    = _SHIP_ROLE_NAMES.get(m.group(3).lower(), m.group(3).title())
    subtype = m.group(4)

    label = f"{faction} {size} {role}"
    if subtype:
        label += f" ({subtype.title()})"
    return label


# ─── Language file loader ─────────────────────────────────────────────────────
def load_language(lang_path: pathlib.Path) -> tuple[dict, dict]:
    """
    Parses the language file in a single pass and returns both sector names
    and station type texts needed for name resolution.

    We load three pages in one file read rather than calling separate loaders:
      Page 20004 — sector names. Entries look like "{20003,XXXXXX}(The Void)";
                   we extract the text inside the final parentheses.
      Page 20102 — station/defence type names. These are what the 'basename'
                   attribute on station elements points to via {page,id} refs.
      Page 20215 — factory category names (Agricultural Goods Factory, etc.).
                   Used as a fallback when a station produces multiple wares.

    Returns:
        sector_names  {sector_id: name}   — keyed by the numeric language ID
        texts         {"page:id": text}   — keyed by "{page}:{id}" for fast lookup
    """
    sector_names: dict = {}
    texts:        dict = {}

    if not lang_path.exists():
        print(f"[Warning] Language file not found: {lang_path.name}")
        print("  Names will fall back to raw IDs and macros.")
        print("  Extract 0001-l044.xml from X4's .cat files using X Tools (Steam).")
        return sector_names, texts

    print(f"[Language] Loading from {lang_path.name}...")

    # Pages loaded and what each is used for:
    #   20004 — sector names (resolved from "(Name)" suffix in each entry)
    #   20102 — station/defence type names (what basename {page,id} refs point to)
    #   20201 — individual factory names (what factoryname attrs in wares.xml point to)
    #   20215 — factory category names, e.g. "Agricultural Goods Factory"
    TARGET_PAGES = {'20004', '20102', '20201', '20215'}
    found = set()

    try:
        tree = ET.parse(lang_path)
        for page in tree.getroot().findall('page'):
            pid = page.get('id', '')
            if pid not in TARGET_PAGES:
                continue

            if pid == '20004':
                # Sector name entries: extract the name from "(Name)" at the end.
                for t in page.findall('t'):
                    text = (t.text or '').strip()
                    m = _SECTOR_NAME_RE.search(text)
                    if m:
                        sector_names[t.get('id', '')] = m.group(1)
            else:
                # All other target pages: store raw text as-is for {page,id} lookup.
                for t in page.findall('t'):
                    tid  = t.get('id', '')
                    text = (t.text or '').strip()
                    if text:
                        texts[f"{pid}:{tid}"] = text

            found.add(pid)
            if found == TARGET_PAGES:
                break  # All target pages collected — no need to scan further.

        print(f"[Language] {len(sector_names)} sector names, {len(texts)} station type texts.")
    except Exception as e:
        print(f"[Warning] Could not parse language file: {e}")

    return sector_names, texts


# ─── Wares file loader ───────────────────────────────────────────────────────
def load_ware_factory_names(wares_path: pathlib.Path, texts: dict) -> dict:
    """
    Parses wares.xml and returns {ware_id: factory_name} for every ware that
    has a factoryname attribute.

    Why wares.xml is needed:
    The language file page 20201 contains factory name strings, but gives us no
    way to map a ware ID like "energycells" to a language entry like "20201:704".
    The factoryname attribute in wares.xml provides that link — each <ware> entry
    carries factoryname="{20201,704}", which we resolve against the already-loaded
    texts dict to get "Solar Power Plant".

    This function must be called after load_language() so that page 20201 is
    already present in texts. If the file is missing, an empty dict is returned
    and _type_from_prod_macros() falls back to title-cased ware IDs.
    """
    factory_names: dict = {}

    if not wares_path.exists():
        print(f"[Warning] Wares file not found: {wares_path.name}")
        print("  Factory names will fall back to title-cased ware IDs.")
        return factory_names

    print(f"[Wares] Loading factory names from {wares_path.name}...")
    try:
        tree = ET.parse(wares_path)
        for ware in tree.getroot().findall('ware'):
            ware_id     = ware.get('id', '')
            factoryname = ware.get('factoryname', '')
            if not ware_id or not factoryname:
                continue
            resolved = _resolve_text_ref(factoryname, texts)
            # Only store successfully resolved names — skip any unresolved refs.
            if resolved and not resolved.startswith('{'):
                factory_names[ware_id] = resolved

        print(f"[Wares] Loaded {len(factory_names)} factory names.")
    except Exception as e:
        print(f"[Warning] Could not parse wares file: {e}")

    return factory_names


# ─── Name resolution helpers ──────────────────────────────────────────────────

def _resolve_text_ref(raw: str, texts: dict) -> str:
    """
    Resolves a bare {page,id} language reference to its text string.
    Returns the raw value unchanged if it is not a reference or not found.

    For example: "{20102,5}" → "Trade Station" (if page 20102, entry 5 is loaded).
    """
    m = _TEXT_REF_RE.match(raw)
    if m:
        return texts.get(f"{m.group(1)}:{m.group(2)}", "")
    return raw


def _nameindex_to_roman(nameindex_str: str) -> str:
    """
    Converts a nameindex attribute string like "2" to a Roman numeral like "II".
    X4 uses nameindex to disambiguate multiple auto-named stations of the same type
    in the same sector, e.g. "The Void Trade Station I" and "The Void Trade Station II".
    Returns an empty string for index 0 or out-of-range values.
    """
    try:
        n = int(nameindex_str)
        if 0 < n < len(_ROMAN):
            return _ROMAN[n]
        return str(n) if n > 0 else ''
    except (ValueError, TypeError):
        return ''


def _type_from_prod_macros(prod_macros: list[str], factory_names: dict) -> str:
    """
    Derives a readable station type name from production module macros.

    For single-ware stations, looks up the exact in-game factory name from
    factory_names (sourced from wares.xml via load_ware_factory_names). This
    gives correct names like "Solar Power Plant" for energycells rather than
    the naive "Energy Cells Factory".

    Falls back to title-casing the ware ID for any ware not present in
    factory_names (e.g. mod-added wares or future DLC not in the wares file).

    For stations producing multiple distinct wares, we take the first
    alphabetically as a label — a rough approximation since the full
    priority-based group system (from data/wares.py) is not available here.
    """
    wares: set[str] = set()
    for macro in prod_macros:
        m = _PROD_MACRO_RE.match(macro)
        if m:
            wares.add(m.group(1).lower())

    if not wares:
        return ''
    if len(wares) == 1:
        ware_id = next(iter(wares))
        # Exact in-game name from wares.xml when available.
        return factory_names.get(ware_id) or f"{ware_id.replace('_', ' ').title()} Factory"
    else:
        primary = sorted(wares)[0].replace('_', ' ').title()
        return f"{primary} Complex"


def _resolve_station_name(
    name_attr:     str,
    basename:      str,
    nameindex:     str,
    owner:         str,
    macro:         str,
    prod_macros:   list[str],
    texts:         dict,
    factory_names: dict,
    sector:        str,
) -> str:
    """
    Resolves the display name for a station element.

    Mirrors the logic from station_scanner.py with the same priority order,
    but adapted for streaming (no full subtree available — production macros
    were collected incrementally as child elements streamed past).

    PLAYER STATIONS
      Path A (player-given name): name_attr is a literal string, used verbatim.
                                  No prefix or suffix — the player chose the name.
      Path B (auto-named):        basename resolves via {page,id} lookup.
      Path C (production fallback): derive type from production module macros.
      Format: "{sector} {type} {roman}"  e.g. "The Void Trade Station II"

    NPC STATIONS
      Path B first: basename or name_attr resolves via {page,id} lookup.
      Path C fallback: derive type from production module macros.
      Format: "{ABBR} {type} {roman} ({code})"  e.g. "ARG Trade Station I (ABZ-012)"
      Note: NPC stations never have player-given names, so Path A is skipped.
    """
    is_player = (owner == 'player')

    # ── Path A: Player gave this station a custom name ────────────────────────
    if is_player and name_attr and not _TEXT_REF_RE.match(name_attr):
        return name_attr

    # ── Path B: Resolve the basename / name attribute as a {page,id} ref ─────
    # The game stores the station type as a language reference in basename,
    # e.g. basename="{20102,5}" resolves to "Trade Station" via page 20102.
    type_name = ''
    raw_ref   = name_attr or basename
    if raw_ref:
        resolved = _resolve_text_ref(raw_ref, texts)
        if resolved and not resolved.startswith('{'):
            type_name = resolved

    # ── Path C: Derive type from production module macros ─────────────────────
    # Used when basename is absent or didn't resolve. Extract the ware ID from
    # each prod_{faction}_{ware}_macro child component and construct a label.
    if not type_name and prod_macros:
        type_name = _type_from_prod_macros(prod_macros, factory_names)

    # ── Last resort: macro-based fallback ─────────────────────────────────────
    if not type_name:
        if 'headquarters' in macro.lower():
            type_name = 'Headquarters'
        elif not is_player:
            type_name = 'Station'   # NPC station with no resolvable type
        else:
            return 'Unnamed Station'

    # ── Format the final display name ─────────────────────────────────────────
    roman = _nameindex_to_roman(nameindex)

    if is_player:
        # X4 format for auto-named player stations: "{sector} {type} {roman}"
        parts = [p for p in [sector, type_name, roman] if p]
        return ' '.join(parts)
    else:
        # X4 format for NPC stations: "{ABBR} {type} {roman} ({code})"
        # Code is appended here so the full display name matches X4's UI.
        abbr  = FACTION_ABBR.get(owner.lower(), '')
        parts = [p for p in [abbr, type_name, roman] if p]
        return ' '.join(parts)


# ─── Sector macro → human name ────────────────────────────────────────────────
def macro_to_name(macro: str, sector_names: dict) -> str | None:
    """
    Converts 'cluster_XY_sectorZZ_macro' to a human-readable sector name.

    Derives the language file key from the cluster and sector numbers:
      lang_id = (cluster * 10) concat (sector * 10 + 1, zero-padded to 3 digits)
    e.g. cluster_43, sector001  →  "430" + "011"  →  key "430011"

    Returns None for non-matching macros (e.g. some DLC sectors).
    """
    m = _SECTOR_MACRO_RE.match(macro)
    if not m:
        return None
    cluster_num = int(m.group(1))
    sector_num  = int(m.group(2))
    prefix  = str(cluster_num * 10)
    suffix  = str(sector_num * 10 + 1).zfill(3)
    lang_id = prefix + suffix
    return sector_names.get(lang_id)


# ─── Combined save file scanner ───────────────────────────────────────────────
def scan_save(
    save_path:     pathlib.Path,
    sector_names:  dict,
    texts:         dict,
    factory_names: dict,
) -> tuple[list[dict], list[dict], dict[str, list]]:
    """
    Single-pass scan that collects both sectors and stations from the save file.

    SECTORS
    Detected on <component class="sector"> start events. The macro attribute is
    resolved to a human name immediately and the current_sector variable is
    updated — this is how subsequent station elements know what sector they are in.

    STATIONS
    Detected on <component class in STATION_CLASSES> start events. We save the
    element's attributes to a pending dict but do NOT finalise the name yet,
    because name resolution may require production module macros from children.

    While station_ref is set, any <component class="production"> start events
    have their macro appended to station_prod_macros. When the outer station's
    end event fires (identified by Python object identity, not tag matching),
    _resolve_station_name() is called with all collected data.

    The station_ref identity guard prevents nested sub-components that happen to
    share a station class value from being registered as separate stations.

    SHIP HOMEBASE ASSIGNMENTS
    The homebase station is stored in the ship's DEFAULT ORDER params — not in
    script blackboard variables. Two order types carry it:
        TradeRoutine → <param name="range"    type="component" value="[0xID]"/>
        Middleman    → <param name="supplier" type="component" value="[0xID]"/>

    We maintain a ship_stack: whenever a <component class="ship_*"> opens we
    push a tracking dict onto it. Each dict carries boolean flags (in_orders,
    in_default) that let us navigate the orders → order[@default=1] → param
    path without buffering the ship subtree. When the ship element closes we
    record the homebase (if found) and pop the stack. The stack handles docked
    ships inside carriers — their orders are processed before connections are
    opened, so the innermost ship at the top of the stack is always the right one.

    All elements are cleared on their end events to keep memory usage low.

    Returns:
        sectors       list of sector dicts
        stations      list of station dicts (includes 'id' for cross-referencing)
        homebase_map  {station_hex_id: [ship_macro, ...]}
    """
    seen_sectors:       set[str]              = set()
    sectors:            list[tuple[str, str]] = []
    stations:           list[dict]            = []
    homebase_map:       dict[str, list]       = {}   # station hex id → [ship macro, ...]
    ship_stack:         list                  = []   # stack of ship tracking dicts

    current_sector      = "Unknown Sector"
    station_ref         = None   # reference to the open station element
    station_pending     = None   # attributes captured at station start event
    station_prod_macros = []     # production module macros collected during streaming

    opener = gzip.open if save_path.suffix == '.gz' else open

    print(f"[Scanning] Streaming {save_path.name} ...")

    with opener(save_path, 'rb') as f:
        for event, elem in ET.iterparse(f, events=('start', 'end')):

            if event == 'start':

                if elem.tag == 'component':
                    cls   = elem.get('class', '')
                    macro = elem.get('macro', '')

                    # ── Sector tracking ───────────────────────────────────────
                    if cls == 'sector':
                        resolved = macro_to_name(macro, sector_names)
                        if resolved:
                            current_sector = resolved
                        if macro and macro not in seen_sectors:
                            seen_sectors.add(macro)
                            sectors.append({
                                'name':      resolved or macro,
                                'macro':     macro,
                                'code':      elem.get('code', ''),
                                'owner':     elem.get('owner', ''),
                                'contested': elem.get('contested') == '1',
                            })

                    # ── Station detection ─────────────────────────────────────
                    elif station_ref is None and cls in STATION_CLASSES:
                        # Save the element reference so we can recognise this exact
                        # element's end event later, and capture the attributes now
                        # while they're available on the start event.
                        # 'id' is the station's hex component ID (e.g. "[0x1dc9a]");
                        # we use it to match against $homebase ship assignments.
                        station_ref     = elem
                        station_pending = {
                            'id':        elem.get('id', ''),
                            'name_attr': elem.get('name', ''),
                            'basename':  elem.get('basename', ''),
                            'nameindex': elem.get('nameindex', ''),
                            'owner':     elem.get('owner', ''),
                            'code':      elem.get('code', ''),
                            'cls':       cls,
                            'macro':     macro,
                            'sector':    current_sector,
                        }
                        station_prod_macros = []

                    # ── Production child collection ───────────────────────────
                    # While inside a station, gather production module macros so
                    # that _resolve_station_name() can fall back to them if
                    # basename fails.
                    elif station_ref is not None and cls == 'production':
                        station_prod_macros.append(macro)

                    # ── Ship stack push ───────────────────────────────────────
                    # Push a tracking dict for this ship. in_orders/in_default
                    # are scope flags navigated by the orders/order/param handlers
                    # below; homebase is filled once the matching param is found.
                    elif cls in SHIP_CLASSES:
                        ship_stack.append({
                            'elem':       elem,
                            'macro':      macro,
                            'code':       elem.get('code', ''),
                            'in_orders':  False,
                            'in_default': False,
                            'order_type': '',
                            'homebase':   '',
                        })

                # ── Ship homebase extraction (order params) ───────────────────
                # The homebase is stored in the ship's default order params:
                #   TradeRoutine → <param name="range"    type="component" value="[0xID]"/>
                #   Middleman    → <param name="supplier" type="component" value="[0xID]"/>
                # We walk into orders → default order → params via stack flags so
                # that nested docked ships each track their own scope independently.
                elif elem.tag == 'orders' and ship_stack:
                    ship_stack[-1]['in_orders'] = True

                elif elem.tag == 'order' and ship_stack and ship_stack[-1]['in_orders']:
                    if elem.get('default') == '1':
                        ship_stack[-1]['in_default'] = True
                        ship_stack[-1]['order_type'] = elem.get('order', '')

                elif elem.tag == 'param' and ship_stack and ship_stack[-1]['in_default']:
                    ot = ship_stack[-1]['order_type']
                    if ot == 'TradeRoutine':
                        target = 'range'
                    elif ot == 'Middleman':
                        target = 'supplier'
                    else:
                        target = None
                    if (target
                            and elem.get('name') == target
                            and elem.get('type') == 'component'):
                        val = elem.get('value', '')
                        if val:
                            ship_stack[-1]['homebase'] = val

            # ── Station finalisation ──────────────────────────────────────────
            # When the exact element that opened our station closes, we have seen
            # all of its children and can resolve the display name.
            if event == 'end' and station_ref is not None and elem is station_ref:
                p = station_pending
                display = _resolve_station_name(
                    p['name_attr'],
                    p['basename'],
                    p['nameindex'],
                    p['owner'],
                    p['macro'],
                    station_prod_macros,
                    texts,
                    factory_names,
                    p['sector'],
                )
                stations.append({
                    'id':     p['id'],     # hex component ID for homebase cross-ref
                    'name':   display,
                    'owner':  p['owner'],
                    'code':   p['code'],
                    'cls':    p['cls'],
                    'macro':  p['macro'],
                    'sector': p['sector'],
                })
                station_ref         = None
                station_pending     = None
                station_prod_macros = []

            # ── Ship homebase finalisation ────────────────────────────────────
            if event == 'end' and ship_stack:
                # Unwind the orders/order scope flags as those elements close so
                # that a subsequent docked ship doesn't inherit the wrong state.
                if elem.tag == 'orders':
                    ship_stack[-1]['in_orders'] = False
                elif elem.tag == 'order' and ship_stack[-1]['in_default']:
                    ship_stack[-1]['in_default'] = False
                    ship_stack[-1]['order_type'] = ''
                # When the ship component itself closes, record the homebase (if
                # found) and pop the entry. Identity check ensures we only pop
                # when the EXACT element that opened this entry closes.
                elif elem is ship_stack[-1]['elem']:
                    ship = ship_stack.pop()
                    if ship['homebase']:
                        homebase_map.setdefault(ship['homebase'], []).append(
                            (ship['macro'], ship['code'])
                        )

            # Free every element once it has fully closed. On a large save file
            # this is what keeps RAM manageable — without it the whole tree
            # would accumulate in memory.
            if event == 'end':
                elem.clear()

    return sectors, stations, homebase_map


# ─── Entry point ──────────────────────────────────────────────────────────────
def main():
    start = time.perf_counter()

    if not SAVE_PATH.exists():
        print("[Error] Save file not found.")
        print(f"  Expected: {SAVE_PATH}")
        print("  Place save_001.xml (or save_001.xml.gz) in the project root.")
        input("\nPress Enter to exit...")
        return

    sector_names, texts        = load_language(LANG_PATH)
    factory_names              = load_ware_factory_names(WARES_PATH, texts)
    sectors, stations, hb_map  = scan_save(SAVE_PATH, sector_names, texts, factory_names)
    elapsed                    = time.perf_counter() - start

    sep = '─' * 70

    # ── Sector listing ────────────────────────────────────────────────────────
    if not sectors:
        print("\n  No sectors found in save file.")
        input("\nPress Enter to exit...")
        return

    sectors.sort(key=lambda s: s['name'].lower())

    print(f"\n{sep}")
    print(f"  SECTORS  ({len(sectors)} found)  ·  completed in {elapsed:.2f}s")
    print(sep)
    print(f"  {'Name':<40}  {'Code':<12}  Owner")
    print(f"  {'─' * 40}  {'─' * 12}  {'─' * 20}")
    for s in sectors:
        flag = '  ⚠ CONTESTED' if s['contested'] else ''
        print(f"  {s['name']:<40}  {s['code']:<12}  {s['owner']}{flag}")
    print(sep)

    # ── Stations grouped by sector ────────────────────────────────────────────
    # Group every station under its sector, then display sector headers with
    # the code and owner we now capture, with stations indented beneath each.
    # Only sectors that contain at least one station are shown here — empty
    # sectors are already visible in the full list above.
    by_sector: dict[str, list] = {}
    for st in stations:
        by_sector.setdefault(st['sector'], []).append(st)

    # Keyed lookup so each sector group header can show code/owner/contested.
    sector_meta = {s['name']: s for s in sectors}

    sectors_with_stations = sorted(by_sector.keys(), key=str.lower)

    # Total assigned ships across all known stations.
    # Uses the cross-referenced sum rather than sum(len(v) for v in hb_map.values())
    # so that ships assigned to non-station objects (e.g. carriers) aren't counted.
    total_assigned = sum(len(hb_map.get(st['id'], [])) for st in stations)

    print(f"\n{sep}")
    print(f"  STATIONS BY SECTOR  "
          f"({len(stations)} stations across {len(sectors_with_stations)} sectors"
          f"  ·  {total_assigned} assigned ships)")
    print(sep)

    for sec_name in sectors_with_stations:
        meta      = sector_meta.get(sec_name, {})
        sec_code  = meta.get('code', '')
        sec_owner = meta.get('owner', '')
        flag      = '  ⚠ CONTESTED' if meta.get('contested') else ''
        sec_sts   = sorted(
            by_sector[sec_name],
            key=lambda s: (s['owner'] != 'player', s['owner'], s['name']),
        )
        n     = len(sec_sts)
        label = 'station' if n == 1 else 'stations'

        # Per-sector ship total — sum homebase counts for every station in this sector.
        sec_ships      = sum(len(hb_map.get(st['id'], [])) for st in sec_sts)
        sec_ships_str  = f"  ·  {sec_ships} ships" if sec_ships > 0 else ""

        # Sector header line — code and owner alongside the name.
        parts = [sec_name]
        if sec_code:  parts.append(sec_code)
        if sec_owner: parts.append(sec_owner)
        print(f"\n  ┌─ {'  ·  '.join(parts)}  ({n} {label}{sec_ships_str}){flag}")

        for st in sec_sts:
            owner_tag  = f"[{st['owner']}]" if st['owner'] else ""
            code_str   = f"({st['code']})"  if st['code']  else ""
            # Retrieve the list of ship macros assigned to this station and
            # aggregate them into named groups for the breakdown line.
            macros     = hb_map.get(st['id'], [])
            ship_count = len(macros)
            ship_str   = f"  {ship_count} ships" if ship_count > 0 else ""
            print(f"  │   {owner_tag:<16}  {st['name']:<44}  {code_str}{ship_str}")
            if macros:
                for macro, code in sorted(macros, key=lambda x: _parse_ship_macro(x[0])):
                    label    = _parse_ship_macro(macro)
                    code_str = f"  ({code})" if code else ""
                    print(f"  │       · {label}{code_str}")

    print(f"\n{sep}")

    input("\nPress Enter to exit...")


if __name__ == '__main__':
    main()
