# ─────────────────────────────────────────────────────────────────────────────
#  INDIVIDUAL WARE FACTORY NAMES
#  Generated by tools/generate_station_names.py — do not edit by hand.
#
#  Source files:
#    XML Library/libraries/wares.xml    — factoryname="{20201,N}" per <ware>
#    0001-l044.xml  page 20201          — text for each N
#
#  HOW THIS IS USED:
#    scanner/station_naming.py applies the single/multi-product naming rule:
#      • 1 unique ware produced → WARE_FACTORY_NAMES[ware_id].name  (this dict)
#      • 2+ unique wares        → group name from data/wares.py WARE_GROUPS
#        which resolves to the page 20215 group factory name.
#
#  The .text_id field stores the page 20201 textId so callers can build or
#  match "{20201,N}" references found in save file attributes, e.g.:
#      ref = f"{20201,{WARE_FACTORY_NAMES[ware_id].text_id}}"
#
#  To regenerate after installing DLC or updating the language file:
#      python tools/generate_station_names.py
# ─────────────────────────────────────────────────────────────────────────────

from typing import NamedTuple


class FactoryEntry(NamedTuple):
    """Factory name and its page 20201 text ID from 0001-l044.xml."""
    name:    str  # display string, e.g. "Hull Part Factory"
    text_id: int  # page 20201 text ID — matches "{20201,N}" refs in save files


WARE_FACTORY_NAMES: dict[str, FactoryEntry] = {

    # High Tech Goods (wares.xml group="hightech")
    "advancedcomposites": FactoryEntry("Advanced Composite Factory", 404),  # display: "Advanced Composites" (id 401)
    "engineparts": FactoryEntry("Engine Part Factory", 804),  # display: "Engine Parts" (id 801)
    "hullparts": FactoryEntry("Hull Part Factory", 1204),  # display: "Hull Parts" (id 1201)
    "microchips": FactoryEntry("Microchip Factory", 2204),  # display: "Microchips" (id 2201)
    "plasmaconductors": FactoryEntry("Plasma Conductor Factory", 3004),  # display: "Plasma Conductors" (id 3001)
    "quantumtubes": FactoryEntry("Quantum Tube Factory", 3104),  # display: "Quantum Tubes" (id 3101)
    "scanningarrays": FactoryEntry("Scanning Array Factory", 3304),  # display: "Scanning Arrays" (id 3301)

    # Ship Technology (wares.xml group="shiptech")
    "advancedelectronics": FactoryEntry("Advanced Electronics Factory", 104),  # display: "Advanced Electronics" (id 101)
    "antimatterconverters": FactoryEntry("Antimatter Converter Factory", 304),  # display: "Antimatter Converters" (id 301)
    "claytronics": FactoryEntry("Claytronics Factory", 504),  # display: "Claytronics" (id 501)
    "dronecomponents": FactoryEntry("Drone Component Factory", 604),  # display: "Drone Components" (id 601)
    "fieldcoils": FactoryEntry("Field Coil Factory", 904),  # display: "Field Coils" (id 901)
    "missilecomponents": FactoryEntry("Missile Component Factory", 2304),  # display: "Missile Components" (id 2301)
    "shieldcomponents": FactoryEntry("Shield Component Factory", 3404),  # display: "Shield Components" (id 3401)
    "smartchips": FactoryEntry("Smart Chip Factory", 3704),  # display: "Smart Chips" (id 3701)
    "turretcomponents": FactoryEntry("Turret Component Factory", 4604),  # display: "Turret Components" (id 4601)
    "weaponcomponents": FactoryEntry("Weapon Component Factory", 4804),  # display: "Weapon Components" (id 4801)

    # Refined Goods   (wares.xml group="refined")
    "antimattercells": FactoryEntry("Antimatter Cell Factory", 204),  # display: "Antimatter Cells" (id 201)
    "graphene": FactoryEntry("Graphene Refinery", 1504),  # display: "Graphene" (id 1501)
    "refinedmetals": FactoryEntry("Ore Refinery", 3204),  # display: "Refined Metals" (id 3201)
    "scrapmetal": FactoryEntry("Scrap Processing Factory", 6604),  # display: "Scrap Metal" (id 6601)
    "siliconwafers": FactoryEntry("Silicon Refinery", 3604),  # display: "Silicon Wafers" (id 3601)
    "superfluidcoolant": FactoryEntry("Helium Refinery", 2904),  # display: "Superfluid Coolant" (id 2901)
    "teladianium": FactoryEntry("Teladianium Foundry", 4504),  # display: "Teladianium" (id 4501)

    # Minerals        (wares.xml group="minerals")
    "nividium": FactoryEntry("Nividium Mine", 2404),  # display: "Nividium" (id 2401)
    "ore": FactoryEntry("Ore Mine", 2704),  # display: "Ore" (id 2701)
    "silicon": FactoryEntry("Silicon Mine", 3504),  # display: "Silicon" (id 3501)

    # Gases           (wares.xml group="gases")
    "helium": FactoryEntry("Helium Extractor", 2804),  # display: "Helium" (id 2801)
    "hydrogen": FactoryEntry("Hydrogen Extractor", 1304),  # display: "Hydrogen" (id 1301)
    "methane": FactoryEntry("Methane Extractor", 1604),  # display: "Methane" (id 1601)

    # Pharmaceutical Goods (wares.xml group="pharmaceutical")
    "majadust": FactoryEntry("Maja Dust Factory", 1804),  # display: "Maja Dust" (id 1801)
    "medicalsupplies": FactoryEntry("Medical Supply Factory", 2104),  # display: "Medical Supplies" (id 2101)
    "spacefuel": FactoryEntry("Spacefuel Factory", 4004),  # display: "Spacefuel" (id 4001)
    "spaceweed": FactoryEntry("Spaceweed Farm", 4104),  # display: "Spaceweed" (id 4101)

    # Agricultural Goods   (wares.xml group="agricultural")
    "majasnails": FactoryEntry("Maja Snail Farm", 1904),  # display: "Maja Snails" (id 1901)
    "meat": FactoryEntry("Meat Factory", 2004),  # display: "Meat" (id 2001)
    "sojabeans": FactoryEntry("Soja Bean Farm", 3804),  # display: "Soja Beans" (id 3801)
    "spices": FactoryEntry("Spice Farm", 4204),  # display: "Spices" (id 4201)
    "sunriseflowers": FactoryEntry("Sunrise Flower Farm", 4304),  # display: "Sunrise Flowers" (id 4301)
    "swampplant": FactoryEntry("Swamp Plant Farm", 4404),  # display: "Swamp Plant" (id 4401)
    "wheat": FactoryEntry("Wheat Farm", 4904),  # display: "Wheat" (id 4901)

    # Food            (wares.xml group="food")
    "foodrations": FactoryEntry("Food Ration Factory", 1104),  # display: "Food Rations" (id 1101)
    "nostropoil": FactoryEntry("Nostrop Oil Factory", 2604),  # display: "Nostrop Oil" (id 2601)
    "sojahusk": FactoryEntry("Soja Husk Factory", 3904),  # display: "Soja Husk" (id 3901)

    # Ice             (wares.xml group="ice")
    "ice": FactoryEntry("Ice Mine", 1404),  # display: "Ice" (id 1401)

    # Energy          (wares.xml group="energy")
    "energycells": FactoryEntry("Solar Power Plant", 704),  # display: "Energy Cells" (id 701)

    # Water           (wares.xml group="water")
    "water": FactoryEntry("Ice Refinery", 4704),  # display: "Water" (id 4701)

}
