# ─────────────────────────────────────────────────────────────────────────────
#  WARE PRICES
#  Generated by Generators/generate_ware_prices.py from libraries/wares.xml.
#  Re-run the generator after a game update or DLC install.
#
#  Keys   : ware ID (lowercase, matches keys in data/wares.py WARE_NAMES)
#  Values : {'min': int, 'average': int, 'max': int} — the market price band.
#
#  Used by the station budget calculation to value 'trade wares' (wares a
#  station buys and sells purely to trade) at the MAX market price. Covers
#  every economy ware, including mineables that have no production recipe.
# ─────────────────────────────────────────────────────────────────────────────

WARE_PRICES: dict[str, dict] = {
    'advancedcomposites': {"min": 432, "average": 540, "max": 648},
    'advancedelectronics': {"min": 710, "average": 1014, "max": 1318},
    'antimattercells': {"min": 121, "average": 202, "max": 282},
    'antimatterconverters': {"min": 248, "average": 354, "max": 461},
    'claytronics': {"min": 1734, "average": 2040, "max": 2346},
    'dronecomponents': {"min": 685, "average": 914, "max": 1142},
    'energycells': {"min": 10, "average": 16, "max": 22},
    'engineparts': {"min": 128, "average": 182, "max": 237},
    'fieldcoils': {"min": 247, "average": 412, "max": 576},
    'foodrations': {"min": 12, "average": 21, "max": 29},
    'graphene': {"min": 100, "average": 166, "max": 233},
    'helium': {"min": 37, "average": 44, "max": 51},
    'hullparts': {"min": 146, "average": 209, "max": 272},
    'hydrogen': {"min": 49, "average": 58, "max": 67},
    'ice': {"min": 26, "average": 30, "max": 35},
    'majadust': {"min": 94, "average": 208, "max": 323},
    'majasnails': {"min": 35, "average": 58, "max": 81},
    'meat': {"min": 29, "average": 48, "max": 68},
    'medicalsupplies': {"min": 43, "average": 66, "max": 89},
    'methane': {"min": 41, "average": 48, "max": 55},
    'microchips': {"min": 805, "average": 948, "max": 1090},
    'missilecomponents': {"min": 6, "average": 9, "max": 13},
    'nividium': {"min": 434, "average": 510, "max": 587},
    'nostropoil': {"min": 20, "average": 34, "max": 47},
    'ore': {"min": 43, "average": 50, "max": 58},
    'plasmaconductors': {"min": 769, "average": 1026, "max": 1282},
    'quantumtubes': {"min": 225, "average": 300, "max": 375},
    'refinedmetals': {"min": 89, "average": 148, "max": 207},
    'scanningarrays': {"min": 842, "average": 1053, "max": 1264},
    'scrapmetal': {"min": 318, "average": 375, "max": 431},
    'shieldcomponents': {"min": 113, "average": 188, "max": 264},
    'silicon': {"min": 111, "average": 130, "max": 150},
    'siliconwafers': {"min": 180, "average": 299, "max": 419},
    'smartchips': {"min": 46, "average": 57, "max": 69},
    'sojabeans': {"min": 40, "average": 67, "max": 93},
    'sojahusk': {"min": 19, "average": 32, "max": 45},
    'spacefuel': {"min": 60, "average": 133, "max": 207},
    'spaceweed': {"min": 75, "average": 166, "max": 257},
    'spices': {"min": 12, "average": 20, "max": 28},
    'sunriseflowers': {"min": 48, "average": 80, "max": 112},
    'superfluidcoolant': {"min": 90, "average": 150, "max": 211},
    'swampplant': {"min": 50, "average": 84, "max": 117},
    'teladianium': {"min": 121, "average": 202, "max": 283},
    'turretcomponents': {"min": 164, "average": 273, "max": 383},
    'water': {"min": 32, "average": 53, "max": 74},
    'weaponcomponents': {"min": 171, "average": 285, "max": 399},
    'wheat': {"min": 19, "average": 31, "max": 44},
}
