# Core role: Auto-generated production module catalog (module → {input, output, duration, workforce}).
# Generated by gamefiles/generate_data.py from X4 game files; re-run after updates.
#  then review the git diff for what the patch changed.
# ─────────────────────────────────────────────────────────────────────────────

# Ware id → production recipe (wares.xml <production> nodes).
#   group   — ware category (wares.xml group attribute)
#   time    — production cycle duration in seconds
#   amount  — units produced per cycle
#   methods — method id → {input ware: amount per cycle}.
#             'default' is the standard recipe; faction methods
#             (teladi, split, ...) appear where inputs differ.
#             Empty dict = no inputs needed (energy cells).
PRODUCTION_STATS: dict[str, dict] = {
    'advancedcomposites': {
        "group":   'hightech',
        "time":    300,
        "amount":  54,
        "methods": {
            'default': {'energycells': 50, 'graphene': 80, 'refinedmetals': 80},
            'teladi': {'energycells': 50, 'graphene': 80, 'teladianium': 58},
        },
    },
    'advancedelectronics': {
        "group":   'shiptech',
        "time":    720,
        "amount":  54,
        "methods": {
            'default': {'energycells': 60, 'microchips': 44, 'quantumtubes': 20},
        },
    },
    'antimattercells': {
        "group":   'refined',
        "time":    120,
        "amount":  99,
        "methods": {
            'default': {'energycells': 100, 'hydrogen': 320},
        },
    },
    'antimatterconverters': {
        "group":   'shiptech',
        "time":    300,
        "amount":  133,
        "methods": {
            'default': {'advancedcomposites': 20, 'energycells': 80, 'microchips': 30},
        },
    },
    'bofu': {
        "group":   'food',
        "time":    240,
        "amount":  82,
        "methods": {
            'default': {'bogas': 40, 'energycells': 40, 'plankton': 120},
        },
    },
    'bogas': {
        "group":   'refined',
        "time":    150,
        "amount":  110,
        "methods": {
            'default': {'energycells': 40, 'water': 100},
        },
    },
    'cheltmeat': {
        "group":   'agricultural',
        "time":    450,
        "amount":  209,
        "methods": {
            'default': {'energycells': 50, 'water': 120},
        },
    },
    'claytronics': {
        "group":   'shiptech',
        "time":    900,
        "amount":  108,
        "methods": {
            'default': {'antimattercells': 100, 'energycells': 140, 'microchips': 160, 'quantumtubes': 100},
            'recycling': {'energycells': 12000, 'scrapmetal': 300},
        },
    },
    'computronicsubstrate': {
        "group":   'hightech',
        "time":    600,
        "amount":  98,
        "methods": {
            'default': {'energycells': 4000, 'hydrogen': 2000, 'ore': 3000, 'silicon': 3000},
            'recycling': {'energycells': 12500, 'scrapmetal': 1000},
        },
    },
    'dronecomponents': {
        "group":   'shiptech',
        "time":    1200,
        "amount":  105,
        "methods": {
            'default': {'energycells': 60, 'engineparts': 20, 'hullparts': 20, 'microchips': 20, 'scanningarrays': 40},
        },
    },
    'energycells': {
        "group":   'energy',
        "time":    60,
        "amount":  175,
        "methods": {
            'default': {},
            'terran': {},
        },
    },
    'engineparts': {
        "group":   'hightech',
        "time":    900,
        "amount":  208,
        "methods": {
            'default': {'antimattercells': 80, 'energycells': 60, 'refinedmetals': 96},
            'teladi': {'antimattercells': 80, 'energycells': 60, 'teladianium': 70},
        },
    },
    'fieldcoils': {
        "group":   'shiptech',
        "time":    600,
        "amount":  175,
        "methods": {
            'default': {'energycells': 60, 'plasmaconductors': 40, 'quantumtubes': 43},
        },
    },
    'foodrations': {
        "group":   'food',
        "time":    240,
        "amount":  460,
        "methods": {
            'default': {'energycells': 100, 'meat': 40, 'spices': 40, 'wheat': 40},
        },
    },
    'graphene': {
        "group":   'refined',
        "time":    240,
        "amount":  96,
        "methods": {
            'default': {'energycells': 80, 'methane': 320},
        },
    },
    'hullparts': {
        "group":   'hightech',
        "time":    900,
        "amount":  294,
        "methods": {
            'default': {'energycells': 80, 'graphene': 40, 'refinedmetals': 280},
            'recycling': {'energycells': 3500, 'scrapmetal': 75},
            'teladi': {'energycells': 80, 'graphene': 40, 'teladianium': 204},
        },
    },
    'khaakalloy': {
        "group":   'hightech',
        "time":    300,
        "amount":  100,
        "methods": {
            'recycling': {'energycells': 6000, 'khaakscrapmetal': 300, 'nividium': 200},
        },
    },
    'khaakscrapmetal': {
        "group":   'refined',
        "time":    60,
        "amount":  1,
        "methods": {
            'processing': {'energycells': 10, 'rawkhaakscrap': 1},
        },
    },
    'majadust': {
        "group":   'pharmaceutical',
        "time":    600,
        "amount":  64,
        "methods": {
            'default': {'energycells': 40, 'majasnails': 120, 'spices': 60},
        },
    },
    'majasnails': {
        "group":   'agricultural',
        "time":    450,
        "amount":  146,
        "methods": {
            'default': {'energycells': 40, 'water': 100},
        },
    },
    'meat': {
        "group":   'agricultural',
        "time":    450,
        "amount":  290,
        "methods": {
            'default': {'energycells': 80, 'water': 100},
        },
    },
    'medicalsupplies': {
        "group":   'pharmaceutical',
        "time":    300,
        "amount":  208,
        "methods": {
            'default': {'energycells': 100, 'spices': 40, 'water': 60, 'wheat': 30},
            'paranid': {'energycells': 100, 'sojabeans': 10, 'spices': 40, 'water': 60},
            'teladi': {'energycells': 100, 'spices': 40, 'sunriseflowers': 12, 'water': 60},
            'boron': {'energycells': 100, 'plankton': 95, 'water': 60},
            'split': {'energycells': 100, 'scruffinfruits': 30, 'spices': 60, 'water': 60},
            'terran': {'energycells': 100, 'ice': 50, 'proteinpaste': 24},
        },
    },
    'metallicmicrolattice': {
        "group":   'hightech',
        "time":    180,
        "amount":  190,
        "methods": {
            'default': {'energycells': 50, 'helium': 130, 'ore': 50},
        },
    },
    'microchips': {
        "group":   'hightech',
        "time":    600,
        "amount":  72,
        "methods": {
            'default': {'energycells': 50, 'siliconwafers': 200},
        },
    },
    'missilecomponents': {
        "group":   'shiptech',
        "time":    900,
        "amount":  281,
        "methods": {
            'default': {'advancedcomposites': 2, 'energycells': 20, 'hullparts': 2},
        },
    },
    'nividiumgems': {
        "group":   '',
        "time":    300,
        "amount":  57,
        "methods": {
            'default': {'energycells': 90, 'nividium': 120},
        },
    },
    'nostropoil': {
        "group":   'food',
        "time":    300,
        "amount":  500,
        "methods": {
            'default': {'energycells': 100, 'spices': 40, 'sunriseflowers': 40, 'water': 60},
        },
    },
    'plankton': {
        "group":   'agricultural',
        "time":    400,
        "amount":  275,
        "methods": {
            'default': {'energycells': 20, 'water': 50},
        },
    },
    'plasmaconductors': {
        "group":   'hightech',
        "time":    900,
        "amount":  44,
        "methods": {
            'default': {'energycells': 60, 'graphene': 96, 'superfluidcoolant': 140},
        },
    },
    'proteinpaste': {
        "group":   'agricultural',
        "time":    300,
        "amount":  219,
        "methods": {
            'default': {'energycells': 80, 'ice': 80, 'methane': 200},
        },
    },
    'quantumtubes': {
        "group":   'hightech',
        "time":    720,
        "amount":  94,
        "methods": {
            'default': {'energycells': 40, 'graphene': 116, 'superfluidcoolant': 30},
        },
    },
    'refinedmetals': {
        "group":   'refined',
        "time":    150,
        "amount":  88,
        "methods": {
            'default': {'energycells': 90, 'ore': 240},
        },
    },
    'scanningarrays': {
        "group":   'hightech',
        "time":    600,
        "amount":  36,
        "methods": {
            'default': {'energycells': 60, 'refinedmetals': 100, 'siliconwafers': 60},
            'teladi': {'energycells': 60, 'siliconwafers': 60, 'teladianium': 73},
        },
    },
    'scrapmetal': {
        "group":   'refined',
        "time":    60,
        "amount":  1,
        "methods": {
            'processing': {'energycells': 10, 'rawscrap': 1},
        },
    },
    'scruffinfruits': {
        "group":   'agricultural',
        "time":    300,
        "amount":  255,
        "methods": {
            'default': {'energycells': 30, 'water': 80},
        },
    },
    'shieldcomponents': {
        "group":   'shiptech',
        "time":    1200,
        "amount":  193,
        "methods": {
            'default': {'energycells': 70, 'plasmaconductors': 20, 'quantumtubes': 20},
        },
    },
    'siliconcarbide': {
        "group":   'hightech',
        "time":    300,
        "amount":  48,
        "methods": {
            'default': {'energycells': 200, 'metallicmicrolattice': 2, 'methane': 400, 'silicon': 300},
            'recycling': {'energycells': 4000, 'scrapmetal': 250},
        },
    },
    'siliconwafers': {
        "group":   'refined',
        "time":    180,
        "amount":  107,
        "methods": {
            'default': {'energycells': 90, 'silicon': 240},
        },
    },
    'smartchips': {
        "group":   'shiptech',
        "time":    600,
        "amount":  143,
        "methods": {
            'default': {'energycells': 50, 'siliconwafers': 20},
        },
    },
    'sojabeans': {
        "group":   'agricultural',
        "time":    300,
        "amount":  104,
        "methods": {
            'default': {'energycells': 30, 'water': 80},
        },
    },
    'sojahusk': {
        "group":   'food',
        "time":    300,
        "amount":  350,
        "methods": {
            'default': {'energycells': 80, 'majasnails': 50, 'sojabeans': 40, 'spices': 20},
        },
    },
    'spacefuel': {
        "group":   'pharmaceutical',
        "time":    480,
        "amount":  98,
        "methods": {
            'default': {'energycells': 40, 'water': 100, 'wheat': 80},
        },
    },
    'spaceweed': {
        "group":   'pharmaceutical',
        "time":    600,
        "amount":  183,
        "methods": {
            'default': {'energycells': 140, 'spices': 40, 'swampplant': 120},
        },
    },
    'spices': {
        "group":   'agricultural',
        "time":    600,
        "amount":  500,
        "methods": {
            'default': {'energycells': 40, 'water': 80},
        },
    },
    'stimulants': {
        "group":   'pharmaceutical',
        "time":    300,
        "amount":  98,
        "methods": {
            'default': {'energycells': 80, 'helium': 400, 'silicon': 20},
        },
    },
    'sunriseflowers': {
        "group":   'agricultural',
        "time":    300,
        "amount":  100,
        "methods": {
            'default': {'energycells': 30, 'water': 80},
        },
    },
    'superfluidcoolant': {
        "group":   'refined',
        "time":    240,
        "amount":  95,
        "methods": {
            'default': {'energycells': 60, 'helium': 320},
        },
    },
    'swampplant': {
        "group":   'agricultural',
        "time":    450,
        "amount":  120,
        "methods": {
            'default': {'energycells': 40, 'water': 100},
        },
    },
    'teladianium': {
        "group":   'refined',
        "time":    120,
        "amount":  70,
        "methods": {
            'default': {'energycells': 45, 'ore': 280},
        },
    },
    'terranmre': {
        "group":   'food',
        "time":    240,
        "amount":  175,
        "methods": {
            'default': {'energycells': 60, 'proteinpaste': 60},
        },
    },
    'turretcomponents': {
        "group":   'shiptech',
        "time":    1800,
        "amount":  170,
        "methods": {
            'default': {'energycells': 60, 'microchips': 20, 'quantumtubes': 20, 'scanningarrays': 10},
        },
    },
    'water': {
        "group":   'water',
        "time":    120,
        "amount":  193,
        "methods": {
            'default': {'energycells': 60, 'ice': 320},
        },
    },
    'weaponcomponents': {
        "group":   'shiptech',
        "time":    1800,
        "amount":  170,
        "methods": {
            'default': {'energycells': 60, 'hullparts': 20, 'plasmaconductors': 30},
        },
    },
    'wheat': {
        "group":   'agricultural',
        "time":    300,
        "amount":  310,
        "methods": {
            'default': {'energycells': 60, 'water': 80},
        },
    },
}
