# ─────────────────────────────────────────────────────────────────────────────
#  AUTO-GENERATED by gamefiles/generate_data.py — DO NOT EDIT BY HAND.
#  Source: libraries/wares.xml (+ DLC diffs) read directly from the X4
#  install's .cat archives. Re-run after a game update or DLC install:
#      python gamefiles/generate_data.py
#  then review the git diff for what the patch changed.
# ─────────────────────────────────────────────────────────────────────────────

# Sector macro → sunlight multiplier (libraries/mapdefaults.xml + DLC).
# Keys are lowercase sector macros, matching what the save-file scanner reads.
# Sunlight affects energy cell production only:
#   effective_output = base_output * sunlight
# 1.0 = standard output; above 1.0 = more cells per cycle.
# Sectors absent from this table fall back to 1.0 in the scanner.
SECTOR_SUNLIGHT: dict[str, float] = {
    "cluster_01_sector001_macro":  1.23,  # Grand Exchange I
    "cluster_01_sector002_macro":  1.35,  # Grand Exchange III
    "cluster_01_sector003_macro":  1.29,  # Grand Exchange IV
    "cluster_02_sector001_macro":  0.9,  # Eighteen Billion
    "cluster_03_sector001_macro":  1.15,  # Memory of Profit IX
    "cluster_04_sector001_macro":  0.82,  # Nopileos' Fortune II
    "cluster_04_sector002_macro":  0.78,  # Nopileos' Fortune VI
    "cluster_05_sector001_macro":  1.43,  # Path to Profit
    "cluster_06_sector001_macro":  1.16,  # Black Hole Sun IV
    "cluster_06_sector002_macro":  1.19,  # Black Hole Sun V
    "cluster_07_sector001_macro":  3.67,  # The Reach
    "cluster_08_sector001_macro":  0.98,  # Silent Witness I
    "cluster_09_sector001_macro":  2.04,  # Bright Promise
    "cluster_100_sector001_macro": 0.13,  # Asteroid Belt
    "cluster_101_sector001_macro": 0.44,  # Mars
    "cluster_102_sector001_macro": 1.89,  # Venus
    "cluster_104_sector001_macro": 1.0,  # Earth
    "cluster_104_sector002_macro": 1.05,  # The Moon
    "cluster_106_sector001_macro": 7.14,  # Mercury
    "cluster_107_sector001_macro": 0.1,  # Jupiter
    "cluster_108_sector001_macro": 0.08,  # Saturn Alpha
    "cluster_108_sector002_macro": 0.08,  # Titan
    "cluster_108_sector003_macro": 0.08,  # Saturn Beta
    "cluster_109_sector001_macro": 0.07,  # Uranus
    "cluster_10_sector001_macro":  1.63,  # Unholy Retribution
    "cluster_110_sector001_macro": 0.06,  # Neptune
    "cluster_111_sector001_macro": 0.05,  # Pluto
    "cluster_112_sector001_macro": 1.17,  # Savage Spur I
    "cluster_112_sector002_macro": 1.25,  # Savage Spur II
    "cluster_113_sector001_macro": 1.87,  # Segaris
    "cluster_114_sector001_macro": 2.08,  # Gaian Prophecy
    "cluster_115_sector001_macro": 1.22,  # Brennan's Triumph
    "cluster_116_sector001_macro": 0.02,  # Oort Cloud
    "cluster_11_sector001_macro":  1.94,  # Pontifex's Claim
    "cluster_12_sector001_macro":  0.71,  # True Sight
    "cluster_13_sector001_macro":  0.59,  # Second Contact II Flashpoint
    "cluster_14_sector001_macro":  1.0,  # Argon Prime
    "cluster_15_sector001_macro":  1.33,  # Ianamus Zura IV
    "cluster_15_sector002_macro":  1.15,  # Ianamus Zura VII
    "cluster_16_sector001_macro":  2.01,  # Matrix #451
    "cluster_17_sector001_macro":  1.0,  # Matrix #9
    "cluster_18_sector001_macro":  1.33,  # Trinity Sanctum III
    "cluster_19_sector001_macro":  1.16,  # Hewa's Twin I
    "cluster_19_sector002_macro":  1.02,  # Hewa's Twin II
    "cluster_20_sector001_macro":  0.83,  # Company Regard
    "cluster_21_sector001_macro":  1.26,  # Scale Plate Green I
    "cluster_21_sector002_macro":  1.15,  # Scale Plate Green VII
    "cluster_22_sector001_macro":  1.36,  # Pious Mists II
    "cluster_23_sector001_macro":  0.71,  # Sacred Relic
    "cluster_24_sector001_macro":  2.08,  # Holy Vision
    "cluster_25_sector001_macro":  1.77,  # Faulty Logic I
    "cluster_25_sector002_macro":  1.47,  # Faulty Logic VII
    "cluster_26_sector001_macro":  1.09,  # Atiya's Misfortune I
    "cluster_26_sector002_macro":  0.93,  # Atiya's Misfortune III
    "cluster_27_sector001_macro":  1.64,  # The Void
    "cluster_28_sector001_macro":  1.26,  # Antigone Memorial
    "cluster_29_sector001_macro":  1.12,  # Hatikvah's Choice I
    "cluster_29_sector002_macro":  0.91,  # Hatikvah's Choice III
    "cluster_30_sector001_macro":  0.76,  # Morning Star III
    "cluster_31_sector001_macro":  1.81,  # Heretic's End
    "cluster_32_sector001_macro":  1.42,  # Tharka's Cascade XV
    "cluster_32_sector002_macro":  1.29,  # Tharka's Cascade XVII
    "cluster_33_sector001_macro":  2.39,  # Matrix #79B
    "cluster_34_sector001_macro":  0.79,  # Profit Center Alpha
    "cluster_35_sector001_macro":  1.0,  # Lasting Vengeance
    "cluster_36_sector001_macro":  0.88,  # Cardinal's Redress
    "cluster_37_sector001_macro":  0.89,  # Pious Mists IV
    "cluster_38_sector001_macro":  1.18,  # Pious Mists XI
    "cluster_39_sector001_macro":  1.06,  # Memory of Profit X
    "cluster_400_sector001_macro": 1.3,  # Wretched Skies IV Family Valka
    "cluster_401_sector001_macro": 0.71,  # Family Zhin
    "cluster_402_sector001_macro": 2.39,  # Family Kritt
    "cluster_403_sector001_macro": 1.23,  # Wretched Skies V Family Phi
    "cluster_404_sector001_macro": 1.42,  # Zyarth's Dominion I
    "cluster_405_sector001_macro": 2.1,  # Zyarth's Dominion IV
    "cluster_406_sector001_macro": 1.51,  # Zyarth's Dominion X
    "cluster_407_sector001_macro": 0.89,  # Family Tkr
    "cluster_408_sector001_macro": 0.59,  # Thuruk's Demise III
    "cluster_408_sector002_macro": 0.71,  # Thuruk's Demise II First Impact
    "cluster_409_sector001_macro": 1.09,  # Tharka's Ravine IV Tharka's Fall
    "cluster_40_sector001_macro":  0.55,  # Second Contact VII
    "cluster_410_sector001_macro": 1.17,  # Tharka's Ravine VIII
    "cluster_411_sector001_macro": 2.45,  # Heart of Acrimony II
    "cluster_412_sector001_macro": 1.26,  # Tharka's Ravine XVI
    "cluster_413_sector001_macro": 1.31,  # Tharka's Ravine XXIV
    "cluster_414_sector001_macro": 1.63,  # Rhy's Defiance
    "cluster_415_sector001_macro": 0.77,  # Matrix #598
    "cluster_416_sector001_macro": 0.83,  # Guiding Star V
    "cluster_416_sector002_macro": 0.71,  # Guiding Star VII
    "cluster_417_sector001_macro": 1.18,  # Eleventh Hour
    "cluster_418_sector001_macro": 0.85,  # Family Nhuut
    "cluster_419_sector001_macro": 0.88,  # Open Market
    "cluster_41_sector001_macro":  0.47,  # Second Contact XI
    "cluster_420_sector001_macro": 1.33,  # Two Grand
    "cluster_421_sector001_macro": 0.81,  # Fires of Defeat
    "cluster_422_sector001_macro": 1.08,  # Wretched Skies X
    "cluster_423_sector001_macro": 0.42,  # Litany of Fury IX
    "cluster_423_sector002_macro": 0.32,  # Litany of Fury XII
    "cluster_424_sector001_macro": 0.71,  # Emperor's Pride IV
    "cluster_424_sector002_macro": 0.65,  # Emperor's Pride VI
    "cluster_425_sector001_macro": 0.64,  # Heart of Acrimony I The Boneyard
    "cluster_42_sector001_macro":  0.86,  # Hewa's Twin III
    "cluster_42_sector002_macro":  0.91,  # Hewa's Twin IV The Cove
    "cluster_43_sector001_macro":  0.82,  # Hewa's Twin V
    "cluster_44_sector001_macro":  1.18,  # Silent Witness XI
    "cluster_45_sector001_macro":  1.47,  # Silent Witness XII
    "cluster_46_sector001_macro":  0.65,  # Morning Star IV
    "cluster_47_sector001_macro":  1.06,  # Trinity Sanctum VII
    "cluster_48_sector001_macro":  0.93,  # Getsu Fune
    "cluster_49_sector001_macro":  1.72,  # Frontier Edge
    "cluster_500_sector001_macro": 13.9,  # Avarice I
    "cluster_500_sector002_macro": 13.9,  # Avarice V Dead End
    "cluster_500_sector003_macro": 13.9,  # Avarice IV
    "cluster_501_sector001_macro": 0.2,  # Windfall I Union Summit
    "cluster_502_sector001_macro": 0.16,  # Windfall III The Hoard
    "cluster_503_sector001_macro": 0.11,  # Windfall IV Aurora's Dream
    "cluster_504_sector001_macro": 0.05,  # Unknown System
    "cluster_50_sector001_macro":  1.41,  # Turquoise Sea IX
    "cluster_50_sector002_macro":  1.28,  # Turquoise Sea X
    "cluster_601_sector001_macro": 0.41,  # Watchful Gaze
    "cluster_602_sector001_macro": 0.83,  # Barren Shores
    "cluster_603_sector001_macro": 1.28,  # Great Reef
    "cluster_604_sector001_macro": 0.12,  # Ocean of Fantasy
    "cluster_605_sector001_macro": 1.74,  # Sanctuary of Darkness
    "cluster_606_sector001_macro": 1.18,  # Kingdom End I
    "cluster_606_sector002_macro": 1.18,  # Reflected Stars
    "cluster_606_sector003_macro": 1.18,  # Towering Wave
    "cluster_607_sector001_macro": 0.15,  # Rolk's Demise
    "cluster_608_sector001_macro": 0.41,  # Atreus' Clouds
    "cluster_609_sector001_macro": 2.71,  # Menelaus' Oasis
    "cluster_701_sector001_macro": 1.18,  # Mitsuno's Revelation
    "cluster_702_sector001_macro": 1.11,  # Mitsuno's Defiance
    "cluster_703_sector001_macro": 1.06,  # Mitsuno's Sacrifice
    "cluster_704_sector001_macro": 0.71,  # President's End
    "cluster_705_sector001_macro": 1.63,  # Nopileos' Memorial
    "cluster_706_sector001_macro": 0.88,  # Hatikvah's Faith
    "cluster_708_sector001_macro": 4.08,  # Matrix #101
    "cluster_709_sector001_macro": 1.24,  # Cardinal's Domain
    "cluster_710_sector001_macro": 0.93,  # Moo-Kye's Revenge
    "cluster_711_sector001_macro": 0.53,  # Mi Ton's Refuge
    "cluster_712_sector001_macro": 0.02,  # Loomanckstrat's Legacy
    "cluster_713_sector001_macro": 0.82,  # CEO's Doubt
    "cluster_714_sector001_macro": 2.21,  # Freedom's Reach
    "cluster_715_sector001_macro": 1.41,  # Mists of Artemis
    "cluster_720_sector001_macro": 1.34,  # Ore Belt
    "cluster_721_sector001_macro": 0.71,  # Adventure's Promise
    "cluster_722_sector001_macro": 0.89,  # Sanctum Verge
    "cluster_723_sector001_macro": 1.66,  # Tempting Fumes
    "cluster_724_sector001_macro": 1.42,  # Circle of Deceit
    "cluster_725_sector001_macro": 0.83,  # Void of Opportunity
}
