# Core role: Auto-generated sector metadata (macro → sunlight / display name / mineable resources).
# Generated by gamefiles/generate_data.py from X4 game files; re-run after updates.
# Keys are lowercase sector macros, matching what the save-file scanner reads.
#
# SECTOR_SUNLIGHT — sunlight multiplier. Affects energy cell production only:
#   effective_output = base_output * sunlight
# 1.0 = standard output; above 1.0 = more cells per cycle.
# Sectors absent from this table fall back to 1.0 in the scanner.
#
# SECTOR_NAMES — English display name (t-file page 20004). Lets the UI
# label sectors before any save has been scanned.
#
# SECTOR_RESOURCES — mineable wares as (ware_id, yield_level), richest
# first. Authored sector defaults; a save's actual fields can drift
# slightly, so scan data still wins whenever a scan is loaded.
#
# SECTOR_OWNERS — game-start owner faction id, derived from god.xml
# station seeding (defence stations are the claim markers). Lets the
# universe map colour sectors before any scan; a real save's ownership
# can differ once factions start losing/taking sectors, so scan data
# wins whenever a scan is loaded. Unclaimed sectors are absent.
SECTOR_SUNLIGHT: dict[str, float] = {
    "cluster_01_sector001_macro":  1.23,  # Grand Exchange I
    "cluster_01_sector002_macro":  1.35,  # Grand Exchange III
    "cluster_01_sector003_macro":  1.29,  # Grand Exchange IV
    "cluster_02_sector001_macro":  0.9,  # Eighteen Billion
    "cluster_03_sector001_macro":  1.15,  # Memory of Profit IX
    "cluster_04_sector001_macro":  0.82,  # Nopileos' Fortune II
    "cluster_04_sector002_macro":  0.78,  # Nopileos' Fortune VI
    "cluster_05_sector001_macro":  1.43,  # Path to Profit
    "cluster_06_sector001_macro":  1.16,  # Black Hole Sun IV
    "cluster_06_sector002_macro":  1.19,  # Black Hole Sun V
    "cluster_07_sector001_macro":  3.67,  # The Reach
    "cluster_08_sector001_macro":  0.98,  # Silent Witness I
    "cluster_09_sector001_macro":  2.04,  # Bright Promise
    "cluster_100_sector001_macro": 0.13,  # Asteroid Belt
    "cluster_101_sector001_macro": 0.44,  # Mars
    "cluster_102_sector001_macro": 1.89,  # Venus
    "cluster_104_sector001_macro": 1.0,  # Earth
    "cluster_104_sector002_macro": 1.05,  # The Moon
    "cluster_106_sector001_macro": 7.14,  # Mercury
    "cluster_107_sector001_macro": 0.1,  # Jupiter
    "cluster_108_sector001_macro": 0.08,  # Saturn Alpha
    "cluster_108_sector002_macro": 0.08,  # Titan
    "cluster_108_sector003_macro": 0.08,  # Saturn Beta
    "cluster_109_sector001_macro": 0.07,  # Uranus
    "cluster_10_sector001_macro":  1.63,  # Unholy Retribution
    "cluster_110_sector001_macro": 0.06,  # Neptune
    "cluster_111_sector001_macro": 0.05,  # Pluto
    "cluster_112_sector001_macro": 1.17,  # Savage Spur I
    "cluster_112_sector002_macro": 1.25,  # Savage Spur II
    "cluster_113_sector001_macro": 1.87,  # Segaris
    "cluster_114_sector001_macro": 2.08,  # Gaian Prophecy
    "cluster_115_sector001_macro": 1.22,  # Brennan's Triumph
    "cluster_116_sector001_macro": 0.02,  # Oort Cloud
    "cluster_11_sector001_macro":  1.94,  # Pontifex's Claim
    "cluster_12_sector001_macro":  0.71,  # True Sight
    "cluster_13_sector001_macro":  0.59,  # Second Contact II Flashpoint
    "cluster_14_sector001_macro":  1.0,  # Argon Prime
    "cluster_15_sector001_macro":  1.33,  # Ianamus Zura IV
    "cluster_15_sector002_macro":  1.15,  # Ianamus Zura VII
    "cluster_16_sector001_macro":  2.01,  # Matrix #451
    "cluster_17_sector001_macro":  1.0,  # Matrix #9
    "cluster_18_sector001_macro":  1.33,  # Trinity Sanctum III
    "cluster_19_sector001_macro":  1.16,  # Hewa's Twin I
    "cluster_19_sector002_macro":  1.02,  # Hewa's Twin II
    "cluster_20_sector001_macro":  0.83,  # Company Regard
    "cluster_21_sector001_macro":  1.26,  # Scale Plate Green I
    "cluster_21_sector002_macro":  1.15,  # Scale Plate Green VII
    "cluster_22_sector001_macro":  1.36,  # Pious Mists II
    "cluster_23_sector001_macro":  0.71,  # Sacred Relic
    "cluster_24_sector001_macro":  2.08,  # Holy Vision
    "cluster_25_sector001_macro":  1.77,  # Faulty Logic I
    "cluster_25_sector002_macro":  1.47,  # Faulty Logic VII
    "cluster_26_sector001_macro":  1.09,  # Atiya's Misfortune I
    "cluster_26_sector002_macro":  0.93,  # Atiya's Misfortune III
    "cluster_27_sector001_macro":  1.64,  # The Void
    "cluster_28_sector001_macro":  1.26,  # Antigone Memorial
    "cluster_29_sector001_macro":  1.12,  # Hatikvah's Choice I
    "cluster_29_sector002_macro":  0.91,  # Hatikvah's Choice III
    "cluster_30_sector001_macro":  0.76,  # Morning Star III
    "cluster_31_sector001_macro":  1.81,  # Heretic's End
    "cluster_32_sector001_macro":  1.42,  # Tharka's Cascade XV
    "cluster_32_sector002_macro":  1.29,  # Tharka's Cascade XVII
    "cluster_33_sector001_macro":  2.39,  # Matrix #79B
    "cluster_34_sector001_macro":  0.79,  # Profit Center Alpha
    "cluster_35_sector001_macro":  1.0,  # Lasting Vengeance
    "cluster_36_sector001_macro":  0.88,  # Cardinal's Redress
    "cluster_37_sector001_macro":  0.89,  # Pious Mists IV
    "cluster_38_sector001_macro":  1.18,  # Pious Mists XI
    "cluster_39_sector001_macro":  1.06,  # Memory of Profit X
    "cluster_400_sector001_macro": 1.3,  # Wretched Skies IV Family Valka
    "cluster_401_sector001_macro": 0.71,  # Family Zhin
    "cluster_402_sector001_macro": 2.39,  # Family Kritt
    "cluster_403_sector001_macro": 1.23,  # Wretched Skies V Family Phi
    "cluster_404_sector001_macro": 1.42,  # Zyarth's Dominion I
    "cluster_405_sector001_macro": 2.1,  # Zyarth's Dominion IV
    "cluster_406_sector001_macro": 1.51,  # Zyarth's Dominion X
    "cluster_407_sector001_macro": 0.89,  # Family Tkr
    "cluster_408_sector001_macro": 0.59,  # Thuruk's Demise III
    "cluster_408_sector002_macro": 0.71,  # Thuruk's Demise II First Impact
    "cluster_409_sector001_macro": 1.09,  # Tharka's Ravine IV Tharka's Fall
    "cluster_40_sector001_macro":  0.55,  # Second Contact VII
    "cluster_410_sector001_macro": 1.17,  # Tharka's Ravine VIII
    "cluster_411_sector001_macro": 2.45,  # Heart of Acrimony II
    "cluster_412_sector001_macro": 1.26,  # Tharka's Ravine XVI
    "cluster_413_sector001_macro": 1.31,  # Tharka's Ravine XXIV
    "cluster_414_sector001_macro": 1.63,  # Rhy's Defiance
    "cluster_415_sector001_macro": 0.77,  # Matrix #598
    "cluster_416_sector001_macro": 0.83,  # Guiding Star V
    "cluster_416_sector002_macro": 0.71,  # Guiding Star VII
    "cluster_417_sector001_macro": 1.18,  # Eleventh Hour
    "cluster_418_sector001_macro": 0.85,  # Family Nhuut
    "cluster_419_sector001_macro": 0.88,  # Open Market
    "cluster_41_sector001_macro":  0.47,  # Second Contact XI
    "cluster_420_sector001_macro": 1.33,  # Two Grand
    "cluster_421_sector001_macro": 0.81,  # Fires of Defeat
    "cluster_422_sector001_macro": 1.08,  # Wretched Skies X
    "cluster_423_sector001_macro": 0.42,  # Litany of Fury IX
    "cluster_423_sector002_macro": 0.32,  # Litany of Fury XII
    "cluster_424_sector001_macro": 0.71,  # Emperor's Pride IV
    "cluster_424_sector002_macro": 0.65,  # Emperor's Pride VI
    "cluster_425_sector001_macro": 0.64,  # Heart of Acrimony I The Boneyard
    "cluster_42_sector001_macro":  0.86,  # Hewa's Twin III
    "cluster_42_sector002_macro":  0.91,  # Hewa's Twin IV The Cove
    "cluster_43_sector001_macro":  0.82,  # Hewa's Twin V
    "cluster_44_sector001_macro":  1.18,  # Silent Witness XI
    "cluster_45_sector001_macro":  1.47,  # Silent Witness XII
    "cluster_46_sector001_macro":  0.65,  # Morning Star IV
    "cluster_47_sector001_macro":  1.06,  # Trinity Sanctum VII
    "cluster_48_sector001_macro":  0.93,  # Getsu Fune
    "cluster_49_sector001_macro":  1.72,  # Frontier Edge
    "cluster_500_sector001_macro": 13.9,  # Avarice I
    "cluster_500_sector002_macro": 13.9,  # Avarice V Dead End
    "cluster_500_sector003_macro": 13.9,  # Avarice IV
    "cluster_501_sector001_macro": 0.2,  # Windfall I Union Summit
    "cluster_502_sector001_macro": 0.16,  # Windfall III The Hoard
    "cluster_503_sector001_macro": 0.11,  # Windfall IV Aurora's Dream
    "cluster_504_sector001_macro": 0.05,  # Unknown System
    "cluster_50_sector001_macro":  1.41,  # Turquoise Sea IX
    "cluster_50_sector002_macro":  1.28,  # Turquoise Sea X
    "cluster_601_sector001_macro": 0.41,  # Watchful Gaze
    "cluster_602_sector001_macro": 0.83,  # Barren Shores
    "cluster_603_sector001_macro": 1.28,  # Great Reef
    "cluster_604_sector001_macro": 0.12,  # Ocean of Fantasy
    "cluster_605_sector001_macro": 1.74,  # Sanctuary of Darkness
    "cluster_606_sector001_macro": 1.18,  # Kingdom End I
    "cluster_606_sector002_macro": 1.18,  # Reflected Stars
    "cluster_606_sector003_macro": 1.18,  # Towering Wave
    "cluster_607_sector001_macro": 0.15,  # Rolk's Demise
    "cluster_608_sector001_macro": 0.41,  # Atreus' Clouds
    "cluster_609_sector001_macro": 2.71,  # Menelaus' Oasis
    "cluster_701_sector001_macro": 1.18,  # Mitsuno's Revelation
    "cluster_702_sector001_macro": 1.11,  # Mitsuno's Defiance
    "cluster_703_sector001_macro": 1.06,  # Mitsuno's Sacrifice
    "cluster_704_sector001_macro": 0.71,  # President's End
    "cluster_705_sector001_macro": 1.63,  # Nopileos' Memorial
    "cluster_706_sector001_macro": 0.88,  # Hatikvah's Faith
    "cluster_708_sector001_macro": 4.08,  # Matrix #101
    "cluster_709_sector001_macro": 1.24,  # Cardinal's Domain
    "cluster_710_sector001_macro": 0.93,  # Moo-Kye's Revenge
    "cluster_711_sector001_macro": 0.53,  # Mi Ton's Refuge
    "cluster_712_sector001_macro": 0.02,  # Loomanckstrat's Legacy
    "cluster_713_sector001_macro": 0.82,  # CEO's Doubt
    "cluster_714_sector001_macro": 2.21,  # Freedom's Reach
    "cluster_715_sector001_macro": 1.41,  # Mists of Artemis
    "cluster_720_sector001_macro": 1.34,  # Ore Belt
    "cluster_721_sector001_macro": 0.71,  # Adventure's Promise
    "cluster_722_sector001_macro": 0.89,  # Sanctum Verge
    "cluster_723_sector001_macro": 1.66,  # Tempting Fumes
    "cluster_724_sector001_macro": 1.42,  # Circle of Deceit
    "cluster_725_sector001_macro": 0.83,  # Void of Opportunity
    "cluster_730_sector001_macro": 1.0,  # Third Redemption
    "cluster_740_sector001_macro": 2.66,  # Scarlet Star
}

SECTOR_NAMES: dict[str, str] = {
    "cluster_01_sector001_macro":  'Grand Exchange I',
    "cluster_01_sector002_macro":  'Grand Exchange III',
    "cluster_01_sector003_macro":  'Grand Exchange IV',
    "cluster_02_sector001_macro":  'Eighteen Billion',
    "cluster_03_sector001_macro":  'Memory of Profit IX',
    "cluster_04_sector001_macro":  "Nopileos' Fortune II",
    "cluster_04_sector002_macro":  "Nopileos' Fortune VI",
    "cluster_05_sector001_macro":  'Path to Profit',
    "cluster_06_sector001_macro":  'Black Hole Sun IV',
    "cluster_06_sector002_macro":  'Black Hole Sun V',
    "cluster_07_sector001_macro":  'The Reach',
    "cluster_08_sector001_macro":  'Silent Witness I',
    "cluster_09_sector001_macro":  'Bright Promise',
    "cluster_100_sector001_macro": 'Asteroid Belt',
    "cluster_101_sector001_macro": 'Mars',
    "cluster_102_sector001_macro": 'Venus',
    "cluster_104_sector001_macro": 'Earth',
    "cluster_104_sector002_macro": 'The Moon',
    "cluster_106_sector001_macro": 'Mercury',
    "cluster_107_sector001_macro": 'Jupiter',
    "cluster_108_sector001_macro": 'Saturn Alpha',
    "cluster_108_sector002_macro": 'Titan',
    "cluster_108_sector003_macro": 'Saturn Beta',
    "cluster_109_sector001_macro": 'Uranus',
    "cluster_10_sector001_macro":  'Unholy Retribution',
    "cluster_110_sector001_macro": 'Neptune',
    "cluster_111_sector001_macro": 'Pluto',
    "cluster_112_sector001_macro": 'Savage Spur I',
    "cluster_112_sector002_macro": 'Savage Spur II',
    "cluster_113_sector001_macro": 'Segaris',
    "cluster_114_sector001_macro": 'Gaian Prophecy',
    "cluster_115_sector001_macro": "Brennan's Triumph",
    "cluster_116_sector001_macro": 'Oort Cloud',
    "cluster_11_sector001_macro":  "Pontifex's Claim",
    "cluster_12_sector001_macro":  'True Sight',
    "cluster_13_sector001_macro":  'Second Contact II Flashpoint',
    "cluster_14_sector001_macro":  'Argon Prime',
    "cluster_15_sector001_macro":  'Ianamus Zura IV',
    "cluster_15_sector002_macro":  'Ianamus Zura VII',
    "cluster_16_sector001_macro":  'Matrix #451',
    "cluster_17_sector001_macro":  'Matrix #9',
    "cluster_18_sector001_macro":  'Trinity Sanctum III',
    "cluster_19_sector001_macro":  "Hewa's Twin I",
    "cluster_19_sector002_macro":  "Hewa's Twin II",
    "cluster_20_sector001_macro":  'Company Regard',
    "cluster_21_sector001_macro":  'Scale Plate Green I',
    "cluster_21_sector002_macro":  'Scale Plate Green VII',
    "cluster_22_sector001_macro":  'Pious Mists II',
    "cluster_23_sector001_macro":  'Sacred Relic',
    "cluster_24_sector001_macro":  'Holy Vision',
    "cluster_25_sector001_macro":  'Faulty Logic I',
    "cluster_25_sector002_macro":  'Faulty Logic VII',
    "cluster_26_sector001_macro":  "Atiya's Misfortune I",
    "cluster_26_sector002_macro":  "Atiya's Misfortune III",
    "cluster_27_sector001_macro":  'The Void',
    "cluster_28_sector001_macro":  'Antigone Memorial',
    "cluster_29_sector001_macro":  "Hatikvah's Choice I",
    "cluster_29_sector002_macro":  "Hatikvah's Choice III",
    "cluster_30_sector001_macro":  'Morning Star III',
    "cluster_31_sector001_macro":  "Heretic's End",
    "cluster_32_sector001_macro":  "Tharka's Cascade XV",
    "cluster_32_sector002_macro":  "Tharka's Cascade XVII",
    "cluster_33_sector001_macro":  'Matrix #79B',
    "cluster_34_sector001_macro":  'Profit Center Alpha',
    "cluster_35_sector001_macro":  'Lasting Vengeance',
    "cluster_36_sector001_macro":  "Cardinal's Redress",
    "cluster_37_sector001_macro":  'Pious Mists IV',
    "cluster_38_sector001_macro":  'Pious Mists XI',
    "cluster_39_sector001_macro":  'Memory of Profit X',
    "cluster_400_sector001_macro": 'Wretched Skies IV Family Valka',
    "cluster_401_sector001_macro": 'Family Zhin',
    "cluster_402_sector001_macro": 'Family Kritt',
    "cluster_403_sector001_macro": 'Wretched Skies V Family Phi',
    "cluster_404_sector001_macro": "Zyarth's Dominion I",
    "cluster_405_sector001_macro": "Zyarth's Dominion IV",
    "cluster_406_sector001_macro": "Zyarth's Dominion X",
    "cluster_407_sector001_macro": 'Family Tkr',
    "cluster_408_sector001_macro": "Thuruk's Demise III",
    "cluster_408_sector002_macro": "Thuruk's Demise II First Impact",
    "cluster_409_sector001_macro": "Tharka's Ravine IV Tharka's Fall",
    "cluster_40_sector001_macro":  'Second Contact VII',
    "cluster_410_sector001_macro": "Tharka's Ravine VIII",
    "cluster_411_sector001_macro": 'Heart of Acrimony II',
    "cluster_412_sector001_macro": "Tharka's Ravine XVI",
    "cluster_413_sector001_macro": "Tharka's Ravine XXIV",
    "cluster_414_sector001_macro": "Rhy's Defiance",
    "cluster_415_sector001_macro": 'Matrix #598',
    "cluster_416_sector001_macro": 'Guiding Star V',
    "cluster_416_sector002_macro": 'Guiding Star VII',
    "cluster_417_sector001_macro": 'Eleventh Hour',
    "cluster_418_sector001_macro": 'Family Nhuut',
    "cluster_419_sector001_macro": 'Open Market',
    "cluster_41_sector001_macro":  'Second Contact XI',
    "cluster_420_sector001_macro": 'Two Grand',
    "cluster_421_sector001_macro": 'Fires of Defeat',
    "cluster_422_sector001_macro": 'Wretched Skies X',
    "cluster_423_sector001_macro": 'Litany of Fury IX',
    "cluster_423_sector002_macro": 'Litany of Fury XII',
    "cluster_424_sector001_macro": "Emperor's Pride IV",
    "cluster_424_sector002_macro": "Emperor's Pride VI",
    "cluster_425_sector001_macro": 'Heart of Acrimony I The Boneyard',
    "cluster_42_sector001_macro":  "Hewa's Twin III",
    "cluster_42_sector002_macro":  "Hewa's Twin IV The Cove",
    "cluster_43_sector001_macro":  "Hewa's Twin V",
    "cluster_44_sector001_macro":  'Silent Witness XI',
    "cluster_45_sector001_macro":  'Silent Witness XII',
    "cluster_46_sector001_macro":  'Morning Star IV',
    "cluster_47_sector001_macro":  'Trinity Sanctum VII',
    "cluster_48_sector001_macro":  'Getsu Fune',
    "cluster_49_sector001_macro":  'Frontier Edge',
    "cluster_500_sector001_macro": 'Avarice I',
    "cluster_500_sector002_macro": 'Avarice V Dead End',
    "cluster_500_sector003_macro": 'Avarice IV',
    "cluster_501_sector001_macro": 'Windfall I Union Summit',
    "cluster_502_sector001_macro": 'Windfall III The Hoard',
    "cluster_503_sector001_macro": "Windfall IV Aurora's Dream",
    "cluster_504_sector001_macro": 'Unknown System',
    "cluster_50_sector001_macro":  'Turquoise Sea IX',
    "cluster_50_sector002_macro":  'Turquoise Sea X',
    "cluster_601_sector001_macro": 'Watchful Gaze',
    "cluster_602_sector001_macro": 'Barren Shores',
    "cluster_603_sector001_macro": 'Great Reef',
    "cluster_604_sector001_macro": 'Ocean of Fantasy',
    "cluster_605_sector001_macro": 'Sanctuary of Darkness',
    "cluster_606_sector001_macro": 'Kingdom End I',
    "cluster_606_sector002_macro": 'Reflected Stars',
    "cluster_606_sector003_macro": 'Towering Wave',
    "cluster_607_sector001_macro": "Rolk's Demise",
    "cluster_608_sector001_macro": "Atreus' Clouds",
    "cluster_609_sector001_macro": "Menelaus' Oasis",
    "cluster_701_sector001_macro": "Mitsuno's Revelation",
    "cluster_702_sector001_macro": "Mitsuno's Defiance",
    "cluster_703_sector001_macro": "Mitsuno's Sacrifice",
    "cluster_704_sector001_macro": "President's End",
    "cluster_705_sector001_macro": "Nopileos' Memorial",
    "cluster_706_sector001_macro": "Hatikvah's Faith",
    "cluster_708_sector001_macro": 'Matrix #101',
    "cluster_709_sector001_macro": "Cardinal's Domain",
    "cluster_710_sector001_macro": "Moo-Kye's Revenge",
    "cluster_711_sector001_macro": "Mi Ton's Refuge",
    "cluster_712_sector001_macro": "Loomanckstrat's Legacy",
    "cluster_713_sector001_macro": "CEO's Doubt",
    "cluster_714_sector001_macro": "Freedom's Reach",
    "cluster_715_sector001_macro": 'Mists of Artemis',
    "cluster_720_sector001_macro": 'Ore Belt',
    "cluster_721_sector001_macro": "Adventure's Promise",
    "cluster_722_sector001_macro": 'Sanctum Verge',
    "cluster_723_sector001_macro": 'Tempting Fumes',
    "cluster_724_sector001_macro": 'Circle of Deceit',
    "cluster_725_sector001_macro": 'Void of Opportunity',
    "cluster_730_sector001_macro": 'Third Redemption',
    "cluster_740_sector001_macro": 'Scarlet Star',
}

SECTOR_RESOURCES: dict[str, list[tuple[str, str]]] = {
    "cluster_01_sector001_macro":  [('hydrogen', 'high'), ('ice', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'verylow')],  # Grand Exchange I
    "cluster_01_sector002_macro":  [('ore', 'high'), ('silicon', 'high'), ('hydrogen', 'medium'), ('ice', 'medium'), ('helium', 'low'), ('methane', 'low'), ('rawscrap', 'verylow')],  # Grand Exchange III
    "cluster_01_sector003_macro":  [('hydrogen', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'verylow')],  # Grand Exchange IV
    "cluster_02_sector001_macro":  [('helium', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'high'), ('silicon', 'high')],  # Eighteen Billion
    "cluster_03_sector001_macro":  [('ice', 'medium'), ('ore', 'medium'), ('silicon', 'medium'), ('nividium', 'verylow')],  # Memory of Profit IX
    "cluster_04_sector001_macro":  [('hydrogen', 'veryhigh'), ('ore', 'veryhigh'), ('ice', 'high'), ('nividium', 'low')],  # Nopileos' Fortune II
    "cluster_05_sector001_macro":  [('hydrogen', 'veryhigh')],  # Path to Profit
    "cluster_06_sector001_macro":  [('hydrogen', 'high'), ('methane', 'medium'), ('ore', 'medium'), ('silicon', 'medium'), ('helium', 'low'), ('nividium', 'verylow')],  # Black Hole Sun IV
    "cluster_06_sector002_macro":  [('hydrogen', 'high'), ('helium', 'medium'), ('methane', 'medium')],  # Black Hole Sun V
    "cluster_07_sector001_macro":  [('ore', 'high')],  # The Reach
    "cluster_08_sector001_macro":  [('hydrogen', 'veryhigh'), ('silicon', 'high'), ('nividium', 'medium')],  # Silent Witness I
    "cluster_100_sector001_macro": [('ice', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('methane', 'high'), ('nividium', 'medium')],  # Asteroid Belt
    "cluster_106_sector001_macro": [('helium', 'veryhigh')],  # Mercury
    "cluster_108_sector002_macro": [('hydrogen', 'veryhigh'), ('methane', 'veryhigh')],  # Titan
    "cluster_108_sector003_macro": [('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('ice', 'high')],  # Saturn Beta
    "cluster_110_sector001_macro": [('helium', 'veryhigh'), ('hydrogen', 'high')],  # Neptune
    "cluster_112_sector001_macro": [('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('nividium', 'medium')],  # Savage Spur I
    "cluster_112_sector002_macro": [('helium', 'veryhigh'), ('hydrogen', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('nividium', 'medium')],  # Savage Spur II
    "cluster_113_sector001_macro": [('ice', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('methane', 'high'), ('nividium', 'low')],  # Segaris
    "cluster_114_sector001_macro": [('helium', 'veryhigh'), ('hydrogen', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('nividium', 'medium')],  # Gaian Prophecy
    "cluster_116_sector001_macro": [('hydrogen', 'veryhigh'), ('ice', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('helium', 'high'), ('nividium', 'medium')],  # Oort Cloud
    "cluster_11_sector001_macro":  [('hydrogen', 'high'), ('ice', 'high'), ('methane', 'high'), ('helium', 'medium')],  # Pontifex's Claim
    "cluster_13_sector001_macro":  [('hydrogen', 'veryhigh'), ('ice', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'low')],  # Second Contact II Flashpoint
    "cluster_15_sector001_macro":  [('helium', 'medium'), ('hydrogen', 'medium'), ('ice', 'medium'), ('methane', 'medium')],  # Ianamus Zura IV
    "cluster_15_sector002_macro":  [('ice', 'medium'), ('ore', 'medium'), ('silicon', 'medium'), ('nividium', 'verylow')],  # Ianamus Zura VII
    "cluster_16_sector001_macro":  [('hydrogen', 'veryhigh'), ('ore', 'high'), ('silicon', 'high')],  # Matrix #451
    "cluster_17_sector001_macro":  [('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('nividium', 'high')],  # Matrix #9
    "cluster_18_sector001_macro":  [('hydrogen', 'medium'), ('ice', 'medium'), ('methane', 'medium'), ('ore', 'medium'), ('silicon', 'medium'), ('helium', 'low'), ('nividium', 'verylow')],  # Trinity Sanctum III
    "cluster_19_sector001_macro":  [('hydrogen', 'medium'), ('ore', 'medium'), ('silicon', 'medium'), ('helium', 'low'), ('methane', 'low'), ('nividium', 'verylow')],  # Hewa's Twin I
    "cluster_19_sector002_macro":  [('ore', 'high'), ('silicon', 'high'), ('hydrogen', 'medium'), ('helium', 'low'), ('methane', 'low'), ('nividium', 'verylow')],  # Hewa's Twin II
    "cluster_21_sector001_macro":  [('rawscrap', 'veryhigh'), ('ore', 'high'), ('silicon', 'high'), ('hydrogen', 'medium'), ('nividium', 'verylow')],  # Scale Plate Green I
    "cluster_21_sector002_macro":  [('ore', 'high'), ('silicon', 'high')],  # Scale Plate Green VII
    "cluster_24_sector001_macro":  [('hydrogen', 'high'), ('ore', 'high'), ('silicon', 'high'), ('helium', 'medium'), ('ice', 'medium'), ('methane', 'low'), ('nividium', 'verylow')],  # Holy Vision
    "cluster_25_sector001_macro":  [('hydrogen', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('rawscrap', 'medium')],  # Faulty Logic I
    "cluster_25_sector002_macro":  [('hydrogen', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh')],  # Faulty Logic VII
    "cluster_26_sector001_macro":  [('hydrogen', 'veryhigh'), ('nividium', 'veryhigh'), ('ore', 'high')],  # Atiya's Misfortune I
    "cluster_26_sector002_macro":  [('nividium', 'veryhigh'), ('hydrogen', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Atiya's Misfortune III
    "cluster_27_sector001_macro":  [('hydrogen', 'high'), ('ice', 'high'), ('methane', 'high'), ('ore', 'medium'), ('silicon', 'medium'), ('helium', 'low'), ('nividium', 'low')],  # The Void
    "cluster_28_sector001_macro":  [('hydrogen', 'high'), ('ice', 'high'), ('ore', 'high'), ('silicon', 'high'), ('helium', 'medium'), ('nividium', 'low')],  # Antigone Memorial
    "cluster_29_sector002_macro":  [('ore', 'high'), ('silicon', 'high'), ('helium', 'medium'), ('hydrogen', 'medium'), ('ice', 'medium'), ('methane', 'low'), ('nividium', 'low')],  # Hatikvah's Choice III
    "cluster_31_sector001_macro":  [('ore', 'veryhigh'), ('rawscrap', 'low')],  # Heretic's End
    "cluster_32_sector001_macro":  [('hydrogen', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'high'), ('nividium', 'medium'), ('rawscrap', 'verylow')],  # Tharka's Cascade XV
    "cluster_32_sector002_macro":  [('hydrogen', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Tharka's Cascade XVII
    "cluster_33_sector001_macro":  [('hydrogen', 'medium'), ('rawscrap', 'low')],  # Matrix #79B
    "cluster_35_sector001_macro":  [('ice', 'high'), ('ore', 'high'), ('hydrogen', 'medium'), ('silicon', 'medium')],  # Lasting Vengeance
    "cluster_36_sector001_macro":  [('hydrogen', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Cardinal's Redress
    "cluster_37_sector001_macro":  [('methane', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Pious Mists IV
    "cluster_38_sector001_macro":  [('hydrogen', 'veryhigh'), ('helium', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'medium')],  # Pious Mists XI
    "cluster_401_sector001_macro": [('hydrogen', 'veryhigh'), ('methane', 'high'), ('ore', 'high'), ('silicon', 'high'), ('helium', 'medium'), ('nividium', 'low')],  # Family Zhin
    "cluster_402_sector001_macro": [('ice', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Family Kritt
    "cluster_40_sector001_macro":  [('ore', 'veryhigh'), ('silicon', 'high'), ('nividium', 'low')],  # Second Contact VII
    "cluster_410_sector001_macro": [('ice', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Tharka's Ravine VIII
    "cluster_411_sector001_macro": [('ice', 'veryhigh'), ('hydrogen', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Heart of Acrimony II
    "cluster_412_sector001_macro": [('methane', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('ice', 'high')],  # Tharka's Ravine XVI
    "cluster_413_sector001_macro": [('methane', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('ice', 'high')],  # Tharka's Ravine XXIV
    "cluster_414_sector001_macro": [('rawscrap', 'veryhigh')],  # Rhy's Defiance
    "cluster_415_sector001_macro": [('hydrogen', 'high'), ('ice', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Matrix #598
    "cluster_416_sector002_macro": [('ice', 'high')],  # Guiding Star VII
    "cluster_418_sector001_macro": [('ore', 'high'), ('rawscrap', 'high'), ('silicon', 'high'), ('hydrogen', 'medium'), ('ice', 'medium'), ('methane', 'medium'), ('helium', 'low'), ('nividium', 'low'), ('rawkhaakscrap', 'verylow')],  # Family Nhuut
    "cluster_41_sector001_macro":  [('ore', 'veryhigh'), ('silicon', 'high')],  # Second Contact XI
    "cluster_420_sector001_macro": [('ore', 'high'), ('silicon', 'high')],  # Two Grand
    "cluster_421_sector001_macro": [('rawscrap', 'medium')],  # Fires of Defeat
    "cluster_422_sector001_macro": [('ice', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Wretched Skies X
    "cluster_424_sector002_macro": [('ore', 'high'), ('silicon', 'high')],  # Emperor's Pride VI
    "cluster_425_sector001_macro": [('ore', 'high'), ('silicon', 'high')],  # Heart of Acrimony I The Boneyard
    "cluster_43_sector001_macro":  [('rawscrap', 'veryhigh'), ('ore', 'high'), ('silicon', 'high')],  # Hewa's Twin V
    "cluster_44_sector001_macro":  [('ore', 'veryhigh'), ('silicon', 'high'), ('nividium', 'low')],  # Silent Witness XI
    "cluster_45_sector001_macro":  [('rawscrap', 'veryhigh'), ('ore', 'medium'), ('silicon', 'medium'), ('rawkhaakscrap', 'low')],  # Silent Witness XII
    "cluster_46_sector001_macro":  [('hydrogen', 'veryhigh'), ('ore', 'high'), ('silicon', 'high'), ('helium', 'medium'), ('ice', 'medium'), ('nividium', 'medium')],  # Morning Star IV
    "cluster_47_sector001_macro":  [('nividium', 'high'), ('ore', 'high'), ('silicon', 'high'), ('helium', 'medium'), ('hydrogen', 'medium'), ('ice', 'medium'), ('methane', 'medium')],  # Trinity Sanctum VII
    "cluster_48_sector001_macro":  [('rawscrap', 'veryhigh'), ('ice', 'high'), ('ore', 'high'), ('silicon', 'high'), ('rawkhaakscrap', 'low')],  # Getsu Fune
    "cluster_49_sector001_macro":  [('hydrogen', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('helium', 'medium')],  # Frontier Edge
    "cluster_500_sector001_macro": [('helium', 'veryhigh'), ('hydrogen', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('ice', 'high'), ('nividium', 'low')],  # Avarice I
    "cluster_500_sector002_macro": [('helium', 'veryhigh'), ('hydrogen', 'veryhigh'), ('ice', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('nividium', 'verylow')],  # Avarice V Dead End
    "cluster_500_sector003_macro": [('helium', 'veryhigh'), ('hydrogen', 'veryhigh'), ('ice', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh')],  # Avarice IV
    "cluster_501_sector001_macro": [('hydrogen', 'veryhigh'), ('ice', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('nividium', 'medium')],  # Windfall I Union Summit
    "cluster_502_sector001_macro": [('hydrogen', 'veryhigh')],  # Windfall III The Hoard
    "cluster_503_sector001_macro": [('hydrogen', 'veryhigh'), ('rawscrap', 'veryhigh'), ('ice', 'medium'), ('ore', 'low'), ('silicon', 'low'), ('nividium', 'verylow')],  # Windfall IV Aurora's Dream
    "cluster_504_sector001_macro": [('hydrogen', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('nividium', 'medium')],  # Unknown System
    "cluster_50_sector001_macro":  [('hydrogen', 'veryhigh'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'medium')],  # Turquoise Sea IX
    "cluster_50_sector002_macro":  [('hydrogen', 'high'), ('nividium', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Turquoise Sea X
    "cluster_601_sector001_macro": [('helium', 'veryhigh'), ('hydrogen', 'veryhigh'), ('methane', 'veryhigh'), ('ore', 'veryhigh'), ('silicon', 'veryhigh')],  # Watchful Gaze
    "cluster_602_sector001_macro": [('ore', 'veryhigh'), ('silicon', 'medium')],  # Barren Shores
    "cluster_603_sector001_macro": [('hydrogen', 'veryhigh'), ('methane', 'veryhigh'), ('helium', 'high')],  # Great Reef
    "cluster_604_sector001_macro": [('rawscrap', 'medium')],  # Ocean of Fantasy
    "cluster_605_sector001_macro": [('ore', 'low'), ('silicon', 'low')],  # Sanctuary of Darkness
    "cluster_606_sector002_macro": [('helium', 'veryhigh')],  # Reflected Stars
    "cluster_607_sector001_macro": [('methane', 'veryhigh'), ('ice', 'high'), ('ore', 'high'), ('silicon', 'high')],  # Rolk's Demise
    "cluster_608_sector001_macro": [('hydrogen', 'veryhigh'), ('ore', 'medium'), ('silicon', 'medium')],  # Atreus' Clouds
    "cluster_609_sector001_macro": [('helium', 'veryhigh'), ('ore', 'high'), ('silicon', 'high')],  # Menelaus' Oasis
    "cluster_702_sector001_macro": [('hydrogen', 'high'), ('ore', 'high'), ('helium', 'medium'), ('ice', 'medium'), ('methane', 'medium'), ('silicon', 'medium'), ('nividium', 'verylow')],  # Mitsuno's Defiance
    "cluster_703_sector001_macro": [('helium', 'high'), ('hydrogen', 'high'), ('ice', 'high'), ('methane', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'verylow')],  # Mitsuno's Sacrifice
    "cluster_704_sector001_macro": [('ice', 'high'), ('ore', 'high'), ('nividium', 'verylow')],  # President's End
    "cluster_705_sector001_macro": [('ice', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'verylow')],  # Nopileos' Memorial
    "cluster_706_sector001_macro": [('ice', 'medium'), ('ore', 'medium'), ('silicon', 'medium')],  # Hatikvah's Faith
    "cluster_708_sector001_macro": [('rawscrap', 'high'), ('ore', 'low'), ('rawkhaakscrap', 'low'), ('silicon', 'low')],  # Matrix #101
    "cluster_709_sector001_macro": [('methane', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('ore', 'high'), ('ice', 'medium'), ('silicon', 'medium')],  # Cardinal's Domain
    "cluster_710_sector001_macro": [('ore', 'veryhigh'), ('ice', 'high'), ('silicon', 'high'), ('nividium', 'verylow')],  # Moo-Kye's Revenge
    "cluster_711_sector001_macro": [('ice', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'low')],  # Mi Ton's Refuge
    "cluster_712_sector001_macro": [('ice', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'medium')],  # Loomanckstrat's Legacy
    "cluster_713_sector001_macro": [('helium', 'high'), ('hydrogen', 'high'), ('ice', 'high'), ('methane', 'high'), ('ore', 'high'), ('silicon', 'high')],  # CEO's Doubt
    "cluster_715_sector001_macro": [('helium', 'high'), ('hydrogen', 'high'), ('methane', 'high'), ('ore', 'high'), ('silicon', 'high'), ('nividium', 'medium')],  # Mists of Artemis
    "cluster_720_sector001_macro": [('ore', 'high'), ('rawscrap', 'high'), ('helium', 'medium'), ('hydrogen', 'medium'), ('methane', 'medium')],  # Ore Belt
    "cluster_721_sector001_macro": [('ore', 'veryhigh'), ('silicon', 'veryhigh'), ('helium', 'high'), ('hydrogen', 'high'), ('methane', 'high'), ('nividium', 'low')],  # Adventure's Promise
    "cluster_722_sector001_macro": [('ore', 'high'), ('silicon', 'high'), ('nividium', 'low'), ('methane', 'verylow')],  # Sanctum Verge
    "cluster_723_sector001_macro": [('helium', 'high')],  # Tempting Fumes
    "cluster_724_sector001_macro": [('helium', 'high'), ('methane', 'high'), ('rawscrap', 'medium'), ('rawkhaakscrap', 'low')],  # Circle of Deceit
    "cluster_725_sector001_macro": [('ore', 'high'), ('silicon', 'high'), ('helium', 'medium'), ('hydrogen', 'medium'), ('methane', 'medium'), ('nividium', 'verylow')],  # Void of Opportunity
    "cluster_730_sector001_macro": [('ice', 'medium'), ('methane', 'medium'), ('ore', 'low'), ('nividium', 'verylow')],  # Third Redemption
    "cluster_740_sector001_macro": [('ore', 'high'), ('helium', 'low'), ('rawscrap', 'low')],  # Scarlet Star
}

SECTOR_OWNERS: dict[str, str] = {
    "cluster_01_sector001_macro":  'teladi',  # Grand Exchange I
    "cluster_01_sector002_macro":  'teladi',  # Grand Exchange III
    "cluster_01_sector003_macro":  'teladi',  # Grand Exchange IV
    "cluster_02_sector001_macro":  'teladi',  # Eighteen Billion
    "cluster_03_sector001_macro":  'teladi',  # Memory of Profit IX
    "cluster_05_sector001_macro":  'teladi',  # Path to Profit
    "cluster_06_sector001_macro":  'argon',  # Black Hole Sun IV
    "cluster_06_sector002_macro":  'argon',  # Black Hole Sun V
    "cluster_07_sector001_macro":  'argon',  # The Reach
    "cluster_08_sector001_macro":  'argon',  # Silent Witness I
    "cluster_09_sector001_macro":  'teladi',  # Bright Promise
    "cluster_100_sector001_macro": 'terran',  # Asteroid Belt
    "cluster_101_sector001_macro": 'terran',  # Mars
    "cluster_102_sector001_macro": 'terran',  # Venus
    "cluster_104_sector001_macro": 'terran',  # Earth
    "cluster_104_sector002_macro": 'terran',  # The Moon
    "cluster_106_sector001_macro": 'terran',  # Mercury
    "cluster_107_sector001_macro": 'terran',  # Jupiter
    "cluster_108_sector001_macro": 'terran',  # Saturn Alpha
    "cluster_108_sector002_macro": 'terran',  # Titan
    "cluster_108_sector003_macro": 'terran',  # Saturn Beta
    "cluster_109_sector001_macro": 'terran',  # Uranus
    "cluster_10_sector001_macro":  'paranid',  # Unholy Retribution
    "cluster_110_sector001_macro": 'terran',  # Neptune
    "cluster_111_sector001_macro": 'terran',  # Pluto
    "cluster_112_sector001_macro": 'xenon',  # Savage Spur I
    "cluster_112_sector002_macro": 'xenon',  # Savage Spur II
    "cluster_113_sector001_macro": 'pioneers',  # Segaris
    "cluster_114_sector001_macro": 'pioneers',  # Gaian Prophecy
    "cluster_115_sector001_macro": 'pioneers',  # Brennan's Triumph
    "cluster_116_sector001_macro": 'terran',  # Oort Cloud
    "cluster_11_sector001_macro":  'holyorder',  # Pontifex's Claim
    "cluster_12_sector001_macro":  'holyorder',  # True Sight
    "cluster_13_sector001_macro":  'antigone',  # Second Contact II Flashpoint
    "cluster_14_sector001_macro":  'argon',  # Argon Prime
    "cluster_15_sector001_macro":  'teladi',  # Ianamus Zura IV
    "cluster_15_sector002_macro":  'teladi',  # Ianamus Zura VII
    "cluster_16_sector001_macro":  'xenon',  # Matrix #451
    "cluster_17_sector001_macro":  'xenon',  # Matrix #9
    "cluster_18_sector001_macro":  'paranid',  # Trinity Sanctum III
    "cluster_19_sector001_macro":  'teladi',  # Hewa's Twin I
    "cluster_19_sector002_macro":  'teladi',  # Hewa's Twin II
    "cluster_20_sector001_macro":  'teladi',  # Company Regard
    "cluster_21_sector001_macro":  'xenon',  # Scale Plate Green I
    "cluster_21_sector002_macro":  'xenon',  # Scale Plate Green VII
    "cluster_22_sector001_macro":  'paranid',  # Pious Mists II
    "cluster_23_sector001_macro":  'paranid',  # Sacred Relic
    "cluster_24_sector001_macro":  'holyorder',  # Holy Vision
    "cluster_25_sector001_macro":  'xenon',  # Faulty Logic I
    "cluster_25_sector002_macro":  'xenon',  # Faulty Logic VII
    "cluster_26_sector001_macro":  'xenon',  # Atiya's Misfortune I
    "cluster_26_sector002_macro":  'xenon',  # Atiya's Misfortune III
    "cluster_27_sector001_macro":  'antigone',  # The Void
    "cluster_28_sector001_macro":  'antigone',  # Antigone Memorial
    "cluster_29_sector001_macro":  'hatikvah',  # Hatikvah's Choice I
    "cluster_29_sector002_macro":  'argon',  # Hatikvah's Choice III
    "cluster_30_sector001_macro":  'argon',  # Morning Star III
    "cluster_31_sector001_macro":  'hatikvah',  # Heretic's End
    "cluster_32_sector001_macro":  'xenon',  # Tharka's Cascade XV
    "cluster_32_sector002_macro":  'xenon',  # Tharka's Cascade XVII
    "cluster_33_sector001_macro":  'xenon',  # Matrix #79B
    "cluster_34_sector001_macro":  'teladi',  # Profit Center Alpha
    "cluster_35_sector001_macro":  'holyorder',  # Lasting Vengeance
    "cluster_36_sector001_macro":  'holyorder',  # Cardinal's Redress
    "cluster_37_sector001_macro":  'paranid',  # Pious Mists IV
    "cluster_38_sector001_macro":  'paranid',  # Pious Mists XI
    "cluster_39_sector001_macro":  'teladi',  # Memory of Profit X
    "cluster_400_sector001_macro": 'split',  # Wretched Skies IV Family Valka
    "cluster_401_sector001_macro": 'split',  # Family Zhin
    "cluster_402_sector001_macro": 'split',  # Family Kritt
    "cluster_403_sector001_macro": 'split',  # Wretched Skies V Family Phi
    "cluster_404_sector001_macro": 'split',  # Zyarth's Dominion I
    "cluster_405_sector001_macro": 'split',  # Zyarth's Dominion IV
    "cluster_406_sector001_macro": 'split',  # Zyarth's Dominion X
    "cluster_407_sector001_macro": 'freesplit',  # Family Tkr
    "cluster_408_sector001_macro": 'freesplit',  # Thuruk's Demise III
    "cluster_408_sector002_macro": 'freesplit',  # Thuruk's Demise II First Impact
    "cluster_409_sector001_macro": 'freesplit',  # Tharka's Ravine IV Tharka's Fall
    "cluster_40_sector001_macro":  'antigone',  # Second Contact VII
    "cluster_410_sector001_macro": 'freesplit',  # Tharka's Ravine VIII
    "cluster_411_sector001_macro": 'freesplit',  # Heart of Acrimony II
    "cluster_412_sector001_macro": 'freesplit',  # Tharka's Ravine XVI
    "cluster_413_sector001_macro": 'xenon',  # Tharka's Ravine XXIV
    "cluster_414_sector001_macro": 'xenon',  # Rhy's Defiance
    "cluster_415_sector001_macro": 'xenon',  # Matrix #598
    "cluster_416_sector001_macro": 'argon',  # Guiding Star V
    "cluster_416_sector002_macro": 'argon',  # Guiding Star VII
    "cluster_417_sector001_macro": 'argon',  # Eleventh Hour
    "cluster_418_sector001_macro": 'split',  # Family Nhuut
    "cluster_419_sector001_macro": 'teladi',  # Open Market
    "cluster_41_sector001_macro":  'antigone',  # Second Contact XI
    "cluster_420_sector001_macro": 'teladi',  # Two Grand
    "cluster_421_sector001_macro": 'freesplit',  # Fires of Defeat
    "cluster_422_sector001_macro": 'paranid',  # Wretched Skies X
    "cluster_423_sector001_macro": 'paranid',  # Litany of Fury IX
    "cluster_423_sector002_macro": 'paranid',  # Litany of Fury XII
    "cluster_424_sector001_macro": 'xenon',  # Emperor's Pride IV
    "cluster_424_sector002_macro": 'xenon',  # Emperor's Pride VI
    "cluster_42_sector001_macro":  'teladi',  # Hewa's Twin III
    "cluster_42_sector002_macro":  'scaleplate',  # Hewa's Twin IV The Cove
    "cluster_43_sector001_macro":  'teladi',  # Hewa's Twin V
    "cluster_44_sector001_macro":  'hatikvah',  # Silent Witness XI
    "cluster_45_sector001_macro":  'scaleplate',  # Silent Witness XII
    "cluster_46_sector001_macro":  'argon',  # Morning Star IV
    "cluster_47_sector001_macro":  'paranid',  # Trinity Sanctum VII
    "cluster_500_sector001_macro": 'scavenger',  # Avarice I
    "cluster_500_sector002_macro": 'scavenger',  # Avarice V Dead End
    "cluster_500_sector003_macro": 'scavenger',  # Avarice IV
    "cluster_501_sector001_macro": 'loanshark',  # Windfall I Union Summit
    "cluster_502_sector001_macro": 'loanshark',  # Windfall III The Hoard
    "cluster_503_sector001_macro": 'loanshark',  # Windfall IV Aurora's Dream
    "cluster_602_sector001_macro": 'boron',  # Barren Shores
    "cluster_603_sector001_macro": 'boron',  # Great Reef
    "cluster_604_sector001_macro": 'boron',  # Ocean of Fantasy
    "cluster_606_sector001_macro": 'boron',  # Kingdom End I
    "cluster_606_sector002_macro": 'boron',  # Reflected Stars
    "cluster_606_sector003_macro": 'boron',  # Towering Wave
    "cluster_607_sector001_macro": 'boron',  # Rolk's Demise
    "cluster_608_sector001_macro": 'boron',  # Atreus' Clouds
    "cluster_609_sector001_macro": 'boron',  # Menelaus' Oasis
    "cluster_701_sector001_macro": 'kaori',  # Mitsuno's Revelation
    "cluster_702_sector001_macro": 'kaori',  # Mitsuno's Defiance
    "cluster_703_sector001_macro": 'kaori',  # Mitsuno's Sacrifice
    "cluster_704_sector001_macro": 'argon',  # President's End
    "cluster_705_sector001_macro": 'scaleplate',  # Nopileos' Memorial
    "cluster_708_sector001_macro": 'xenon',  # Matrix #101
    "cluster_709_sector001_macro": 'paranid',  # Cardinal's Domain
    "cluster_712_sector001_macro": 'scaleplate',  # Loomanckstrat's Legacy
    "cluster_713_sector001_macro": 'teladi',  # CEO's Doubt
    "cluster_714_sector001_macro": 'teladi',  # Freedom's Reach
    "cluster_725_sector001_macro": 'xenon',  # Void of Opportunity
}
