# ─────────────────────────────────────────────────────────────────────────────
#  SHIP STATS
#  Maps ship macro names to their static game stats, extracted from the
#  macro XML files in 'ship xml/'.
#
#  AUTO-GENERATED by generate_ship_stats.py — do not edit by hand.
#  Re-run generate_ship_stats.py after adding new XMLs to 'ship xml/'.
#
#  CURRENT KEYS PER ENTRY:
#    max_hull  — base maximum hull HP before any mods are applied
# ─────────────────────────────────────────────────────────────────────────────

SHIP_STATS = {
    'ship_arg_l_destroyer_01_a_macro': {
        'max_hull': 93000,
    },
    'ship_arg_l_destroyer_01_b_macro': {
        'max_hull': 111000,
    },
    'ship_arg_l_destroyer_02_a_macro': {
        'max_hull': 102000,
    },
    'ship_arg_l_miner_liquid_01_a_macro': {
        'max_hull': 26000,
    },
    'ship_arg_l_miner_liquid_01_b_macro': {
        'max_hull': 32000,
    },
    'ship_arg_l_miner_solid_01_a_macro': {
        'max_hull': 26000,
    },
    'ship_arg_l_miner_solid_01_b_macro': {
        'max_hull': 32000,
    },
    'ship_arg_l_trans_container_01_a_macro': {
        'max_hull': 57000,
    },
    'ship_arg_l_trans_container_01_b_macro': {
        'max_hull': 69000,
    },
    'ship_arg_l_trans_container_02_a_macro': {
        'max_hull': 53000,
    },
    'ship_arg_l_trans_container_02_b_macro': {
        'max_hull': 64000,
    },
    'ship_arg_l_trans_container_03_a_macro': {
        'max_hull': 78000,
    },
    'ship_arg_l_trans_container_03_b_macro': {
        'max_hull': 93000,
    },
    'ship_arg_l_trans_container_04_a_macro': {
        'max_hull': 84000,
    },
    'ship_arg_l_trans_container_04_b_macro': {
        'max_hull': 101000,
    },
    'ship_arg_l_trans_container_05_a_macro': {
        'max_hull': 67000,
    },
    'ship_arg_l_trans_container_05_b_macro': {
        'max_hull': 80000,
    },
    'ship_arg_m_bomber_01_a_macro': {
        'max_hull': 12000,
    },
    'ship_arg_m_bomber_01_b_macro': {
        'max_hull': 14000,
    },
    'ship_arg_m_bomber_02_a_macro': {
        'max_hull': 13000,
    },
    'ship_arg_m_frigate_01_a_macro': {
        'max_hull': 17000,
    },
    'ship_arg_m_frigate_01_b_macro': {
        'max_hull': 20000,
    },
    'ship_arg_m_miner_liquid_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_arg_m_miner_liquid_01_b_macro': {
        'max_hull': 5000,
    },
    'ship_arg_m_miner_solid_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_arg_m_miner_solid_01_b_macro': {
        'max_hull': 5000,
    },
    'ship_arg_m_trans_container_01_a_macro': {
        'max_hull': 5000,
    },
    'ship_arg_m_trans_container_01_b_macro': {
        'max_hull': 6000,
    },
    'ship_arg_m_trans_container_02_a_macro': {
        'max_hull': 5000,
    },
    'ship_arg_m_trans_container_02_b_macro': {
        'max_hull': 6000,
    },
    'ship_arg_s_fighter_01_a_macro': {
        'max_hull': 3100,
    },
    'ship_arg_s_fighter_01_b_macro': {
        'max_hull': 3800,
    },
    'ship_arg_s_fighter_02_a_macro': {
        'max_hull': 1800,
    },
    'ship_arg_s_fighter_02_b_macro': {
        'max_hull': 2200,
    },
    'ship_arg_s_fighter_03_a_macro': {
        'max_hull': 1900,
    },
    'ship_arg_s_fighter_04_a_macro': {
        'max_hull': 1700,
    },
    'ship_arg_s_heavyfighter_01_a_macro': {
        'max_hull': 4400,
    },
    'ship_arg_s_heavyfighter_01_b_macro': {
        'max_hull': 5300,
    },
    'ship_arg_s_heavyfighter_02_a_macro': {
        'max_hull': 4000,
    },
    'ship_arg_s_miner_solid_01_a_macro': {
        'max_hull': 1200,
    },
    'ship_arg_s_racer_01_a_macro': {
        'max_hull': 1800,
    },
    'ship_arg_s_scout_01_a_macro': {
        'max_hull': 1400,
    },
    'ship_arg_s_scout_01_b_macro': {
        'max_hull': 1700,
    },
    'ship_arg_s_trans_container_01_a_macro': {
        'max_hull': 2600,
    },
    'ship_arg_s_trans_container_01_b_macro': {
        'max_hull': 3000,
    },
    'ship_arg_s_trans_container_02_a_macro': {
        'max_hull': 2100,
    },
    'ship_arg_s_trans_container_02_b_macro': {
        'max_hull': 2500,
    },
    'ship_arg_xl_builder_01_a_macro': {
        'max_hull': 115000,
    },
    'ship_arg_xl_builder_01_b_macro': {
        'max_hull': 138000,
    },
    'ship_arg_xl_carrier_01_a_macro': {
        'max_hull': 216000,
    },
    'ship_arg_xl_carrier_01_b_macro': {
        'max_hull': 259000,
    },
    'ship_arg_xl_carrier_02_a_macro': {
        'max_hull': 277000,
    },
    'ship_arg_xl_resupplier_01_a_macro': {
        'max_hull': 116000,
    },
    'ship_arg_xl_resupplier_01_b_macro': {
        'max_hull': 139000,
    },
    'ship_arg_xs_cv_01_a_macro': {
        'max_hull': 150,
    },
    'ship_arg_xs_cv_02_a_macro': {
        'max_hull': 100,
    },
    'ship_arg_xs_police_01_a_macro': {
        'max_hull': 281,
    },
    'ship_arg_xs_pv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_arg_xs_pv_01_b_macro': {
        'max_hull': 184,
    },
    'ship_arg_xs_pv_01_c_macro': {
        'max_hull': 184,
    },
    'ship_arg_xs_pv_01_d_macro': {
        'max_hull': 184,
    },
    'ship_arg_xs_pv_02_a_macro': {
        'max_hull': 209,
    },
    'ship_arg_xs_pv_03_a_macro': {
        'max_hull': 200,
    },
    'ship_arg_xs_pv_03_b_macro': {
        'max_hull': 260,
    },
    'ship_arg_xs_pv_04_a_macro': {
        'max_hull': 150,
    },
    'ship_arg_xs_pv_04_b_macro': {
        'max_hull': 260,
    },
    'ship_arg_xs_pv_05_a_macro': {
        'max_hull': 100,
    },
    'ship_arg_xs_pv_05_b_macro': {
        'max_hull': 130,
    },
    'ship_arg_xs_pv_05_c_macro': {
        'max_hull': 100,
    },
    'ship_atf_l_destroyer_01_a_macro': {
        'max_hull': 130000,
    },
    'ship_atf_xl_battleship_01_a_macro': {
        'max_hull': 275000,
    },
    'ship_bor_l_carrier_01_a_macro': {
        'max_hull': 117000,
    },
    'ship_bor_l_destroyer_01_a_macro': {
        'max_hull': 114000,
    },
    'ship_bor_l_miner_liquid_01_a_macro': {
        'max_hull': 31000,
    },
    'ship_bor_l_miner_solid_01_a_macro': {
        'max_hull': 31000,
    },
    'ship_bor_l_trans_container_01_a_macro': {
        'max_hull': 40000,
    },
    'ship_bor_m_corvette_01_a_macro': {
        'max_hull': 7900,
    },
    'ship_bor_m_corvette_02_a_macro': {
        'max_hull': 8100,
    },
    'ship_bor_m_gunboat_01_a_macro': {
        'max_hull': 10900,
    },
    'ship_bor_m_miner_liquid_01_a_macro': {
        'max_hull': 8000,
    },
    'ship_bor_m_miner_solid_01_a_macro': {
        'max_hull': 8000,
    },
    'ship_bor_m_trans_container_01_a_macro': {
        'max_hull': 9000,
    },
    'ship_bor_s_fighter_01_a_macro': {
        'max_hull': 3100,
    },
    'ship_bor_s_heavyfighter_01_a_macro': {
        'max_hull': 3700,
    },
    'ship_bor_s_miner_solid_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_bor_s_scout_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_bor_s_scout_02_a_macro': {
        'max_hull': 2600,
    },
    'ship_bor_s_trans_container_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_bor_xl_builder_01_a_macro': {
        'max_hull': 178000,
    },
    'ship_bor_xl_carrier_01_a_macro': {
        'max_hull': 383000,
    },
    'ship_bor_xl_resupplier_01_a_macro': {
        'max_hull': 174000,
    },
    'ship_bor_xs_cv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_bor_xs_cv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_bor_xs_cv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_bor_xs_pv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_bor_xs_pv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_bor_xs_pv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_bor_xs_pv_04_a_macro': {
        'max_hull': 184,
    },
    'ship_bor_xs_pv_05_a_macro': {
        'max_hull': 184,
    },
    'ship_gen_m_transdrone_container_01_a_macro': {
        'max_hull': 10000,
    },
    'ship_gen_m_transdrone_container_02_a_macro': {
        'max_hull': 10000,
    },
    'ship_gen_m_tugboat_01_a_macro': {
        'max_hull': 8000,
    },
    'ship_gen_m_yacht_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_gen_s_fighter_01_a_macro': {
        'max_hull': 3900,
    },
    'ship_gen_s_fighter_01_b_macro': {
        'max_hull': 4600,
    },
    'ship_gen_s_fightingdrone_01_a_macro': {
        'max_hull': 1900,
    },
    'ship_gen_s_fightingdrone_explosive_01_a_macro': {
        'max_hull': 1200,
    },
    'ship_gen_s_lasertower_01_a_macro': {
        'max_hull': 5000,
    },
    'ship_gen_s_miningdrone_liquid_01_a_macro': {
        'max_hull': 1700,
    },
    'ship_gen_s_miningdrone_solid_01_a_macro': {
        'max_hull': 1700,
    },
    'ship_gen_s_racer_01_a_macro': {
        'max_hull': 2100,
    },
    'ship_gen_s_transdrone_container_01_a_macro': {
        'max_hull': 2200,
    },
    'ship_gen_s_transdrone_container_02_a_macro': {
        'max_hull': 2200,
    },
    'ship_gen_xs_boardingpod_01_a_macro': {
        'max_hull': 200,
    },
    'ship_gen_xs_buildingdrone_01_a_macro': {
        'max_hull': 207,
    },
    'ship_gen_xs_cargodrone_container_01_a_macro': {
        'max_hull': 523,
    },
    'ship_gen_xs_cargodrone_empty_01_a_macro': {
        'max_hull': 523,
    },
    'ship_gen_xs_cargodrone_equipment_01_a_macro': {
        'max_hull': 523,
    },
    'ship_gen_xs_cargodrone_liquid_01_a_macro': {
        'max_hull': 523,
    },
    'ship_gen_xs_cargodrone_pickup_01_a_macro': {
        'max_hull': 523,
    },
    'ship_gen_xs_cargodrone_solid_01_a_macro': {
        'max_hull': 523,
    },
    'ship_gen_xs_distressbeacon_01_a_macro': {
        'max_hull': 250,
    },
    'ship_gen_xs_escapepod_01_a_macro': {
        'max_hull': 209,
    },
    'ship_gen_xs_lasertower_01_a_macro': {
        'max_hull': 1001,
    },
    'ship_gen_xs_repairdrone_01_a_macro': {
        'max_hull': 207,
    },
    'ship_kha_l_destroyer_01_a_macro': {
        'max_hull': 119000,
    },
    'ship_kha_m_fighter_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_kha_m_fighter_02_a_macro': {
        'max_hull': 3000,
    },
    'ship_kha_s_fighter_01_a_macro': {
        'max_hull': 800,
    },
    'ship_kha_s_fighter_02_a_macro': {
        'max_hull': 600,
    },
    'ship_kha_xl_battleship_01_a_macro': {
        'max_hull': 275000,
    },
    'ship_par_l_destroyer_01_a_macro': {
        'max_hull': 99000,
    },
    'ship_par_l_destroyer_01_b_macro': {
        'max_hull': 119000,
    },
    'ship_par_l_destroyer_02_a_macro': {
        'max_hull': 128000,
    },
    'ship_par_l_miner_liquid_01_a_macro': {
        'max_hull': 23000,
    },
    'ship_par_l_miner_liquid_01_b_macro': {
        'max_hull': 28000,
    },
    'ship_par_l_miner_liquid_02_a_macro': {
        'max_hull': 29000,
    },
    'ship_par_l_miner_solid_01_a_macro': {
        'max_hull': 23000,
    },
    'ship_par_l_miner_solid_01_b_macro': {
        'max_hull': 28000,
    },
    'ship_par_l_miner_solid_02_a_macro': {
        'max_hull': 29000,
    },
    'ship_par_l_trans_container_01_a_macro': {
        'max_hull': 37000,
    },
    'ship_par_l_trans_container_01_b_macro': {
        'max_hull': 45000,
    },
    'ship_par_l_trans_container_02_a_macro': {
        'max_hull': 33000,
    },
    'ship_par_l_trans_container_02_b_macro': {
        'max_hull': 40000,
    },
    'ship_par_l_trans_container_03_a_macro': {
        'max_hull': 55000,
    },
    'ship_par_m_corvette_01_a_macro': {
        'max_hull': 10000,
    },
    'ship_par_m_corvette_01_b_macro': {
        'max_hull': 12000,
    },
    'ship_par_m_frigate_01_a_macro': {
        'max_hull': 19000,
    },
    'ship_par_m_frigate_01_b_macro': {
        'max_hull': 23000,
    },
    'ship_par_m_miner_liquid_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_par_m_miner_liquid_01_b_macro': {
        'max_hull': 5000,
    },
    'ship_par_m_miner_solid_01_a_macro': {
        'max_hull': 4000,
    },
    'ship_par_m_miner_solid_01_b_macro': {
        'max_hull': 5000,
    },
    'ship_par_m_trans_container_01_a_macro': {
        'max_hull': 5000,
    },
    'ship_par_m_trans_container_01_b_macro': {
        'max_hull': 7000,
    },
    'ship_par_m_trans_container_02_a_macro': {
        'max_hull': 5000,
    },
    'ship_par_m_trans_container_02_b_macro': {
        'max_hull': 6000,
    },
    'ship_par_m_trans_container_03_a_macro': {
        'max_hull': 11000,
    },
    'ship_par_s_fighter_01_a_macro': {
        'max_hull': 3700,
    },
    'ship_par_s_fighter_01_b_macro': {
        'max_hull': 4400,
    },
    'ship_par_s_fighter_02_a_macro': {
        'max_hull': 4200,
    },
    'ship_par_s_fighter_02_b_macro': {
        'max_hull': 5000,
    },
    'ship_par_s_heavyfighter_01_a_macro': {
        'max_hull': 4700,
    },
    'ship_par_s_miner_solid_01_a_macro': {
        'max_hull': 1200,
    },
    'ship_par_s_racer_01_a_macro': {
        'max_hull': 4200,
    },
    'ship_par_s_scout_01_a_macro': {
        'max_hull': 1300,
    },
    'ship_par_s_scout_01_b_macro': {
        'max_hull': 1600,
    },
    'ship_par_s_trans_container_01_a_macro': {
        'max_hull': 2100,
    },
    'ship_par_s_trans_container_01_b_macro': {
        'max_hull': 2600,
    },
    'ship_par_xl_builder_01_a_macro': {
        'max_hull': 149000,
    },
    'ship_par_xl_builder_01_b_macro': {
        'max_hull': 178000,
    },
    'ship_par_xl_carrier_01_a_macro': {
        'max_hull': 281000,
    },
    'ship_par_xl_carrier_01_b_macro': {
        'max_hull': 337000,
    },
    'ship_par_xl_carrier_02_a_macro': {
        'max_hull': 303000,
    },
    'ship_par_xl_resupplier_01_a_macro': {
        'max_hull': 130000,
    },
    'ship_par_xl_resupplier_01_b_macro': {
        'max_hull': 156000,
    },
    'ship_par_xl_resupplier_02_a_macro': {
        'max_hull': 164000,
    },
    'ship_par_xs_police_01_a_macro': {
        'max_hull': 281,
    },
    'ship_par_xs_pv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_par_xs_pv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_par_xs_pv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_par_xs_pv_04_a_macro': {
        'max_hull': 184,
    },
    'ship_pir_l_miner_solid_01_a_macro': {
        'max_hull': 26000,
    },
    'ship_pir_l_scavenger_01_a_macro': {
        'max_hull': 114000,
    },
    'ship_pir_l_scavenger_01_a_storyhighcapacity_macro': {
        'max_hull': 114000,
    },
    'ship_pir_l_scrapper_01_macro': {
        'max_hull': 66000,
    },
    'ship_pir_s_fighter_01_a_macro': {
        'max_hull': 3000,
    },
    'ship_pir_s_fighter_02_a_macro': {
        'max_hull': 2600,
    },
    'ship_pir_s_heavyfighter_01_a_macro': {
        'max_hull': 4900,
    },
    'ship_pir_s_trans_condensate_01_a_macro': {
        'max_hull': 2200,
    },
    'ship_pir_s_trans_container_01_a_macro': {
        'max_hull': 2200,
    },
    'ship_pir_xl_battleship_01_a_macro': {
        'max_hull': 500000,
    },
    'ship_pir_xl_builder_01_macro': {
        'max_hull': 115000,
    },
    'ship_spl_l_destroyer_01_a_macro': {
        'max_hull': 211000,
    },
    'ship_spl_l_miner_liquid_01_a_macro': {
        'max_hull': 21000,
    },
    'ship_spl_l_miner_solid_01_a_macro': {
        'max_hull': 21000,
    },
    'ship_spl_l_trans_container_01_a_macro': {
        'max_hull': 37000,
    },
    'ship_spl_m_bomber_01_a_macro': {
        'max_hull': 25000,
    },
    'ship_spl_m_corvette_01_a_macro': {
        'max_hull': 17000,
    },
    'ship_spl_m_corvette_01_b_macro': {
        'max_hull': 8000,
    },
    'ship_spl_m_frigate_01_a_macro': {
        'max_hull': 32000,
    },
    'ship_spl_m_miner_liquid_01_a_macro': {
        'max_hull': 4300,
    },
    'ship_spl_m_miner_solid_01_a_macro': {
        'max_hull': 4800,
    },
    'ship_spl_m_trans_container_01_a_macro': {
        'max_hull': 7400,
    },
    'ship_spl_s_fighter_01_a_macro': {
        'max_hull': 3600,
    },
    'ship_spl_s_fighter_02_a_macro': {
        'max_hull': 4600,
    },
    'ship_spl_s_fighter_02_b_macro': {
        'max_hull': 1800,
    },
    'ship_spl_s_heavyfighter_01_a_macro': {
        'max_hull': 6100,
    },
    'ship_spl_s_heavyfighter_02_a_macro': {
        'max_hull': 5500,
    },
    'ship_spl_s_miner_solid_01_a_macro': {
        'max_hull': 1200,
    },
    'ship_spl_s_scenariofighter_01_a_macro': {
        'max_hull': 6100,
    },
    'ship_spl_s_scout_01_a_macro': {
        'max_hull': 2000,
    },
    'ship_spl_s_trans_container_01_a_macro': {
        'max_hull': 2300,
    },
    'ship_spl_s_trans_container_01_plot_01_macro': {
        'max_hull': 2300,
    },
    'ship_spl_xl_ark_01_a_macro': {
        'max_hull': 935000,
    },
    'ship_spl_xl_battleship_01_a_macro': {
        'max_hull': 230000,
    },
    'ship_spl_xl_builder_01_a_macro': {
        'max_hull': 181000,
    },
    'ship_spl_xl_carrier_01_a_macro': {
        'max_hull': 590000,
    },
    'ship_spl_xl_resupplier_01_a_macro': {
        'max_hull': 160000,
    },
    'ship_spl_xs_cv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_cv_01_b_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_cv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_cv_02_b_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_cv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_cv_03_b_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_police_01_a_macro': {
        'max_hull': 281,
    },
    'ship_spl_xs_pv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_01_b_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_01_c_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_02_b_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_02_c_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_03_b_macro': {
        'max_hull': 184,
    },
    'ship_spl_xs_pv_03_c_macro': {
        'max_hull': 184,
    },
    'ship_tel_l_destroyer_01_a_macro': {
        'max_hull': 104000,
    },
    'ship_tel_l_destroyer_01_b_macro': {
        'max_hull': 124000,
    },
    'ship_tel_l_destroyer_02_a_macro': {
        'max_hull': 112000,
    },
    'ship_tel_l_miner_liquid_01_a_macro': {
        'max_hull': 30000,
    },
    'ship_tel_l_miner_liquid_01_b_macro': {
        'max_hull': 36000,
    },
    'ship_tel_l_miner_liquid_02_a_macro': {
        'max_hull': 34800,
    },
    'ship_tel_l_miner_solid_01_a_macro': {
        'max_hull': 30000,
    },
    'ship_tel_l_miner_solid_01_b_macro': {
        'max_hull': 36000,
    },
    'ship_tel_l_miner_solid_02_a_macro': {
        'max_hull': 35000,
    },
    'ship_tel_l_trans_container_01_a_macro': {
        'max_hull': 52000,
    },
    'ship_tel_l_trans_container_01_b_macro': {
        'max_hull': 63000,
    },
    'ship_tel_l_trans_container_02_a_macro': {
        'max_hull': 48000,
    },
    'ship_tel_l_trans_container_02_b_macro': {
        'max_hull': 57000,
    },
    'ship_tel_l_trans_container_03_a_macro': {
        'max_hull': 64000,
    },
    'ship_tel_m_bomber_01_a_macro': {
        'max_hull': 12000,
    },
    'ship_tel_m_bomber_01_b_macro': {
        'max_hull': 14000,
    },
    'ship_tel_m_frigate_01_a_macro': {
        'max_hull': 33000,
    },
    'ship_tel_m_frigate_01_b_macro': {
        'max_hull': 39000,
    },
    'ship_tel_m_miner_liquid_01_a_macro': {
        'max_hull': 3700,
    },
    'ship_tel_m_miner_liquid_01_b_macro': {
        'max_hull': 4500,
    },
    'ship_tel_m_miner_solid_01_a_macro': {
        'max_hull': 3700,
    },
    'ship_tel_m_miner_solid_01_b_macro': {
        'max_hull': 4500,
    },
    'ship_tel_m_trans_container_01_a_macro': {
        'max_hull': 8000,
    },
    'ship_tel_m_trans_container_01_b_macro': {
        'max_hull': 9000,
    },
    'ship_tel_m_trans_container_02_a_macro': {
        'max_hull': 7000,
    },
    'ship_tel_m_trans_container_02_b_macro': {
        'max_hull': 8000,
    },
    'ship_tel_m_trans_container_03_a_macro': {
        'max_hull': 10000,
    },
    'ship_tel_s_fighter_01_a_macro': {
        'max_hull': 3900,
    },
    'ship_tel_s_fighter_01_b_macro': {
        'max_hull': 4600,
    },
    'ship_tel_s_fighter_02_a_macro': {
        'max_hull': 4100,
    },
    'ship_tel_s_fighter_02_b_macro': {
        'max_hull': 5000,
    },
    'ship_tel_s_miner_solid_01_a_macro': {
        'max_hull': 1300,
    },
    'ship_tel_s_racer_01_a_macro': {
        'max_hull': 2500,
    },
    'ship_tel_s_scout_01_a_macro': {
        'max_hull': 2500,
    },
    'ship_tel_s_scout_01_b_macro': {
        'max_hull': 3100,
    },
    'ship_tel_s_scout_02_a_macro': {
        'max_hull': 2300,
    },
    'ship_tel_s_scout_02_b_macro': {
        'max_hull': 2700,
    },
    'ship_tel_s_trans_container_01_a_macro': {
        'max_hull': 2400,
    },
    'ship_tel_s_trans_container_01_b_macro': {
        'max_hull': 2800,
    },
    'ship_tel_s_trans_container_02_a_macro': {
        'max_hull': 6700,
    },
    'ship_tel_xl_builder_01_a_macro': {
        'max_hull': 128000,
    },
    'ship_tel_xl_builder_01_b_macro': {
        'max_hull': 154000,
    },
    'ship_tel_xl_carrier_01_a_macro': {
        'max_hull': 239000,
    },
    'ship_tel_xl_carrier_01_b_macro': {
        'max_hull': 287000,
    },
    'ship_tel_xl_resupplier_01_a_macro': {
        'max_hull': 105000,
    },
    'ship_tel_xl_resupplier_01_b_macro': {
        'max_hull': 126000,
    },
    'ship_tel_xs_police_01_a_macro': {
        'max_hull': 281,
    },
    'ship_tel_xs_police_02_a_macro': {
        'max_hull': 281,
    },
    'ship_tel_xs_police_03_a_macro': {
        'max_hull': 281,
    },
    'ship_tel_xs_pv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_tel_xs_pv_01_b_macro': {
        'max_hull': 184,
    },
    'ship_tel_xs_pv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_tel_xs_pv_02_b_macro': {
        'max_hull': 184,
    },
    'ship_tel_xs_pv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_tel_xs_pv_03_b_macro': {
        'max_hull': 184,
    },
    'ship_tel_xs_pv_04_a_macro': {
        'max_hull': 184,
    },
    'ship_tel_xs_pv_04_b_macro': {
        'max_hull': 184,
    },
    'ship_ter_l_destroyer_01_a_macro': {
        'max_hull': 95000,
    },
    'ship_ter_l_flagship_01_a_macro': {
        'max_hull': 128000,
    },
    'ship_ter_l_flagship_01_b_macro': {
        'max_hull': 128000,
    },
    'ship_ter_l_miner_liquid_01_a_macro': {
        'max_hull': 24000,
    },
    'ship_ter_l_miner_solid_01_a_macro': {
        'max_hull': 24000,
    },
    'ship_ter_l_research_01_a_macro': {
        'max_hull': 36000,
    },
    'ship_ter_l_trans_container_01_a_macro': {
        'max_hull': 36000,
    },
    'ship_ter_m_corvette_01_a_macro': {
        'max_hull': 11000,
    },
    'ship_ter_m_corvette_02_a_macro': {
        'max_hull': 16100,
    },
    'ship_ter_m_corvette_02_b_macro': {
        'max_hull': 16100,
    },
    'ship_ter_m_frigate_01_a_macro': {
        'max_hull': 20000,
    },
    'ship_ter_m_gunboat_01_a_macro': {
        'max_hull': 13000,
    },
    'ship_ter_m_miner_liquid_01_a_macro': {
        'max_hull': 5000,
    },
    'ship_ter_m_miner_solid_01_a_macro': {
        'max_hull': 5000,
    },
    'ship_ter_m_trans_container_01_a_macro': {
        'max_hull': 9000,
    },
    'ship_ter_s_fighter_01_a_macro': {
        'max_hull': 3700,
    },
    'ship_ter_s_fighter_02_a_macro': {
        'max_hull': 3300,
    },
    'ship_ter_s_fighter_03_a_macro': {
        'max_hull': 3400,
    },
    'ship_ter_s_fighter_04_a_macro': {
        'max_hull': 3600,
    },
    'ship_ter_s_fighter_04_b_macro': {
        'max_hull': 2500,
    },
    'ship_ter_s_fighter_04_c_macro': {
        'max_hull': 3600,
    },
    'ship_ter_s_heavyfighter_01_a_macro': {
        'max_hull': 4400,
    },
    'ship_ter_s_miner_solid_01_a_macro': {
        'max_hull': 1000,
    },
    'ship_ter_s_scout_01_a_macro': {
        'max_hull': 1400,
    },
    'ship_ter_s_scout_02_a_macro': {
        'max_hull': 3000,
    },
    'ship_ter_s_trans_container_01_a_macro': {
        'max_hull': 1700,
    },
    'ship_ter_s_xperimental_01_a_macro': {
        'max_hull': 4580,
    },
    'ship_ter_s_xperimental_01_a_story_macro': {
        'max_hull': 38000,
    },
    'ship_ter_xl_builder_01_a_macro': {
        'max_hull': 153000,
    },
    'ship_ter_xl_carrier_01_a_macro': {
        'max_hull': 213000,
    },
    'ship_ter_xl_resupplier_01_a_macro': {
        'max_hull': 157000,
    },
    'ship_ter_xs_cv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_ter_xs_cv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_ter_xs_police_01_a_macro': {
        'max_hull': 300,
    },
    'ship_ter_xs_pv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_ter_xs_pv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_ter_xs_pv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_tfm_xl_carrier_01_a_macro': {
        'max_hull': 735000,
    },
    'ship_tfm_xl_carrier_02_a_macro': {
        'max_hull': 1190000,
    },
    'ship_tfm_xl_carrier_02_b_macro': {
        'max_hull': 1190000,
    },
    'ship_xen_l_terraformer_01_a_macro': {
        'max_hull': 112000,
    },
    'ship_xen_m_corvette_01_a_macro': {
        'max_hull': 8400,
    },
    'ship_xen_m_corvette_02_a_macro': {
        'max_hull': 12000,
    },
    'ship_xen_m_fighter_01_a_macro': {
        'max_hull': 10000,
    },
    'ship_xen_m_miner_01_a_macro': {
        'max_hull': 6000,
    },
    'ship_xen_m_miner_solid_01_a_macro': {
        'max_hull': 6100,
    },
    'ship_xen_s_fighter_01_a_macro': {
        'max_hull': 2500,
    },
    'ship_xen_s_fighter_02_a_macro': {
        'max_hull': 2900,
    },
    'ship_xen_s_heavyfighter_01_a_macro': {
        'max_hull': 4800,
    },
    'ship_xen_s_scout_01_a_macro': {
        'max_hull': 1200,
    },
    'ship_xen_xl_carrier_01_a_macro': {
        'max_hull': 340000,
    },
    'ship_xen_xl_destroyer_01_a_macro': {
        'max_hull': 165000,
    },
    'ship_xen_xl_mothership_01_a_macro': {
        'max_hull': 1496000,
    },
    'ship_xen_xs_pv_01_a_macro': {
        'max_hull': 184,
    },
    'ship_xen_xs_pv_02_a_macro': {
        'max_hull': 184,
    },
    'ship_xen_xs_pv_03_a_macro': {
        'max_hull': 184,
    },
    'ship_xen_xs_pv_04_a_macro': {
        'max_hull': 184,
    },
    'ship_yak_m_corvette_01_a_macro': {
        'max_hull': 10000,
    },
    'ship_yak_s_fighter_01_a_macro': {
        'max_hull': 4000,
    },
}
