# ─────────────────────────────────────────────────────────────────────────────
#  AUTO-GENERATED by gamefiles/generate_data.py — DO NOT EDIT BY HAND.
#  Source: libraries/wares.xml (+ DLC diffs) read directly from the X4
#  install's .cat archives. Re-run after a game update or DLC install:
#      python gamefiles/generate_data.py
#  then review the git diff for what the patch changed.
# ─────────────────────────────────────────────────────────────────────────────

# Station module + shield equipment macro → static game stats.
#   max_hull       — base maximum hull HP (structure modules)
#   max_shield     — shield recharge capacity in HP (shield equipment)
#   cargo_capacity — maximum cargo volume in m³ (storage modules)
#   produces       — ware id produced by this module (production modules)
# Used by StationHandler._parse_modules() and ShipHandler for shield HP.
# Entries with no meaningful values (decorative, connection pieces) are omitted.
STATION_STATS = {
    'buildmodule_bor_equip_l_macro': {
        'max_hull':       370000,
    },
    'buildmodule_bor_equip_m_dockarea_01_macro': {
        'max_hull':       225000,
    },
    'buildmodule_bor_equip_xl_macro': {
        'max_hull':       715000,
    },
    'buildmodule_bor_ships_l_macro': {
        'max_hull':       450000,
    },
    'buildmodule_bor_ships_m_dockarea_01_macro': {
        'max_hull':       245000,
    },
    'buildmodule_bor_ships_xl_macro': {
        'max_hull':       780000,
    },
    'buildmodule_gen_equip_l_macro': {
        'max_hull':       324000,
    },
    'buildmodule_gen_equip_m_dockarea_01_macro': {
        'max_hull':       1020000,
    },
    'buildmodule_gen_equip_xl_macro': {
        'max_hull':       551000,
    },
    'buildmodule_gen_ships_l_macro': {
        'max_hull':       324000,
    },
    'buildmodule_gen_ships_m_dockarea_01_macro': {
        'max_hull':       1020000,
    },
    'buildmodule_gen_ships_m_macro': {
        'max_hull':       176000,
    },
    'buildmodule_gen_ships_s_macro': {
        'max_hull':       176000,
    },
    'buildmodule_gen_ships_xl_macro': {
        'max_hull':       551000,
    },
    'buildmodule_ter_equip_l_macro': {
        'max_hull':       324000,
    },
    'buildmodule_ter_equip_m_dockarea_01_macro': {
        'max_hull':       1020000,
    },
    'buildmodule_ter_equip_xl_macro': {
        'max_hull':       551000,
    },
    'buildmodule_ter_ships_l_macro': {
        'max_hull':       324000,
    },
    'buildmodule_ter_ships_m_dockarea_01_macro': {
        'max_hull':       1020000,
    },
    'buildmodule_ter_ships_xl_macro': {
        'max_hull':       551000,
    },
    'buildmodule_xen_ships_m_macro': {
        'max_hull':       176000,
    },
    'buildmodule_xen_ships_s_macro': {
        'max_hull':       176000,
    },
    'buildmodule_xen_ships_xl_macro': {
        'max_hull':       551000,
    },
    'cargo_gen_buildstorage_01_macro': {
        'max_hull':       2500,
    },
    'defence_arg_claim_01_macro': {
        'max_hull':       512000,
    },
    'defence_arg_disc_01_macro': {
        'max_hull':       197400,
    },
    'defence_arg_tube_01_macro': {
        'max_hull':       148800,
    },
    'defence_bor_claim_01_macro': {
        'max_hull':       435000,
    },
    'defence_bor_disc_01_macro': {
        'max_hull':       387000,
    },
    'defence_bor_tube_01_macro': {
        'max_hull':       295000,
    },
    'defence_kha_disc_01_macro': {
        'max_hull':       50000,
    },
    'defence_par_claim_01_macro': {
        'max_hull':       532000,
    },
    'defence_par_claim_story_01_macro': {
        'max_hull':       1532000,
    },
    'defence_par_disc_01_macro': {
        'max_hull':       197400,
    },
    'defence_par_tube_01_macro': {
        'max_hull':       148800,
    },
    'defence_spl_claim_01_macro': {
        'max_hull':       520000,
    },
    'defence_spl_disc_01_macro': {
        'max_hull':       197400,
    },
    'defence_spl_tube_01_macro': {
        'max_hull':       148800,
    },
    'defence_tel_claim_01_macro': {
        'max_hull':       516000,
    },
    'defence_tel_disc_01_macro': {
        'max_hull':       197400,
    },
    'defence_tel_tube_01_macro': {
        'max_hull':       148800,
    },
    'defence_ter_claim_01_macro': {
        'max_hull':       600000,
    },
    'defence_ter_disc_01_macro': {
        'max_hull':       300000,
    },
    'defence_ter_tube_01_macro': {
        'max_hull':       150000,
    },
    'dockarea_arg_m_02_tradestation_01_macro': {
        'max_hull':       1100000,
    },
    'dockarea_arg_m_station_01_hightech_macro': {
        'max_hull':       275000,
    },
    'dockarea_arg_m_station_01_lowtech_macro': {
        'max_hull':       210000,
    },
    'dockarea_arg_m_station_01_macro': {
        'max_hull':       240000,
    },
    'dockarea_arg_m_station_02_hightech_macro': {
        'max_hull':       530000,
    },
    'dockarea_arg_m_station_02_lowtech_macro': {
        'max_hull':       460000,
    },
    'dockarea_arg_m_station_02_macro': {
        'max_hull':       495000,
    },
    'dockarea_bor_m_station_01_standard_macro': {
        'max_hull':       580000,
    },
    'dockarea_gen_m_showroom_01_macro': {
        'max_hull':       260000,
    },
    'dockarea_gen_m_venturer_01_macro': {
        'max_hull':       920000,
    },
    'dockarea_gen_s_showroom_01_macro': {
        'max_hull':       260000,
    },
    'dockarea_gen_s_showroom_02_macro': {
        'max_hull':       260000,
    },
    'dockarea_gen_xl_venturer_01_macro': {
        'max_hull':       1610000,
    },
    'dockarea_par_m_station_01_macro': {
        'max_hull':       72523,
    },
    'dockarea_tel_m_station_01_macro': {
        'max_hull':       72523,
    },
    'dockarea_ter_m_station_01_hightech_macro': {
        'max_hull':       455000,
    },
    'dockarea_ter_m_station_01_standard_macro': {
        'max_hull':       275000,
    },
    'dockarea_xen_m_station_01_macro': {
        'max_hull':       2160000,
    },
    'hab_arg_l_01_macro': {
        'max_hull':       500000,
    },
    'hab_arg_m_01_macro': {
        'max_hull':       250000,
    },
    'hab_arg_s_01_macro': {
        'max_hull':       120000,
    },
    'hab_bor_l_01_macro': {
        'max_hull':       480000,
    },
    'hab_bor_m_01_macro': {
        'max_hull':       260000,
    },
    'hab_bor_s_01_macro': {
        'max_hull':       140000,
    },
    'hab_par_l_01_macro': {
        'max_hull':       600000,
    },
    'hab_par_m_01_macro': {
        'max_hull':       250000,
    },
    'hab_par_s_01_macro': {
        'max_hull':       120000,
    },
    'hab_pir_l_01_macro': {
        'max_hull':       500000,
    },
    'hab_pir_m_01_macro': {
        'max_hull':       250000,
    },
    'hab_pir_s_01_macro': {
        'max_hull':       120000,
    },
    'hab_spl_l_01_macro': {
        'max_hull':       500000,
    },
    'hab_spl_m_01_macro': {
        'max_hull':       250000,
    },
    'hab_spl_s_01_macro': {
        'max_hull':       120000,
    },
    'hab_tel_l_01_macro': {
        'max_hull':       450000,
    },
    'hab_tel_m_01_macro': {
        'max_hull':       200000,
    },
    'hab_tel_s_01_macro': {
        'max_hull':       100000,
    },
    'hab_ter_l_01_macro': {
        'max_hull':       1200000,
    },
    'hab_ter_m_01_macro': {
        'max_hull':       600000,
    },
    'hab_ter_s_01_macro': {
        'max_hull':       300000,
    },
    'landmark_gen_hqasteroiddebree_01_macro': {
        'max_hull':       4500,
    },
    'landmarks_arg_antigonearc_01_macro': {
        'max_hull':       178500,
    },
    'landmarks_arg_antigonepillar_01_macro': {
        'max_hull':       430000,
    },
    'landmarks_arg_antigonescaffolding_01_macro': {
        'max_hull':       245500,
    },
    'landmarks_arg_antigonespire_01_macro': {
        'max_hull':       680000,
    },
    'landmarks_arg_antigonestraight_01_macro': {
        'max_hull':       223000,
    },
    'landmarks_erlking_vault_01_macro': {
        'max_hull':       150000,
    },
    'landmarks_erlking_vault_02_macro': {
        'max_hull':       150000,
    },
    'landmarks_erlking_vault_03_macro': {
        'max_hull':       150000,
    },
    'landmarks_erlking_vault_04_macro': {
        'max_hull':       150000,
    },
    'landmarks_erlking_vault_05_macro': {
        'max_hull':       150000,
    },
    'landmarks_gen_asteroidmine_01_entrance_01_macro': {
        'max_hull':       100000,
    },
    'landmarks_gen_exploration_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_old_ringstation_macro': {
        'max_hull':       1500000,
    },
    'landmarks_gen_piratestation_01_core_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_piratestation_01_exit_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_piratestation_01_port_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_piratestation_01_ring_01_macro': {
        'max_hull':       1000000,
        'cargo_capacity': 50000,
    },
    'landmarks_gen_piratestation_02_port_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_piratestation_02_ring_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_piratestation_02_ring_02_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_piratestation_02_storage_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_piratestation_02_storage_02_macro': {
        'max_hull':       1000000,
    },
    'landmarks_gen_prison_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_kha_hive_arm_01_macro': {
        'max_hull':       3500000,
    },
    'landmarks_kha_hive_cluster_01_macro': {
        'max_hull':       350000,
    },
    'landmarks_kha_tetrahedron_01_macro': {
        'max_hull':       60000,
    },
    'landmarks_kha_tetrahedron_02_macro': {
        'max_hull':       60000,
    },
    'landmarks_kha_tetrahedron_03_macro': {
        'max_hull':       60000,
    },
    'landmarks_kha_tetrahedron_04_macro': {
        'max_hull':       90000,
    },
    'landmarks_kha_tetrahedron_05_macro': {
        'max_hull':       90000,
    },
    'landmarks_par_monument_01_macro': {
        'max_hull':       10000,
    },
    'landmarks_par_monument_center_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_par_monument_clamp_01_macro': {
        'max_hull':       3,
    },
    'landmarks_par_monument_core_01_macro': {
        'max_hull':       800,
    },
    'landmarks_par_monument_core_02_macro': {
        'max_hull':       800,
    },
    'landmarks_par_storage_01_macro': {
        'max_hull':       739000,
        'cargo_capacity': 1000000,
    },
    'landmarks_par_tradestation_01_macro': {
        'max_hull':       100000,
    },
    'landmarks_par_tradestation_living_01_macro': {
        'max_hull':       100000,
    },
    'landmarks_par_tradestation_stor_container_l_01_macro': {
        'max_hull':       100000,
    },
    'landmarks_player_hq_01_research_macro': {
        'max_hull':       1000000,
    },
    'landmarks_research_vault_01_macro': {
        'max_hull':       150000,
    },
    'landmarks_tel_tradestation_01_bridge_01_macro': {
        'max_hull':       500000,
    },
    'landmarks_tel_tradestation_01_center_01_macro': {
        'max_hull':       2000000,
    },
    'landmarks_tel_tradestation_01_centercylinder_01_macro': {
        'max_hull':       200000,
    },
    'landmarks_tel_tradestation_01_centerend_01_macro': {
        'max_hull':       2000000,
    },
    'landmarks_tel_tradestation_01_centerfill_01_macro': {
        'max_hull':       500000,
    },
    'landmarks_tel_tradestation_01_column_01_macro': {
        'max_hull':       500000,
    },
    'landmarks_tel_tradestation_01_column_02_macro': {
        'max_hull':       500000,
    },
    'landmarks_tel_tradestation_01_dockarea_m_01_macro': {
        'max_hull':       2000000,
    },
    'landmarks_tel_tradestation_01_extension_01_macro': {
        'max_hull':       3000000,
    },
    'landmarks_tel_tradestation_01_radar_01_macro': {
        'max_hull':       500000,
    },
    'landmarks_tel_tradestation_01_ring_01_macro': {
        'max_hull':       10000000,
    },
    'landmarks_tel_tradestation_01_ring_inside_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_tel_tradestation_01_ring_inside_02_macro': {
        'max_hull':       1000000,
    },
    'landmarks_tel_tradestation_01_ring_inside_03_macro': {
        'max_hull':       1000000,
    },
    'landmarks_tel_tradestation_01_ring_storage_01_macro': {
        'max_hull':       4000000,
        'cargo_capacity': 400000,
    },
    'landmarks_tel_tradestation_01_ringcenter_01_macro': {
        'max_hull':       500000,
    },
    'landmarks_tel_tradestation_01_ringclamp_01_macro': {
        'max_hull':       1000000,
    },
    'landmarks_tel_tradestation_01_ringclamp_02_macro': {
        'max_hull':       1000000,
    },
    'landmarks_tel_tradestation_01_storage_01_macro': {
        'max_hull':       1000000,
        'cargo_capacity': 100000,
    },
    'landmarks_tel_tradestation_01_tradelocation_01_macro': {
        'max_hull':       200000,
    },
    'landmarks_vault_01_macro': {
        'max_hull':       15000,
    },
    'landmarks_vault_02_macro': {
        'max_hull':       1500,
    },
    'landmarks_vault_03_macro': {
        'max_hull':       150000,
    },
    'landmarks_vault_04_macro': {
        'max_hull':       15000,
    },
    'masstraffic_station_01_center_01_macro': {
        'max_hull':       1000000,
    },
    'masstraffic_station_02_center_01_macro': {
        'max_hull':       500000,
    },
    'masstraffic_station_03_center_01_macro': {
        'max_hull':       5000000,
    },
    'pier_arg_harbor_01_macro': {
        'max_hull':       750000,
    },
    'pier_arg_harbor_02_macro': {
        'max_hull':       250000,
    },
    'pier_arg_harbor_03_macro': {
        'max_hull':       1000000,
    },
    'pier_arg_harbor_04_macro': {
        'max_hull':       180000,
    },
    'pier_arg_single_01_tradestation_01_macro': {
        'max_hull':       100000,
    },
    'pier_bor_harbor_01_macro': {
        'max_hull':       850000,
    },
    'pier_bor_harbor_02_macro': {
        'max_hull':       325000,
    },
    'pier_bor_harbor_03_macro': {
        'max_hull':       1250000,
    },
    'pier_bor_harbor_04_macro': {
        'max_hull':       575000,
    },
    'pier_bor_tradestation_01_macro': {
        'max_hull':       2000000,
    },
    'pier_par_harbor_01_macro': {
        'max_hull':       810000,
    },
    'pier_par_harbor_02_macro': {
        'max_hull':       270000,
    },
    'pier_par_harbor_03_macro': {
        'max_hull':       1080000,
    },
    'pier_spl_harbor_01_macro': {
        'max_hull':       750000,
    },
    'pier_spl_harbor_02_macro': {
        'max_hull':       250000,
    },
    'pier_spl_harbor_03_macro': {
        'max_hull':       1000000,
    },
    'pier_tel_harbor_01_macro': {
        'max_hull':       750000,
    },
    'pier_tel_harbor_02_macro': {
        'max_hull':       250000,
    },
    'pier_tel_harbor_03_macro': {
        'max_hull':       1000000,
    },
    'pier_ter_harbor_01_macro': {
        'max_hull':       750000,
    },
    'pier_ter_harbor_02_macro': {
        'max_hull':       250000,
    },
    'pier_ter_harbor_03_macro': {
        'max_hull':       1000000,
    },
    'pier_ter_harbor_04_macro': {
        'max_hull':       250000,
    },
    'pier_ter_harbor_05_macro': {
        'max_hull':       250000,
    },
    'pier_ter_tradestation_01_macro': {
        'max_hull':       2000000,
    },
    'proc_gen_scrapworks_macro': {
        'max_hull':       150000,
    },
    'proc_gen_scrapworkskhaak_macro': {
        'max_hull':       150000,
    },
    'prod_arg_foodrations_macro': {
        'max_hull':       133000,
        'produces':       'foodrations',
    },
    'prod_arg_meat_macro': {
        'max_hull':       198000,
        'produces':       'meat',
    },
    'prod_arg_medicalsupplies_macro': {
        'max_hull':       197000,
        'produces':       'medicalsupplies',
    },
    'prod_arg_spacefuel_macro': {
        'max_hull':       148000,
        'produces':       'spacefuel',
    },
    'prod_arg_wheat_macro': {
        'max_hull':       262000,
        'produces':       'wheat',
    },
    'prod_bor_bofu_macro': {
        'max_hull':       165000,
        'produces':       'bofu',
    },
    'prod_bor_bogas_macro': {
        'max_hull':       185000,
        'produces':       'bogas',
    },
    'prod_bor_medicalsupplies_macro': {
        'max_hull':       204000,
        'produces':       'medicalsupplies',
    },
    'prod_bor_plankton_macro': {
        'max_hull':       135000,
        'produces':       'plankton',
    },
    'prod_gen_advancedcomposites_macro': {
        'max_hull':       197000,
        'produces':       'advancedcomposites',
    },
    'prod_gen_advancedelectronics_macro': {
        'max_hull':       160000,
        'produces':       'advancedelectronics',
    },
    'prod_gen_antimattercells_macro': {
        'max_hull':       251000,
        'produces':       'antimattercells',
    },
    'prod_gen_antimatterconverters_macro': {
        'max_hull':       216000,
        'produces':       'antimatterconverters',
    },
    'prod_gen_claytronics_macro': {
        'max_hull':       195000,
        'produces':       'claytronics',
    },
    'prod_gen_dronecomponents_macro': {
        'max_hull':       174000,
        'produces':       'dronecomponents',
    },
    'prod_gen_energycells_macro': {
        'max_hull':       217000,
        'produces':       'energycells',
    },
    'prod_gen_engineparts_macro': {
        'max_hull':       120000,
        'produces':       'engineparts',
    },
    'prod_gen_fieldcoils_macro': {
        'max_hull':       149000,
        'produces':       'fieldcoils',
    },
    'prod_gen_graphene_macro': {
        'max_hull':       190000,
        'produces':       'graphene',
    },
    'prod_gen_hullparts_macro': {
        'max_hull':       146000,
        'produces':       'hullparts',
    },
    'prod_gen_microchips_macro': {
        'max_hull':       199000,
        'produces':       'microchips',
    },
    'prod_gen_missilecomponents_macro': {
        'max_hull':       159000,
        'produces':       'missilecomponents',
    },
    'prod_gen_plasmaconductors_macro': {
        'max_hull':       181000,
        'produces':       'plasmaconductors',
    },
    'prod_gen_quantumtubes_macro': {
        'max_hull':       148000,
        'produces':       'quantumtubes',
    },
    'prod_gen_refinedmetals_macro': {
        'max_hull':       210000,
        'produces':       'refinedmetals',
    },
    'prod_gen_scanningarrays_macro': {
        'max_hull':       169000,
        'produces':       'scanningarrays',
    },
    'prod_gen_scrap_recycler_macro': {
        'max_hull':       200000,
    },
    'prod_gen_scrap_recyclerkhaak_macro': {
        'max_hull':       200000,
        'produces':       'khaakalloy',
    },
    'prod_gen_shieldcomponents_macro': {
        'max_hull':       191000,
        'produces':       'shieldcomponents',
    },
    'prod_gen_siliconwafers_macro': {
        'max_hull':       186000,
        'produces':       'siliconwafers',
    },
    'prod_gen_smartchips_macro': {
        'max_hull':       104000,
        'produces':       'smartchips',
    },
    'prod_gen_spices_macro': {
        'max_hull':       151000,
        'produces':       'spices',
    },
    'prod_gen_superfluidcoolant_macro': {
        'max_hull':       177000,
        'produces':       'superfluidcoolant',
    },
    'prod_gen_turretcomponents_macro': {
        'max_hull':       155000,
        'produces':       'turretcomponents',
    },
    'prod_gen_water_macro': {
        'max_hull':       203000,
        'produces':       'water',
    },
    'prod_gen_weaponcomponents_macro': {
        'max_hull':       208000,
        'produces':       'weaponcomponents',
    },
    'prod_par_majadust_macro': {
        'max_hull':       245000,
        'produces':       'majadust',
    },
    'prod_par_majasnails_macro': {
        'max_hull':       236000,
        'produces':       'majasnails',
    },
    'prod_par_medicalsupplies_macro': {
        'max_hull':       197000,
        'produces':       'medicalsupplies',
    },
    'prod_par_sojabeans_macro': {
        'max_hull':       259000,
        'produces':       'sojabeans',
    },
    'prod_par_sojahusk_macro': {
        'max_hull':       218000,
        'produces':       'sojahusk',
    },
    'prod_spl_cheltmeat_macro': {
        'max_hull':       320000,
        'produces':       'cheltmeat',
    },
    'prod_spl_medicalsupplies_macro': {
        'max_hull':       197000,
        'produces':       'medicalsupplies',
    },
    'prod_spl_scruffinfruit_macro': {
        'max_hull':       280000,
        'produces':       'scruffinfruits',
    },
    'prod_tel_advancedcomposites_macro': {
        'max_hull':       197000,
        'produces':       'advancedcomposites',
    },
    'prod_tel_engineparts_macro': {
        'max_hull':       120000,
        'produces':       'engineparts',
    },
    'prod_tel_hullparts_macro': {
        'max_hull':       146000,
        'produces':       'hullparts',
    },
    'prod_tel_medicalsupplies_macro': {
        'max_hull':       197000,
        'produces':       'medicalsupplies',
    },
    'prod_tel_nostropoil_macro': {
        'max_hull':       276000,
        'produces':       'nostropoil',
    },
    'prod_tel_scanningarrays_macro': {
        'max_hull':       169000,
        'produces':       'scanningarrays',
    },
    'prod_tel_spaceweed_macro': {
        'max_hull':       260000,
        'produces':       'spaceweed',
    },
    'prod_tel_sunriseflowers_macro': {
        'max_hull':       235000,
        'produces':       'sunriseflowers',
    },
    'prod_tel_swampplant_macro': {
        'max_hull':       287000,
        'produces':       'swampplant',
    },
    'prod_tel_teladianium_macro': {
        'max_hull':       226000,
        'produces':       'teladianium',
    },
    'prod_ter_computronicsubstrate_macro': {
        'max_hull':       400000,
        'produces':       'computronicsubstrate',
    },
    'prod_ter_energycells_macro': {
        'max_hull':       200000,
        'produces':       'energycells',
    },
    'prod_ter_medicalsupplies_macro': {
        'max_hull':       240000,
        'produces':       'medicalsupplies',
    },
    'prod_ter_metallicmicrolattice_macro': {
        'max_hull':       280000,
        'produces':       'metallicmicrolattice',
    },
    'prod_ter_mre_macro': {
        'max_hull':       270000,
        'produces':       'terranmre',
    },
    'prod_ter_proteinpaste_macro': {
        'max_hull':       260000,
        'produces':       'proteinpaste',
    },
    'prod_ter_scrap_recycler_macro': {
        'max_hull':       200000,
    },
    'prod_ter_siliconcarbide_macro': {
        'max_hull':       350000,
        'produces':       'siliconcarbide',
    },
    'prod_ter_stimulants_macro': {
        'max_hull':       300000,
        'produces':       'stimulants',
    },
    'radar_arg_dish_01_macro': {
        'max_hull':       110000,
    },
    'scs_gen_destructible_generator_01_macro': {
        'max_hull':       20,
    },
    'scs_gen_destructible_hatch_16_01_macro': {
        'max_hull':       10,
    },
    'scs_gen_destructible_hatch_32_01_macro': {
        'max_hull':       10,
    },
    'scs_gen_destructible_hazard_fire_01_macro': {
        'max_hull':       20,
    },
    'scs_gen_destructible_hazard_fire_02_macro': {
        'max_hull':       20,
    },
    'scs_gen_destructible_shoottarget_01_macro': {
        'max_hull':       3,
    },
    'scs_gen_prop_detector_01_macro': {
        'max_hull':       10,
    },
    'scs_gen_prop_oxygenrecharger_01_macro': {
        'max_hull':       10,
    },
    'shield_arg_l_standard_01_mk1_macro': {
        'max_shield':     55200,
    },
    'shield_arg_l_standard_01_mk2_macro': {
        'max_shield':     65688,
    },
    'shield_arg_m_standard_01_mk1_macro': {
        'max_shield':     5750,
    },
    'shield_arg_m_standard_01_mk2_macro': {
        'max_shield':     7475,
    },
    'shield_arg_m_standard_02_mk1_macro': {
        'max_shield':     5750,
    },
    'shield_arg_m_standard_02_mk2_macro': {
        'max_shield':     7475,
    },
    'shield_arg_s_combattutorial_01_mk1_macro': {
        'max_shield':     1000,
    },
    'shield_arg_s_racer_01_mk1_macro': {
        'max_shield':     1196,
    },
    'shield_arg_s_standard_01_mk1_macro': {
        'max_shield':     1196,
    },
    'shield_arg_s_standard_01_mk2_macro': {
        'max_shield':     1380,
    },
    'shield_arg_s_standard_01_mk3_macro': {
        'max_shield':     1955,
    },
    'shield_arg_xl_standard_01_mk1_macro': {
        'max_shield':     148900,
    },
    'shield_bor_l_standard_01_mk1_macro': {
        'max_shield':     50400,
    },
    'shield_bor_l_standard_01_mk2_macro': {
        'max_shield':     61690,
    },
    'shield_bor_l_standard_01_mk3_macro': {
        'max_shield':     82656,
    },
    'shield_bor_m_standard_01_mk1_macro': {
        'max_shield':     5250,
    },
    'shield_bor_m_standard_01_mk2_macro': {
        'max_shield':     6825,
    },
    'shield_bor_m_standard_01_mk3_macro': {
        'max_shield':     8400,
    },
    'shield_bor_m_standard_02_mk1_macro': {
        'max_shield':     5250,
    },
    'shield_bor_m_standard_02_mk2_macro': {
        'max_shield':     6825,
    },
    'shield_bor_m_standard_02_mk3_macro': {
        'max_shield':     8400,
    },
    'shield_bor_s_standard_01_mk1_macro': {
        'max_shield':     1050,
    },
    'shield_bor_s_standard_01_mk2_macro': {
        'max_shield':     1260,
    },
    'shield_bor_s_standard_01_mk3_macro': {
        'max_shield':     1738,
    },
    'shield_bor_xl_standard_01_mk1_macro': {
        'max_shield':     135955,
    },
    'shield_bor_xl_standard_01_mk2_macro': {
        'max_shield':     160427,
    },
    'shield_gen_m_yacht_01_mk1_macro': {
        'max_shield':     38600,
    },
    'shield_gen_s_racer_01_mk1_macro': {
        'max_shield':     1196,
    },
    'shield_kha_l_standard_01_mk1_macro': {
        'max_shield':     135000,
    },
    'shield_kha_m_standard_01_mk1_macro': {
        'max_shield':     4800,
    },
    'shield_kha_m_standard_02_mk1_macro': {
        'max_shield':     4800,
    },
    'shield_kha_m_standard_03_mk1_macro': {
        'max_shield':     4800,
    },
    'shield_kha_s_standard_01_mk1_macro': {
        'max_shield':     745,
    },
    'shield_kha_xl_standard_01_mk1_macro': {
        'max_shield':     150000,
    },
    'shield_par_l_standard_01_mk1_macro': {
        'max_shield':     40320,
    },
    'shield_par_l_standard_01_mk2_macro': {
        'max_shield':     48000,
    },
    'shield_par_m_standard_01_mk1_macro': {
        'max_shield':     4000,
    },
    'shield_par_m_standard_01_mk2_macro': {
        'max_shield':     5400,
    },
    'shield_par_m_standard_02_mk1_macro': {
        'max_shield':     4000,
    },
    'shield_par_m_standard_02_mk2_macro': {
        'max_shield':     5200,
    },
    'shield_par_s_racer_01_mk1_macro': {
        'max_shield':     1289,
    },
    'shield_par_s_standard_01_mk1_macro': {
        'max_shield':     760,
    },
    'shield_par_s_standard_01_mk2_macro': {
        'max_shield':     960,
    },
    'shield_par_s_standard_01_mk3_macro': {
        'max_shield':     1360,
    },
    'shield_par_xl_standard_01_mk1_macro': {
        'max_shield':     103585,
    },
    'shield_pir_xl_battleship_01_standard_01_mk1_macro': {
        'max_shield':     158600,
    },
    'shield_spl_l_standard_01_mk1_macro': {
        'max_shield':     38845,
    },
    'shield_spl_l_standard_01_mk2_macro': {
        'max_shield':     46886,
    },
    'shield_spl_m_standard_01_mk1_macro': {
        'max_shield':     3848,
    },
    'shield_spl_m_standard_01_mk2_macro': {
        'max_shield':     4932,
    },
    'shield_spl_m_standard_02_mk1_macro': {
        'max_shield':     3848,
    },
    'shield_spl_m_standard_02_mk2_macro': {
        'max_shield':     4932,
    },
    'shield_spl_s_standard_01_mk1_macro': {
        'max_shield':     740,
    },
    'shield_spl_s_standard_01_mk2_macro': {
        'max_shield':     888,
    },
    'shield_spl_s_standard_01_mk3_macro': {
        'max_shield':     1258,
    },
    'shield_spl_xl_standard_01_mk1_macro': {
        'max_shield':     100800,
    },
    'shield_tel_l_standard_01_mk1_macro': {
        'max_shield':     66082,
    },
    'shield_tel_l_standard_01_mk2_macro': {
        'max_shield':     78000,
    },
    'shield_tel_m_standard_01_mk1_macro': {
        'max_shield':     6500,
    },
    'shield_tel_m_standard_01_mk2_macro': {
        'max_shield':     8840,
    },
    'shield_tel_m_standard_02_mk1_macro': {
        'max_shield':     6500,
    },
    'shield_tel_m_standard_02_mk2_macro': {
        'max_shield':     8840,
    },
    'shield_tel_s_racer_01_mk1_macro': {
        'max_shield':     450,
    },
    'shield_tel_s_standard_01_mk1_macro': {
        'max_shield':     1300,
    },
    'shield_tel_s_standard_01_mk2_macro': {
        'max_shield':     1625,
    },
    'shield_tel_s_standard_01_mk3_macro': {
        'max_shield':     2366,
    },
    'shield_tel_xl_standard_01_mk1_macro': {
        'max_shield':     181791,
    },
    'shield_ter_l_standard_01_mk1_macro': {
        'max_shield':     57600,
    },
    'shield_ter_l_standard_01_mk2_macro': {
        'max_shield':     71424,
    },
    'shield_ter_l_standard_01_mk3_macro': {
        'max_shield':     86400,
    },
    'shield_ter_l_standard_02_mk1_macro': {
        'max_shield':     57600,
    },
    'shield_ter_l_standard_02_mk2_macro': {
        'max_shield':     71424,
    },
    'shield_ter_l_standard_02_mk3_macro': {
        'max_shield':     86400,
    },
    'shield_ter_m_standard_01_mk1_macro': {
        'max_shield':     6000,
    },
    'shield_ter_m_standard_01_mk2_macro': {
        'max_shield':     7800,
    },
    'shield_ter_m_standard_01_mk3_macro': {
        'max_shield':     9720,
    },
    'shield_ter_m_standard_02_mk1_macro': {
        'max_shield':     6000,
    },
    'shield_ter_m_standard_02_mk2_macro': {
        'max_shield':     7800,
    },
    'shield_ter_m_standard_02_mk3_macro': {
        'max_shield':     9720,
    },
    'shield_ter_m_standard_04_mk1_macro': {
        'max_shield':     6000,
    },
    'shield_ter_m_standard_04_mk2_macro': {
        'max_shield':     7800,
    },
    'shield_ter_m_standard_04_mk3_macro': {
        'max_shield':     9720,
    },
    'shield_ter_m_virtual_01_mk1_macro': {
        'max_shield':     6000,
    },
    'shield_ter_m_virtual_01_mk2_macro': {
        'max_shield':     7800,
    },
    'shield_ter_m_virtual_01_mk3_macro': {
        'max_shield':     9720,
    },
    'shield_ter_s_standard_01_mk1_macro': {
        'max_shield':     1200,
    },
    'shield_ter_s_standard_01_mk2_macro': {
        'max_shield':     1440,
    },
    'shield_ter_s_standard_01_mk3_macro': {
        'max_shield':     2100,
    },
    'shield_ter_s_virtual_01_mk1_macro': {
        'max_shield':     1440,
    },
    'shield_ter_s_virtual_01_mk1_story_macro': {
        'max_shield':     7500,
    },
    'shield_ter_s_xperimental_01_mk1_story_macro': {
        'max_shield':     7500,
    },
    'shield_ter_s_xperimental_01_mk5_macro': {
        'max_shield':     4800,
    },
    'shield_ter_xl_standard_01_mk1_macro': {
        'max_shield':     155377,
    },
    'shield_ter_xl_standard_01_mk2_macro': {
        'max_shield':     195775,
    },
    'shield_xen_l_standard_01_mk1_macro': {
        'max_shield':     45600,
    },
    'shield_xen_l_standard_01_mk2_macro': {
        'max_shield':     54355,
    },
    'shield_xen_l_standard_02_mk1_macro': {
        'max_shield':     48000,
    },
    'shield_xen_l_standard_02_mk2_macro': {
        'max_shield':     54720,
    },
    'shield_xen_m_standard_01_mk1_macro': {
        'max_shield':     4750,
    },
    'shield_xen_m_standard_01_mk2_macro': {
        'max_shield':     5662,
    },
    'shield_xen_m_standard_02_mk1_macro': {
        'max_shield':     4750,
    },
    'shield_xen_m_standard_02_mk2_macro': {
        'max_shield':     5662,
    },
    'shield_xen_m_standard_04_mk1_macro': {
        'max_shield':     4750,
    },
    'shield_xen_m_virtual_01_mk1_macro': {
        'max_shield':     5662,
    },
    'shield_xen_s_standard_01_mk1_macro': {
        'max_shield':     950,
    },
    'shield_xen_s_standard_01_mk2_macro': {
        'max_shield':     1188,
    },
    'shield_xen_s_virtual_01_mk1_macro': {
        'max_shield':     1188,
    },
    'shield_xen_xl_mothership_01_mk1_macro': {
        'max_shield':     86060,
    },
    'shield_xen_xl_standard_01_mk1_macro': {
        'max_shield':     135000,
    },
    'shield_xen_xl_standard_02_mk1_macro': {
        'max_shield':     135000,
    },
    'storage_arg_l_container_01_macro': {
        'max_hull':       565000,
        'cargo_capacity': 1000000,
    },
    'storage_arg_l_liquid_01_macro': {
        'max_hull':       565000,
        'cargo_capacity': 1000000,
    },
    'storage_arg_l_solid_01_macro': {
        'max_hull':       565000,
        'cargo_capacity': 1000000,
    },
    'storage_arg_l_tradestation_01_macro': {
        'max_hull':       643000,
        'cargo_capacity': 300000,
    },
    'storage_arg_m_container_01_macro': {
        'max_hull':       285000,
        'cargo_capacity': 250000,
    },
    'storage_arg_m_liquid_01_macro': {
        'max_hull':       285000,
        'cargo_capacity': 500000,
    },
    'storage_arg_m_solid_01_macro': {
        'max_hull':       285000,
        'cargo_capacity': 500000,
    },
    'storage_arg_s_container_01_macro': {
        'max_hull':       114000,
        'cargo_capacity': 50000,
    },
    'storage_arg_s_liquid_01_macro': {
        'max_hull':       114000,
        'cargo_capacity': 100000,
    },
    'storage_arg_s_solid_01_macro': {
        'max_hull':       114000,
        'cargo_capacity': 100000,
    },
    'storage_bor_l_container_01_macro': {
        'max_hull':       775000,
        'cargo_capacity': 1000000,
    },
    'storage_bor_l_liquid_01_macro': {
        'max_hull':       765000,
        'cargo_capacity': 1000000,
    },
    'storage_bor_l_solid_01_macro': {
        'max_hull':       769000,
        'cargo_capacity': 1000000,
    },
    'storage_bor_m_container_01_macro': {
        'max_hull':       315000,
        'cargo_capacity': 250000,
    },
    'storage_bor_m_liquid_01_macro': {
        'max_hull':       307000,
        'cargo_capacity': 500000,
    },
    'storage_bor_m_solid_01_macro': {
        'max_hull':       311000,
        'cargo_capacity': 500000,
    },
    'storage_bor_s_container_01_macro': {
        'max_hull':       135000,
        'cargo_capacity': 50000,
    },
    'storage_bor_s_liquid_01_macro': {
        'max_hull':       126000,
        'cargo_capacity': 100000,
    },
    'storage_bor_s_solid_01_macro': {
        'max_hull':       132000,
        'cargo_capacity': 100000,
    },
    'storage_gen_buildstorage_01_macro': {
        'cargo_capacity': 2000000000,
    },
    'storage_par_l_container_01_macro': {
        'max_hull':       653000,
        'cargo_capacity': 1000000,
    },
    'storage_par_l_liquid_01_macro': {
        'max_hull':       653000,
        'cargo_capacity': 1000000,
    },
    'storage_par_l_solid_01_macro': {
        'max_hull':       653000,
        'cargo_capacity': 1000000,
    },
    'storage_par_m_container_01_macro': {
        'max_hull':       304000,
        'cargo_capacity': 250000,
    },
    'storage_par_m_liquid_01_macro': {
        'max_hull':       304000,
        'cargo_capacity': 500000,
    },
    'storage_par_m_solid_01_macro': {
        'max_hull':       304000,
        'cargo_capacity': 500000,
    },
    'storage_par_s_container_01_macro': {
        'max_hull':       133000,
        'cargo_capacity': 50000,
    },
    'storage_par_s_liquid_01_macro': {
        'max_hull':       133000,
        'cargo_capacity': 100000,
    },
    'storage_par_s_solid_01_macro': {
        'max_hull':       133000,
        'cargo_capacity': 100000,
    },
    'storage_pir_l_condensate_01_macro': {
        'max_hull':       1000000,
        'cargo_capacity': 50,
    },
    'storage_pir_s_condensate_01_macro': {
        'max_hull':       100000,
        'cargo_capacity': 10000,
    },
    'storage_spl_l_container_01_macro': {
        'max_hull':       778000,
        'cargo_capacity': 1000000,
    },
    'storage_spl_l_liquid_01_macro': {
        'max_hull':       778000,
        'cargo_capacity': 1000000,
    },
    'storage_spl_l_solid_01_macro': {
        'max_hull':       778000,
        'cargo_capacity': 1000000,
    },
    'storage_spl_m_container_01_macro': {
        'max_hull':       345000,
        'cargo_capacity': 250000,
    },
    'storage_spl_m_liquid_01_macro': {
        'max_hull':       345000,
        'cargo_capacity': 500000,
    },
    'storage_spl_m_solid_01_macro': {
        'max_hull':       345000,
        'cargo_capacity': 500000,
    },
    'storage_spl_s_container_01_macro': {
        'max_hull':       157000,
        'cargo_capacity': 50000,
    },
    'storage_spl_s_liquid_01_macro': {
        'max_hull':       157000,
        'cargo_capacity': 100000,
    },
    'storage_spl_s_solid_01_macro': {
        'max_hull':       157000,
        'cargo_capacity': 100000,
    },
    'storage_tel_l_container_01_macro': {
        'max_hull':       531000,
        'cargo_capacity': 1000000,
    },
    'storage_tel_l_liquid_01_macro': {
        'max_hull':       531000,
        'cargo_capacity': 1000000,
    },
    'storage_tel_l_solid_01_macro': {
        'max_hull':       531000,
        'cargo_capacity': 1000000,
    },
    'storage_tel_m_container_01_macro': {
        'max_hull':       259000,
        'cargo_capacity': 250000,
    },
    'storage_tel_m_liquid_01_macro': {
        'max_hull':       259000,
        'cargo_capacity': 500000,
    },
    'storage_tel_m_solid_01_macro': {
        'max_hull':       259000,
        'cargo_capacity': 500000,
    },
    'storage_tel_s_container_01_macro': {
        'max_hull':       111000,
        'cargo_capacity': 50000,
    },
    'storage_tel_s_liquid_01_macro': {
        'max_hull':       111000,
        'cargo_capacity': 100000,
    },
    'storage_tel_s_solid_01_macro': {
        'max_hull':       111000,
        'cargo_capacity': 100000,
    },
    'storage_ter_l_container_01_macro': {
        'max_hull':       1000000,
        'cargo_capacity': 1000000,
    },
    'storage_ter_l_liquid_01_macro': {
        'max_hull':       1000000,
        'cargo_capacity': 1000000,
    },
    'storage_ter_l_solid_01_macro': {
        'max_hull':       1000000,
        'cargo_capacity': 1000000,
    },
    'storage_ter_m_container_01_macro': {
        'max_hull':       450000,
        'cargo_capacity': 500000,
    },
    'storage_ter_m_container_tradestation_01_macro': {
        'max_hull':       600000,
        'cargo_capacity': 300000,
    },
    'storage_ter_m_liquid_01_macro': {
        'max_hull':       450000,
        'cargo_capacity': 500000,
    },
    'storage_ter_m_solid_01_macro': {
        'max_hull':       450000,
        'cargo_capacity': 500000,
    },
    'storage_ter_s_container_01_macro': {
        'max_hull':       150000,
        'cargo_capacity': 100000,
    },
    'storage_ter_s_liquid_01_macro': {
        'max_hull':       150000,
        'cargo_capacity': 100000,
    },
    'storage_ter_s_liquid_tradestation_01_macro': {
        'max_hull':       300000,
        'cargo_capacity': 100000,
    },
    'storage_ter_s_solid_01_macro': {
        'max_hull':       150000,
        'cargo_capacity': 100000,
    },
    'struct_arg_arc_01_macro': {
        'max_hull':       290000,
    },
    'struct_arg_base_01_macro': {
        'max_hull':       150000,
    },
    'struct_arg_base_02_macro': {
        'max_hull':       237000,
    },
    'struct_arg_base_03_macro': {
        'max_hull':       280000,
    },
    'struct_arg_cross_01_macro': {
        'max_hull':       120000,
    },
    'struct_arg_cross_02_macro': {
        'max_hull':       110000,
    },
    'struct_arg_cross_03_macro': {
        'max_hull':       100000,
    },
    'struct_arg_cross_04_macro': {
        'max_hull':       90000,
    },
    'struct_arg_cross_05_macro': {
        'max_hull':       80000,
    },
    'struct_arg_vertical_01_macro': {
        'max_hull':       79000,
    },
    'struct_arg_vertical_02_macro': {
        'max_hull':       143000,
    },
    'struct_at_xen_shell_macro': {
        'max_hull':       120000,
    },
    'struct_bor_base_01_macro': {
        'max_hull':       74000,
    },
    'struct_bor_base_02_macro': {
        'max_hull':       140000,
    },
    'struct_bor_base_03_macro': {
        'max_hull':       213000,
    },
    'struct_bor_base_04_macro': {
        'max_hull':       225000,
    },
    'struct_bor_base_05_macro': {
        'max_hull':       260000,
    },
    'struct_bor_cross_01_macro': {
        'max_hull':       110000,
    },
    'struct_bor_cross_02_macro': {
        'max_hull':       165000,
    },
    'struct_bor_vertical_01_macro': {
        'max_hull':       68000,
    },
    'struct_bor_vertical_02_macro': {
        'max_hull':       132000,
    },
    'struct_gen_observationdeck_01_macro': {
        'max_hull':       170000,
    },
    'struct_gen_observationdeck_02_macro': {
        'max_hull':       170000,
    },
    'struct_gen_observationdeck_03_macro': {
        'max_hull':       170000,
    },
    'struct_gen_venturerbase_01_macro': {
        'max_hull':       237000,
    },
    'struct_gen_venturerbase_02_macro': {
        'max_hull':       150000,
    },
    'struct_gen_venturerbase_03_macro': {
        'max_hull':       280000,
    },
    'struct_gen_venturercross_01_macro': {
        'max_hull':       120000,
    },
    'struct_gen_venturervertical_01_macro': {
        'max_hull':       79000,
    },
    'struct_gen_venturervertical_02_macro': {
        'max_hull':       143000,
    },
    'struct_par_base_01_macro': {
        'max_hull':       110000,
    },
    'struct_par_base_02_macro': {
        'max_hull':       230000,
    },
    'struct_par_base_03_macro': {
        'max_hull':       370000,
    },
    'struct_par_cross_01_macro': {
        'max_hull':       90000,
    },
    'struct_par_cross_02_macro': {
        'max_hull':       370000,
    },
    'struct_par_cross_03_macro': {
        'max_hull':       230000,
    },
    'struct_par_vertical_01_macro': {
        'max_hull':       79000,
    },
    'struct_par_vertical_02_macro': {
        'max_hull':       143000,
    },
    'struct_spl_base_01_macro': {
        'max_hull':       150000,
    },
    'struct_spl_base_02_macro': {
        'max_hull':       237000,
    },
    'struct_spl_base_03_macro': {
        'max_hull':       280000,
    },
    'struct_spl_cross_01_macro': {
        'max_hull':       120000,
    },
    'struct_spl_vertical_01_macro': {
        'max_hull':       79000,
    },
    'struct_spl_vertical_02_macro': {
        'max_hull':       143000,
    },
    'struct_tel_base_01_macro': {
        'max_hull':       150000,
    },
    'struct_tel_base_02_macro': {
        'max_hull':       238000,
    },
    'struct_tel_base_03_macro': {
        'max_hull':       280000,
    },
    'struct_tel_cross_01_macro': {
        'max_hull':       120000,
    },
    'struct_tel_vertical_01_macro': {
        'max_hull':       79000,
    },
    'struct_tel_vertical_02_macro': {
        'max_hull':       143000,
    },
    'struct_ter_base_01_macro': {
        'max_hull':       75000,
    },
    'struct_ter_base_02_macro': {
        'max_hull':       150000,
    },
    'struct_ter_base_03_macro': {
        'max_hull':       300000,
    },
    'struct_ter_cross_01_macro': {
        'max_hull':       300000,
    },
    'struct_ter_vertical_01_macro': {
        'max_hull':       75000,
    },
    'struct_ter_vertical_02_macro': {
        'max_hull':       150000,
    },
    'torus_maze_macro': {
        'max_hull':       1000000,
    },
    'torus_turretbase_macro': {
        'max_hull':       1500,
    },
    'torus_turretbase_v2_macro': {
        'max_hull':       1500,
    },
    'ventureplatform_gen_cross_01_macro': {
        'max_hull':       430000,
    },
    'welfare_bor_artacademy_01_macro': {
        'max_hull':       305000,
    },
    'welfare_gen_casino_01_macro': {
        'max_hull':       250000,
    },
    'welfare_gen_gamblinghall_01_macro': {
        'max_hull':       100000,
    },
    'xenon_asteroid_01_part_01_macro': {
        'max_hull':       1000000,
    },
    'xenon_asteroid_01_part_02_macro': {
        'max_hull':       1000000,
    },
    'xenon_asteroid_01_part_03_macro': {
        'max_hull':       1000000,
    },
    'xenon_asteroid_01_part_04_macro': {
        'max_hull':       1000000,
    },
    'xenon_asteroid_02_part_01_macro': {
        'max_hull':       10000,
    },
    'xenon_asteroid_02_part_02_macro': {
        'max_hull':       10000,
    },
    'xenon_asteroid_02_part_03_macro': {
        'max_hull':       10000,
    },
    'xenon_asteroid_03_macro': {
        'max_hull':       1000000,
    },
    'xenon_asteroid_philae_01_macro': {
        'max_hull':       200,
    },
    'xenon_small_station_01_base_macro': {
        'max_hull':       2640000,
    },
    'xenon_small_station_01_solarpanel_01_macro': {
        'max_hull':       800000,
        'produces':       'energycells',
    },
    'xenon_small_station_01_storage_01_macro': {
        'max_hull':       250000,
        'cargo_capacity': 250000,
    },
}
